import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { createClient as createServerClient } from "@/lib/supabase/server";

function admin(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SECRET_KEY;if(!u||!k)throw new Error("Missing Supabase configuration");return createClient(u,k)}
function cutoff(){return new Date(Date.now()-24*60*60*1000).toISOString()}
async function ai(prompt:string){const key=process.env.GEMINI_API_KEY;if(!key)return null;const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.45}})});if(!r.ok)return null;const j=await r.json();return j?.candidates?.[0]?.content?.parts?.map((p:{text?:string})=>p.text||"").join("").trim()||null}
async function context(){const auth=await createServerClient();const{data:{user}}=await auth.auth.getUser();if(!user)return null;const s=admin();const{data:profile}=await s.from("user_profiles").select("company_id,role,full_name,username,nickname").eq("user_id",user.id).maybeSingle();if(!profile?.company_id)return {user,s,profile:null};return {user,s,profile}}
async function cleanOld(s:ReturnType<typeof admin>,userId:string,companyId:string){const old=await s.from("ai_help_sessions").select("id").eq("user_id",userId).eq("company_id",companyId).lt("updated_at",cutoff());const ids=(old.data||[]).map((x:{id:string})=>x.id);if(ids.length){await s.from("ai_help_messages").delete().in("session_id",ids);await s.from("ai_help_sessions").delete().in("id",ids)}}

export async function GET(){try{const c=await context();if(!c)return NextResponse.json({error:"Unauthorized"},{status:401});if(!c.profile)return NextResponse.json({session:null,messages:[]});await cleanOld(c.s,c.user.id,c.profile.company_id);const{data:session}=await c.s.from("ai_help_sessions").select("id,handling_mode,status,updated_at").eq("user_id",c.user.id).eq("company_id",c.profile.company_id).gte("updated_at",cutoff()).order("updated_at",{ascending:false}).limit(1).maybeSingle();if(!session)return NextResponse.json({session:null,messages:[]});const{data:messages}=await c.s.from("ai_help_messages").select("id,role,message,created_at").eq("session_id",session.id).gte("created_at",cutoff()).order("created_at",{ascending:true}).limit(80);return NextResponse.json({session,messages:messages||[],memory_hours:24})}catch(e){console.error(e);return NextResponse.json({error:"Internal server error"},{status:500})}}

export async function POST(req:NextRequest){try{const c=await context();if(!c)return NextResponse.json({error:"Unauthorized"},{status:401});if(!c.profile)return NextResponse.json({error:"Company not configured"},{status:409});const text=String((await req.json()).message||"").trim().slice(0,2000);if(!text)return NextResponse.json({error:"Message is required"},{status:400});await cleanOld(c.s,c.user.id,c.profile.company_id);let{data:session}=await c.s.from("ai_help_sessions").select("id,handling_mode,status").eq("user_id",c.user.id).eq("company_id",c.profile.company_id).gte("updated_at",cutoff()).order("updated_at",{ascending:false}).limit(1).maybeSingle();if(!session){const created=await c.s.from("ai_help_sessions").insert({user_id:c.user.id,company_id:c.profile.company_id,status:"open",handling_mode:"ai"}).select("id,handling_mode,status").single();if(created.error)throw created.error;session=created.data}await c.s.from("ai_help_messages").insert({session_id:session.id,user_id:c.user.id,role:"user",message:text});let reply="وصلتني رسالتك. أنا AVERO Care Agent، رح ساعدك خطوة خطوة.";if(session.handling_mode==="ai"){const history=await c.s.from("ai_help_messages").select("role,message").eq("session_id",session.id).gte("created_at",cutoff()).order("created_at",{ascending:false}).limit(10);const answer=await ai(`You are Rex, AVERO customer care agent. Reply in simple Lebanese/Arabic when the user writes Arabic. Be practical and short. Your memory is strictly the last 24 hours only. Do not infer or mention older chats.\nUser profile:${JSON.stringify(c.profile)}\nRecent messages:${JSON.stringify((history.data||[]).reverse())}\nUser message:${text}`);if(answer)reply=answer}else reply="المحادثة حالياً مع إنسان من فريق الدعم. وصلت رسالتك ورح يرد عليك.";const{data:assistant}=await c.s.from("ai_help_messages").insert({session_id:session.id,user_id:c.user.id,role:"assistant",message:reply}).select("id,role,message,created_at").single();await c.s.from("ai_help_sessions").update({updated_at:new Date().toISOString(),status:"open"}).eq("id",session.id);return NextResponse.json({ok:true,session_id:session.id,reply:assistant,memory_hours:24})}catch(e){console.error(e);return NextResponse.json({error:"Internal server error"},{status:500})}}
