import { createClient } from "@supabase/supabase-js";
import sharp from "sharp";

const GRAPH_VERSION = process.env.META_GRAPH_VERSION || "v24.0";

function db() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SECRET_KEY;
  if (!url || !key) throw new Error("Missing Supabase configuration");
  return createClient(url, key);
}

function authorized(request: Request) {
  const secret = process.env.CRON_SECRET;
  if (!secret) return false;
  return (request.headers.get("authorization") || "").replace(/^Bearer\s+/i, "").trim() === secret;
}

function esc(value: unknown) {
  return String(value || "").replace(/[&<>]/g, (m) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[m] || m));
}

async function media(s: any, item: any, companyId: string) {
  if (item.media_url) return item.media_url;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1080"><rect width="1080" height="1080" fill="#020617"/><circle cx="870" cy="160" r="250" fill="#7c3aed" opacity=".2"/><text x="90" y="150" fill="#c4b5fd" font-family="Arial" font-size="28" font-weight="700">FOXY MARKETING</text><foreignObject x="90" y="270" width="900" height="520"><div xmlns="http://www.w3.org/1999/xhtml" style="font-family:Arial;color:white;font-size:68px;font-weight:800;line-height:1.1">${esc(item.campaign_name || item.caption || "Marketing")}</div></foreignObject><text x="90" y="940" fill="#94a3b8" font-family="Arial" font-size="25">Generated by AVERO OS</text></svg>`;
  const buf = await sharp(Buffer.from(svg)).jpeg({ quality: 88 }).toBuffer();
  const path = `${companyId}/${item.id}-auto.jpg`;
  const up = await s.storage.from("marketing-media").upload(path, buf, { contentType: "image/jpeg", upsert: true });
  if (up.error) throw up.error;
  const url = s.storage.from("marketing-media").getPublicUrl(path).data.publicUrl;
  await s.from("marketing_content_queue").update({ media_url: url, updated_at: new Date().toISOString() }).eq("id", item.id);
  return url;
}

async function post(path: string, body: Record<string, string>) {
  const res = await fetch(`https://graph.facebook.com/${GRAPH_VERSION}/${path}`, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams(body),
  });
  const json = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(json?.error?.message || `Meta ${res.status}`);
  return json;
}

async function credential(s: any, companyId: string, platform: string) {
  const { data: connection } = await s.from("company_social_connections")
    .select("external_account_id,direct_publishing_enabled")
    .eq("company_id", companyId)
    .eq("platform", platform)
    .maybeSingle();
  let token: string | null = null;
  if (connection?.direct_publishing_enabled) {
    const { data } = await s.rpc("marketing_get_social_token", { p_company_id: companyId, p_platform: platform });
    token = typeof data === "string" && data.trim() ? data : null;
  }
  return { id: connection?.external_account_id || null, token };
}

export async function GET(request: Request) {
  if (!authorized(request)) return Response.json({ error: "Unauthorized" }, { status: 401 });
  const s = db();
  const now = new Date().toISOString();
  try {
    const { data: rows } = await s.from("marketing_content_queue").select("*").eq("status", "scheduled").lte("scheduled_for", now).order("scheduled_for", { ascending: true }).limit(20);
    let published = 0;
    for (const item of rows || []) {
      const { data: setting } = await s.from("marketing_schedule_settings").select("mode,enabled").eq("company_id", item.company_id).maybeSingle();
      if (!setting?.enabled || setting.mode !== "automatic") continue;
      await s.from("marketing_content_queue").update({ status: "publishing", updated_at: now }).eq("id", item.id);
      try {
        const platforms = Array.isArray(item.platforms) ? item.platforms : [item.channel].filter(Boolean);
        const caption = [item.caption, ...(item.hashtags || []).map((x: string) => `#${String(x).replace(/^#/, "")}`)].filter(Boolean).join("\n\n");
        const results: any[] = [];
        let mediaUrl = item.media_url || null;
        if (platforms.includes("instagram") && !mediaUrl) mediaUrl = await media(s, item, item.company_id);

        const fb = await credential(s, item.company_id, "facebook");
        const ig = await credential(s, item.company_id, "instagram");

        if (platforms.includes("facebook")) {
          if (!fb.id || !fb.token) throw new Error("Facebook Direct Publishing is not connected for this company.");
          const x = mediaUrl
            ? await post(`${fb.id}/photos`, { url: mediaUrl, caption, access_token: fb.token })
            : await post(`${fb.id}/feed`, { message: caption, access_token: fb.token });
          results.push({ platform: "facebook", id: x.post_id || x.id });
        }

        if (platforms.includes("instagram")) {
          const token = ig.token || fb.token;
          if (!ig.id || !token || !mediaUrl) throw new Error("Instagram Direct Publishing is not connected for this company.");
          const container = await post(`${ig.id}/media`, { image_url: mediaUrl, caption: caption.slice(0, 2200), access_token: token });
          const p = await post(`${ig.id}/media_publish`, { creation_id: String(container.id), access_token: token });
          results.push({ platform: "instagram", id: p.id });
        }

        const unsupported = platforms.filter((p: string) => !["facebook", "instagram"].includes(p));
        await s.from("marketing_content_queue").update({
          status: "published",
          published_at: new Date().toISOString(),
          external_post_id: results.map((x) => `${x.platform}:${x.id}`).join(",") || null,
          error_message: unsupported.length ? `Not auto-connected yet: ${unsupported.join(", ")}` : null,
          metrics: { ...(item.metrics || {}), publisher: "foxy_auto_vercel", publishing_result: results },
          updated_at: new Date().toISOString(),
        }).eq("id", item.id);
        await s.from("ai_agent_runs").insert({ company_id: item.company_id, agent_key: "ai_marketing", action: "automatic_publish", status: "completed", input: { content_id: item.id, scheduled_for: item.scheduled_for }, output: { results }, completed_at: new Date().toISOString() });
        published++;
      } catch (e) {
        const reason = e instanceof Error ? e.message : "Auto publish failed";
        await s.from("marketing_content_queue").update({ status: "failed", error_message: reason, updated_at: new Date().toISOString() }).eq("id", item.id);
        await s.from("ai_agent_runs").insert({ company_id: item.company_id, agent_key: "ai_marketing", action: "automatic_publish", status: "failed", input: { content_id: item.id }, error_message: reason, completed_at: new Date().toISOString() });
      }
    }
    return Response.json({ ok: true, due: rows?.length || 0, published });
  } catch (e) {
    console.error(e);
    return Response.json({ error: "Automatic publishing failed" }, { status: 500 });
  }
}
