import sharp from "sharp";
import { createAdminClient } from "@/lib/supabase/admin";
import { publishMarketingContent } from "@/lib/marketing/publisher";

function authorized(request: Request) {
  const secret = process.env.CRON_SECRET;
  if (!secret) return false;
  return (request.headers.get("authorization") || "").replace(/^Bearer\s+/i, "").trim() === secret;
}

function esc(value: unknown) {
  return String(value || "").replace(/[&<>]/g, (m) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[m] || m));
}

async function media(s: any, item: any, companyId: string) {
  if (item.media_url) return item.media_url;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1080"><rect width="1080" height="1080" fill="#020617"/><circle cx="870" cy="160" r="250" fill="#7c3aed" opacity=".2"/><text x="90" y="150" fill="#c4b5fd" font-family="Arial" font-size="28" font-weight="700">FOXY MARKETING</text><foreignObject x="90" y="270" width="900" height="520"><div xmlns="http://www.w3.org/1999/xhtml" style="font-family:Arial;color:white;font-size:68px;font-weight:800;line-height:1.1">${esc(item.campaign_name || item.caption || "Marketing")}</div></foreignObject><text x="90" y="940" fill="#94a3b8" font-family="Arial" font-size="25">Generated by AVERO OS</text></svg>`;
  const buf = await sharp(Buffer.from(svg)).jpeg({ quality: 88 }).toBuffer();
  const path = `${companyId}/${item.id}-auto.jpg`;
  const up = await s.storage.from("marketing-media").upload(path, buf, { contentType: "image/jpeg", upsert: true });
  if (up.error) throw up.error;
  const url = s.storage.from("marketing-media").getPublicUrl(path).data.publicUrl;
  await s.from("marketing_content_queue").update({ media_url: url, updated_at: new Date().toISOString() }).eq("id", item.id);
  return url;
}

export async function GET(request: Request) {
  if (!authorized(request)) return Response.json({ error: "Unauthorized" }, { status: 401 });
  const s = createAdminClient();
  const now = new Date().toISOString();

  try {
    const { data: rows, error: rowsError } = await s.from("marketing_content_queue")
      .select("*")
      .eq("status", "scheduled")
      .lte("scheduled_for", now)
      .order("scheduled_for", { ascending: true })
      .limit(20);

    if (rowsError) throw rowsError;

    let published = 0;
    let failed = 0;

    for (const item of rows || []) {
      const { data: setting } = await s.from("marketing_schedule_settings")
        .select("mode,enabled")
        .eq("company_id", item.company_id)
        .maybeSingle();

      if (!setting?.enabled || setting.mode !== "automatic") continue;

      await s.from("marketing_content_queue").update({ status: "publishing", updated_at: now }).eq("id", item.id);

      try {
        const platforms = Array.isArray(item.platforms) ? item.platforms : [item.channel].filter(Boolean);
        let mediaUrl = item.media_url || null;
        if (platforms.includes("instagram") && !mediaUrl) mediaUrl = await media(s, item, item.company_id);

        const results = await publishMarketingContent(s, item.company_id, item, platforms, mediaUrl);
        const complete = results.length > 0 && results.every((result) => result.status === "published");
        const somePublished = results.some((result) => result.status === "published");
        const status = somePublished ? "published" : "failed";
        const errorMessage = complete
          ? null
          : results.map((result) => `${result.platform}: ${result.status}${result.note ? ` - ${result.note}` : ""}`).join(" | ");

        await s.from("marketing_content_queue").update({
          status,
          published_at: somePublished ? new Date().toISOString() : null,
          external_post_id: results.filter((result) => result.id).map((result) => `${result.platform}:${result.id}`).join(",") || null,
          error_message: errorMessage,
          metrics: { ...(item.metrics || {}), publisher: "foxy_auto_router", publishing_result: results },
          updated_at: new Date().toISOString(),
        }).eq("id", item.id);

        await s.from("ai_agent_runs").insert({
          company_id: item.company_id,
          agent_key: "ai_marketing",
          action: "automatic_publish",
          status: somePublished ? "completed" : "failed",
          input: { content_id: item.id, scheduled_for: item.scheduled_for, platforms },
          output: { results },
          error_message: errorMessage,
          completed_at: new Date().toISOString(),
        });

        if (somePublished) published++;
        else failed++;
      } catch (error) {
        const reason = error instanceof Error ? error.message : "Auto publish failed";
        await s.from("marketing_content_queue").update({
          status: "failed",
          error_message: reason,
          updated_at: new Date().toISOString(),
        }).eq("id", item.id);

        await s.from("ai_agent_runs").insert({
          company_id: item.company_id,
          agent_key: "ai_marketing",
          action: "automatic_publish",
          status: "failed",
          input: { content_id: item.id },
          error_message: reason,
          completed_at: new Date().toISOString(),
        });
        failed++;
      }
    }

    return Response.json({ ok: true, due: rows?.length || 0, published, failed });
  } catch (error) {
    console.error("Foxy automatic publishing error", error);
    return Response.json({ error: "Automatic publishing failed" }, { status: 500 });
  }
}
