"use client";
import {useEffect,useState} from 'react';
import {useLanguage} from './LanguageProvider';
const card='rounded-2xl border border-slate-800 bg-slate-900 p-5';
export default function AccountingWorkspace(){
 const{language}=useLanguage(),ar=language==='ar',L=(e:string,a:string)=>ar?a:e;
 const[d,S]=useState<any>({balances:{},journals:[]}),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch('/api/accounting',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(j=>j&&S(j)).finally(()=>setLoading(false))},[]);
 const b=d.balances||{},money=(n:any)=>`${Math.abs(Number(n||0)).toFixed(2)} SAR`;
 const kpis=[['4000',L('Sales Revenue','إيرادات المبيعات'),'credit'],['2100',L('VAT Payable','ضريبة القيمة المضافة المستحقة'),'credit'],['1100',L('Inventory Asset','أصل المخزون'),'debit'],['5000',L('Cost of Goods Sold','تكلفة البضاعة المباعة'),'debit']];
 return <div className="space-y-5"><div><h1 className="text-3xl font-black">{L('Accounting','المحاسبة')}</h1><p className="text-sm text-slate-400">{L('Automatic double-entry journals from completed POS sales.','قيود محاسبية مزدوجة تلقائية من مبيعات نقاط البيع المكتملة.')}</p></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{kpis.map(([code,label,nature])=>{const raw=Number(b[code]||0),display=nature==='credit'?-raw:raw;return <div key={code} className={card}><small className="text-slate-500">{code}</small><h3 className="mt-1 font-black">{label}</h3><div className="mt-3 text-2xl font-black text-cyan-300">{money(display)}</div></div>})}</div><div className={card}><h2 className="text-xl font-black">{L('Recent Journal Entries','أحدث القيود اليومية')}</h2><p className="mb-4 text-sm text-slate-500">{L('Every completed sale posts payment, revenue, VAT and COGS/inventory when applicable.','كل عملية بيع مكتملة ترحّل الدفع والإيراد والضريبة وتكلفة البضاعة/المخزون عند انطباقها.')}</p>{loading?<p className="text-slate-500">{L('Loading...','جارٍ التحميل...')}</p>:d.journals.length===0?<p className="text-slate-500">{L('No accounting journals yet. Complete a Cashier sale to create the first one.','لا توجد قيود محاسبية بعد. أكمل عملية بيع من الكاشير لإنشاء أول قيد.')}</p>:<div className="space-y-3">{d.journals.map((j:any)=><details key={j.id} className="rounded-xl border border-slate-800 bg-slate-950 p-4"><summary className="cursor-pointer list-none"><div className="flex flex-wrap items-center justify-between gap-2"><span><b>{j.entry_no}</b><small className="ml-2 text-slate-500">{j.description}</small></span><span className="text-xs text-slate-500">{new Date(j.entry_date).toLocaleString(ar?'ar-SA':'en-US')}</span></div></summary><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead className="text-slate-500"><tr><th className="py-2 text-left rtl:text-right">{L('Account','الحساب')}</th><th className="text-right">{L('Debit','مدين')}</th><th className="text-right">{L('Credit','دائن')}</th></tr></thead><tbody>{(j.lines||[]).map((l:any)=><tr key={l.id||`${l.account_id}-${l.description}`} className="border-t border-slate-800"><td className="py-2">{l.accounting_accounts?.code} · {ar?l.accounting_accounts?.name_ar:l.accounting_accounts?.name_en}</td><td className="text-right">{Number(l.debit||0).toFixed(2)}</td><td className="text-right">{Number(l.credit||0).toFixed(2)}</td></tr>)}</tbody></table></div></details>)}</div>}</div></div>
}
