"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, ArrowRight, BarChart3, CheckCircle2, Clock3, Plus, RefreshCw } from "lucide-react";

const box="rounded-2xl border border-slate-800 bg-slate-900";
const input="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm outline-none focus:border-cyan-400";
const AGENT_LABELS:any={ai_sales:"Leo",ai_marketing:"Foxy",ai_hr:"Aero",ai_support:"Gor",ai_inventory:"Vexa",ai_warehouse:"Bruno",ai_customer_care:"Rex",ai_analytics:"Nova"};

export default function AgentCrmDashboard({agentKey}:{agentKey?:string}){
 const[data,setData]=useState<any>({agents:[]}),[loading,setLoading]=useState(true),[open,setOpen]=useState(false);
 const[form,setForm]=useState<any>({agent_key:agentKey||"ai_sales",title:"",priority:"medium",record_type:"task",due_at:"",summary:"",value:0});
 async function load(){setLoading(true);const r=await fetch("/api/agent-crm"+(agentKey?"?agent="+encodeURIComponent(agentKey):""),{cache:"no-store"});if(r.ok)setData(await r.json());setLoading(false)}
 useEffect(()=>{void load()},[agentKey]);
 async function create(){if(!form.title.trim())return;const r=await fetch("/api/agent-crm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"create",...form,agent_key:agentKey||form.agent_key,due_at:form.due_at||null})});if(r.ok){setOpen(false);setForm({...form,title:"",summary:"",value:0,due_at:""});void load()}}
 async function update(id:string,status:string){await fetch("/api/agent-crm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"update",id,status})});void load()}
 const agents=data.agents||[];
 const totals=useMemo(()=>({runs:agents.reduce((n:number,a:any)=>n+Number(a.kpis.runs||0),0),failed:agents.reduce((n:number,a:any)=>n+Number(a.kpis.failed||0),0),open:agents.reduce((n:number,a:any)=>n+Number(a.kpis.open_items||0),0),value:agents.reduce((n:number,a:any)=>n+Number(a.kpis.value||0),0)}),[agents]);
 if(loading)return <div className="p-10 text-center text-slate-500">Loading AI CRM...</div>;
 return <div className="space-y-6">
   <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.28em] text-cyan-300">{agentKey?AGENT_LABELS[agentKey]+" CRM":"AVERO AI CRM"}</p><h1 className="mt-2 text-3xl font-black">{agentKey?"Agent Performance & Work Queue":"All Agents Command Center"}</h1><p className="mt-2 text-sm text-slate-400">{agentKey?"KPIs, tasks, activity and domain performance for this agent.":"One CRM for every AI department with live KPIs, work queues and health analytics."}</p></div><div className="flex gap-2"><button onClick={load} className="rounded-xl border border-slate-700 px-4 py-3 text-sm font-bold"><RefreshCw size={16}/></button><button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-xl bg-cyan-400 px-4 py-3 text-sm font-black text-slate-950"><Plus size={16}/> New CRM Item</button></div></div>
   {!agentKey&&<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><K icon={<Activity/>} label="Agent Runs" value={totals.runs}/><K icon={<AlertTriangle/>} label="Failed Runs" value={totals.failed}/><K icon={<Clock3/>} label="Open Work" value={totals.open}/><K icon={<BarChart3/>} label="Tracked Value" value={totals.value.toLocaleString()}/></div>}
   <div className={agentKey?"grid gap-5":"grid gap-5 xl:grid-cols-2"}>
    {agents.map((a:any)=><section key={a.key} className={box+" overflow-hidden"}>
      <div className="flex items-start justify-between border-b border-slate-800 p-5"><div><div className="flex items-center gap-2"><h2 className="text-2xl font-black">{a.name}</h2><span className={"rounded-full px-2 py-1 text-[10px] font-black "+(a.enabled?"bg-emerald-500/10 text-emerald-300":"bg-slate-800 text-slate-500")}>{a.enabled?"ENABLED":"OFF"}</span></div><p className="text-sm text-slate-400">{a.department}</p></div>{!agentKey&&<Link href={"/crm/agents/"+a.key} className="flex items-center gap-1 text-sm font-bold text-cyan-300">Open CRM <ArrowRight size={15}/></Link>}</div>
      <div className="grid grid-cols-2 gap-px bg-slate-800 md:grid-cols-4">{Object.entries(a.kpis||{}).slice(0,8).map(([k,v]:any)=><div key={k} className="bg-slate-900 p-4"><p className="text-[10px] uppercase tracking-wide text-slate-500">{k.replaceAll("_"," ")}</p><p className="mt-1 text-xl font-black">{typeof v==="number"?v.toLocaleString():String(v)}</p></div>)}</div>
      <div className="grid gap-4 p-5 lg:grid-cols-2"><div><h3 className="mb-3 text-sm font-black uppercase text-slate-400">Work Queue</h3>{!a.items?.length?<p className="rounded-xl border border-dashed border-slate-800 p-5 text-sm text-slate-500">No open CRM items.</p>:a.items.slice(0,8).map((i:any)=><div key={i.id} className="mb-2 rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="flex justify-between gap-2"><b className="text-sm">{i.title}</b><span className={"text-[10px] font-black "+(i.priority==="urgent"?"text-rose-300":"text-slate-500")}>{i.priority}</span></div><p className="mt-1 text-xs text-slate-500">{i.record_type+" · "+i.status+(i.due_at?" · "+new Date(i.due_at).toLocaleDateString():"")}</p>{!["done","cancelled"].includes(i.status)&&<button onClick={()=>update(i.id,"done")} className="mt-2 text-xs font-bold text-emerald-300">✓ Mark done</button>}</div>)}</div>
      <div><h3 className="mb-3 text-sm font-black uppercase text-slate-400">Recent Activity</h3>{!a.recent_runs?.length?<p className="rounded-xl border border-dashed border-slate-800 p-5 text-sm text-slate-500">No agent runs yet.</p>:a.recent_runs.slice(0,8).map((r:any)=><div key={r.id} className="mb-2 flex items-center justify-between rounded-xl border border-slate-800 bg-slate-950 p-3"><span><b className="block text-xs">{r.action}</b><small className="text-slate-500">{new Date(r.created_at).toLocaleString()}</small></span>{String(r.status).startsWith("completed")?<CheckCircle2 size={16} className="text-emerald-400"/>:<AlertTriangle size={16} className="text-rose-400"/>}</div>)}</div></div>
    </section>)}
   </div>
   {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4"><div className="w-full max-w-xl rounded-3xl border border-slate-700 bg-slate-900 p-6"><div className="flex justify-between"><h2 className="text-xl font-black">New Agent CRM Item</h2><button onClick={()=>setOpen(false)}>✕</button></div><div className="mt-5 space-y-3">{!agentKey&&<select className={input} value={form.agent_key} onChange={e=>setForm({...form,agent_key:e.target.value})}>{Object.entries(AGENT_LABELS).map(([k,v]:any)=><option key={k} value={k}>{v}</option>)}</select>}<input className={input} placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><div className="grid grid-cols-2 gap-3"><select className={input} value={form.record_type} onChange={e=>setForm({...form,record_type:e.target.value})}><option>task</option><option>opportunity</option><option>alert</option><option>follow_up</option><option>case</option></select><select className={input} value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>low</option><option>medium</option><option>high</option><option>urgent</option></select></div><input type="datetime-local" className={input} value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/><input type="number" className={input} placeholder="Value" value={form.value} onChange={e=>setForm({...form,value:Number(e.target.value)})}/><textarea className={input} placeholder="Summary / notes" value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/><button onClick={create} className="w-full rounded-xl bg-cyan-400 py-3 font-black text-slate-950">Create</button></div></div></div>}
 </div>
}
function K({icon,label,value}:any){return <div className={box+" p-5"}><div className="flex items-center gap-2 text-cyan-300">{icon}<span className="text-xs font-black uppercase">{label}</span></div><p className="mt-3 text-3xl font-black">{value}</p></div>}
