"use client";

import { useMemo, useState } from "react";
import { BarChart3, Building2, FileText, MapPin, Target, Trophy, UsersRound } from "lucide-react";
import { useLanguage } from "./LanguageProvider";

type Lead = { id:string; service_type:string|null; status:string|null; city:string|null; estimated_value?:number|null; created_at?:string|null; updated_at:string; customers:{source?:string|null}|null; };
type RangeKey = "30d" | "90d" | "year" | "all";

export default function AnalyticsWorkspaceV2({ leads }: { leads: Lead[] }) {
  const { language } = useLanguage(); const ar = language === "ar";
  const money = (value:number) => new Intl.NumberFormat(ar ? "ar-SA" : "en-SA", { style:"currency", currency:"SAR", maximumFractionDigits:0 }).format(value);
  const [range,setRange] = useState<RangeKey>("90d");
  const data = useMemo(()=>{ const now=new Date(); let start:Date|null=null; if(range==="30d") start=new Date(now.getFullYear(),now.getMonth(),now.getDate()-29); if(range==="90d") start=new Date(now.getFullYear(),now.getMonth(),now.getDate()-89); if(range==="year") start=new Date(now.getFullYear(),0,1); if(start) start.setHours(0,0,0,0); const filtered=leads.filter(l=>!start||new Date(l.created_at||l.updated_at)>=start!); const statuses=["new","qualified","quotation","negotiation","won","lost"]; const counts=Object.fromEntries(statuses.map(s=>[s,filtered.filter(l=>(l.status||"new").toLowerCase()===s).length])); const conversion=filtered.length?(counts.won/filtered.length)*100:0; const wonValue=filtered.filter(l=>(l.status||"").toLowerCase()==="won").reduce((s,l)=>s+Number(l.estimated_value||0),0); const pipelineValue=filtered.filter(l=>!["won","lost"].includes((l.status||"new").toLowerCase())).reduce((s,l)=>s+Number(l.estimated_value||0),0); const rank=(field:"service_type"|"city")=>{ const m=new Map<string,number>(); filtered.forEach(l=>{const k=(l[field]||(ar?"غير معروف":"Unknown")).trim()||(ar?"غير معروف":"Unknown");m.set(k,(m.get(k)||0)+1)}); return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6)}; const sm=new Map<string,number>(); filtered.forEach(l=>{const k=(l.customers?.source||(ar?"أخرى":"Other")).trim()||(ar?"أخرى":"Other");sm.set(k,(sm.get(k)||0)+1)}); return {filtered,counts,conversion,wonValue,pipelineValue,services:rank("service_type"),cities:rank("city"),sources:[...sm.entries()].sort((a,b)=>b[1]-a[1])}; },[leads,range,ar]);
  const stageLabel=(s:string)=> ar ? ({new:"جديد",qualified:"مؤهل",quotation:"عرض سعر",negotiation:"تفاوض",won:"تم الفوز",lost:"مفقود"} as Record<string,string>)[s]||s : s;
  const maxStage=Math.max(1,...Object.values(data.counts)); const maxService=Math.max(1,...data.services.map(([,v])=>v)); const maxCity=Math.max(1,...data.cities.map(([,v])=>v));
  const ranges:[RangeKey,string][] = ar ? [["30d","30 يومًا"],["90d","90 يومًا"],["year","هذه السنة"],["all","كل الوقت"]] : [["30d","30 Days"],["90d","90 Days"],["year","This Year"],["all","All Time"]];
  const empty=<div className="rounded-xl border border-dashed border-slate-800 py-8 text-center text-sm text-slate-500">{ar?"لا توجد بيانات متاحة لهذه الفترة.":"No data available for this period."}</div>;
  return <main className="flex-1 overflow-y-auto bg-slate-950 px-7 py-8 text-white"><div className="mx-auto max-w-[1500px] space-y-7">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.24em] text-blue-400">{ar?"ذكاء AVERO":"AVERO Intelligence"}</p><h1 className="text-3xl font-bold">{ar?"تحليلات متقدمة":"Advanced Analytics"}</h1><p className="mt-2 text-sm text-slate-400">{ar?"تحليل عميق من سجلات CRM المباشرة — دون أرقام تجريبية أو مخترعة.":"Deep analysis from live CRM records — no demo or invented numbers."}</p></div><div className="flex gap-2">{ranges.map(([key,label])=><button key={key} onClick={()=>setRange(key)} className={`rounded-lg border px-4 py-2 text-sm ${range===key?"border-blue-500 bg-blue-500/10 text-blue-300":"border-slate-700 bg-slate-900 text-slate-400"}`}>{label}</button>)}</div></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[[ar?"العملاء المحللون":"Leads Analyzed",String(data.filtered.length),UsersRound],[ar?"معدل التحويل":"Conversion Rate",`${data.conversion.toFixed(1)}%`,Target],[ar?"الصفقات المكتسبة":"Won Deals",String(data.counts.won),Trophy],[ar?"قيمة الفرص":"Pipeline Value",money(data.pipelineValue),BarChart3],[ar?"قيمة الصفقات المكتسبة":"Won Value",money(data.wonValue),Building2]].map(([label,value,Icon])=><div key={String(label)} className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><div className="mb-5 flex items-center justify-between"><span className="text-sm text-slate-400">{String(label)}</span>{typeof Icon!=="string"&&<Icon size={20} className="text-blue-400"/>}</div><div className="text-2xl font-bold">{String(value)}</div></div>)}</section>
    <section className="grid gap-5 xl:grid-cols-[1.4fr_1fr]"><Panel title={ar?"قمع المبيعات":"Sales Funnel"} subtitle={ar?"التوزيع الفعلي للعملاء حسب مرحلة CRM الحالية":"Real lead distribution by current CRM stage"} icon={BarChart3}>{Object.entries(data.counts).map(([stage,value])=><Bar key={stage} label={stageLabel(stage)} value={value} max={maxStage}/>)}</Panel><Panel title={ar?"مصادر العملاء":"Lead Sources"} subtitle={ar?"القنوات المسجلة في سجلات العملاء":"Channels recorded on customer records"} icon={Building2}><div className="space-y-3">{data.sources.length?data.sources.map(([s,c])=><div key={s} className="flex items-center justify-between rounded-xl border border-slate-800 bg-slate-950/40 px-4 py-3"><span>{s}</span><strong>{c}</strong></div>):empty}</div></Panel></section>
    <section className="grid gap-5 lg:grid-cols-2"><Panel title={ar?"أفضل الخدمات":"Top Services"} subtitle={ar?"ترتيب من سجلات CRM المباشرة":"Ranked from live CRM records"} icon={FileText}><div className="space-y-4">{data.services.length?data.services.map(([l,v])=><Bar key={l} label={l} value={v} max={maxService}/>):empty}</div></Panel><Panel title={ar?"أفضل المدن":"Top Cities"} subtitle={ar?"ترتيب من سجلات CRM المباشرة":"Ranked from live CRM records"} icon={MapPin}><div className="space-y-4">{data.cities.length?data.cities.map(([l,v])=><Bar key={l} label={l} value={v} max={maxCity}/>):empty}</div></Panel></section>
  </div></main>;
}
function Panel({title,subtitle,icon:Icon,children}:{title:string;subtitle:string;icon:typeof UsersRound;children:React.ReactNode}){return <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><div className="mb-6 flex items-center gap-3"><Icon className="text-blue-400"/><div><h2 className="text-xl font-semibold">{title}</h2><p className="text-sm text-slate-500">{subtitle}</p></div></div>{children}</div>}
function Bar({label,value,max}:{label:string;value:number;max:number}){return <div><div className="mb-1.5 flex justify-between text-sm"><span className="text-slate-300">{label}</span><span>{value}</span></div><div className="h-2 rounded-full bg-slate-800"><div className="h-full rounded-full bg-blue-500" style={{width:`${(value/max)*100}%`}}/></div></div>}
