"use client";
import{useEffect,useMemo,useState}from'react';

const panel='rounded-2xl border border-slate-800 bg-slate-900';
const btn='rounded-xl bg-cyan-400 px-4 py-3 font-black text-slate-950 disabled:opacity-40';
const ghost='rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 font-bold text-slate-300';
const inp='w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5';

export default function CashierWorkspace(){
 const[d,S]=useState<any>({products:[],categories:[],orders:[],warehouses:[],shifts:[],settings:null});
 const[x,X]=useState<any>({payment_methods:[],tables:[],best_sellers:[],cashier_name:'Cashier'});
 const[cart,K]=useState<any[]>([]),[mode,M]=useState<'hospitality'|'retail'>('hospitality'),[cat,C]=useState('all'),[q,Q]=useState(''),[service,V]=useState('dine_in');
 const[disc,D]=useState(0),[customDisc,setCustomDisc]=useState(''),[pay,P]=useState<any>(null),[table,T]=useState<any>(null),[modal,Z]=useState(''),[customer,U]=useState({name:'',phone:'',email:'',notes:''}),[heldId,H]=useState<string|null>(null),[payForm,setPayForm]=useState<any>({name:'',adjustment_percent:0,adjustment_type:'markup'}),[tableForm,setTableForm]=useState<any>({name:'',area:'Main',seats:2});
 async function load(){const[a,b]=await Promise.all([fetch('/api/sales',{cache:'no-store'}),fetch('/api/cashier-extras',{cache:'no-store'})]);if(a.ok)S(await a.json());if(b.ok)X(await b.json())}
 useEffect(()=>{load()},[]);
 const currency=d.settings?.currency||'SAR',shift=d.shifts.find((s:any)=>s.status==='open'),wh=shift?.warehouse_id||d.settings?.default_warehouse_id||d.warehouses[0]?.id,held=d.orders.filter((o:any)=>o.status==='held');
 const bestIds=new Set(x.best_sellers.map((z:any)=>z.product_id));
 const products=useMemo(()=>d.products.filter((p:any)=>p.show_on_cashier&&(cat==='all'||(cat==='best'&&bestIds.has(p.id))||p.category_id===cat)&&(!q||`${p.name} ${p.sku||''} ${p.barcode||''}`.toLowerCase().includes(q.toLowerCase()))),[d.products,cat,q,x.best_sellers]);
 const pricesIncludeTax=!!d.settings?.prices_include_tax;
 const rows=cart.map((z:any)=>{const listed=Number(z.price)*Number(z.quantity||0),rate=z.tax_enabled?Number(z.tax_rate||0):0,net=pricesIncludeTax&&rate>0?listed/(1+rate/100):listed;return{listed,rate,net}});
 const subtotal=rows.reduce((a:number,z:any)=>a+z.net,0),discount=subtotal*Math.max(0,Math.min(100,disc))/100,ratio=subtotal?discount/subtotal:0,tax=rows.reduce((a:number,z:any)=>a+(z.rate>0?z.net*(1-ratio)*z.rate/100:0),0),base=Math.max(0,subtotal-discount+tax),adj=pay?base*Number(pay.adjustment_percent||0)/100*(pay.adjustment_type==='discount'?-1:1):0,total=Math.max(0,base+adj);
 function add(p:any){K(a=>{const i=a.findIndex((z:any)=>z.id===p.id);return i<0?[...a,{...p,quantity:1,notes:''}]:a.map((z:any,n:number)=>n===i?{...z,quantity:z.quantity+1}:z)})}
 async function api(kind:string,data:any){const r=await fetch('/api/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,data})}),j=await r.json();if(!r.ok){alert(j.error||'Action failed');return null}return j}
 async function extra(kind:string,data:any){const r=await fetch('/api/cashier-extras',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,data})}),j=await r.json();if(!r.ok){alert(j.error||'Action failed');return null}return j}
 async function checkout(){if(!cart.length)return;if(!wh)return alert('Select a warehouse first');if(!shift)return alert('Open a cashier shift before payment');const method=pay||x.payment_methods[0]||{code:'cash',name:'Cash',adjustment_percent:0,adjustment_type:'markup'};const j=await api('checkout',{shift_id:shift.id,warehouse_id:wh,service_type:mode==='hospitality'?service:'retail',discount,discount_percent:disc,customer,held_order_id:heldId,lines:cart.map((z:any)=>({product_id:z.id,quantity:z.quantity,discount:0,notes:z.notes||''})),payments:[{payment_method:method.code||method.name,base_amount:base,adjustment_percent:Number(method.adjustment_percent||0),adjustment_type:method.adjustment_type||'markup',amount:total}]});if(j){await extra('attach_order',{order_id:j.result.order_id,table_id:table?.id||null,table_name:table?.name||null});K([]);D(0);U({name:'',phone:'',email:'',notes:''});H(null);T(null);P(null);load()}}
 async function hold(){if(!cart.length||!wh)return;const j=await api('hold',{shift_id:shift?.id||null,warehouse_id:wh,service_type:mode==='hospitality'?service:'retail',discount,discount_percent:disc,customer,lines:cart.map((z:any)=>({product_id:z.id,quantity:z.quantity,discount:0,notes:z.notes||''}))});if(j){K([]);D(0);H(null);load()}}
 async function openShift(){if(!wh)return alert('Create/select a warehouse');await api('open_shift',{warehouse_id:wh,opening_cash:0});load()}
 async function addPayment(){if(!String(payForm.name||'').trim())return alert('Payment method name is required');const r=await fetch('/api/commerce-admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'payment_method',data:payForm})});if(!r.ok)return alert((await r.json()).error);setPayForm({name:'',adjustment_percent:0,adjustment_type:'markup'});load()}
 async function addTable(){if(!String(tableForm.name||'').trim())return alert('Table name is required');const r=await fetch('/api/commerce-admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'dining_table',data:tableForm})});if(!r.ok)return alert((await r.json()).error);setTableForm({name:'',area:'Main',seats:2});load()}
 function recall(o:any){const lines=(o.sales_order_lines||[]).map((l:any)=>{const p=d.products.find((z:any)=>z.id===l.product_id);return p?{...p,quantity:Number(l.quantity),notes:l.notes||''}:null}).filter(Boolean);K(lines);D(Number(o.discount_percent||0));U({name:o.customer_name||'',phone:o.customer_phone||'',email:o.customer_email||'',notes:o.customer_notes||''});H(o.id);V(o.service_type||'dine_in');Z('')}

 return <div className="space-y-4">
  <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">Cashier</h1><p className="text-sm text-slate-400">Cashier: <b className="text-cyan-300">{x.cashier_name}</b> · Shift {shift?'OPEN':'CLOSED'}</p></div><div className="flex gap-2"><button className={mode==='hospitality'?btn:ghost} onClick={()=>M('hospitality')}>Hospitality Cashier</button><button className={mode==='retail'?btn:ghost} onClick={()=>M('retail')}>Retail Cashier</button></div></header>
  <div className="flex flex-wrap gap-2">{!shift&&<button className={btn} onClick={openShift}>Open Shift</button>}<button className={ghost} onClick={()=>Z('track')}>Track Invoice</button>{mode==='hospitality'&&<button className={ghost} onClick={()=>Z('tables')}>Dining Map</button>}<button className={ghost} onClick={()=>Z('payments')}>Payment Methods</button><button className={ghost} onClick={()=>Z('holds')}>Held Orders ({held.length})</button></div>
  <div className="grid gap-4 xl:grid-cols-[1fr_420px]"><main className={`${panel} p-4`}><div className="mb-3 flex gap-2"><input className={`${inp} flex-1`} value={q} onChange={e=>Q(e.target.value)} placeholder={mode==='retail'?'Search / Barcode / SKU':'Search menu item...'}/>{mode==='hospitality'&&['dine_in','takeaway','delivery'].map(s=><button key={s} className={service===s?btn:ghost} onClick={()=>V(s)}>{s==='dine_in'?'Dine In':s==='takeaway'?'Takeaway':'Delivery'}</button>)}</div><div className="mb-4 flex flex-wrap gap-2"><button className={cat==='all'?btn:ghost} onClick={()=>C('all')}>All</button><button className={cat==='best'?btn:ghost} onClick={()=>C('best')}>Best Sellers</button>{d.categories.map((c:any)=><button key={c.id} className={cat===c.id?btn:ghost} onClick={()=>C(c.id)}>{c.name}</button>)}</div>{mode==='hospitality'?<div className="grid grid-cols-2 gap-3 md:grid-cols-3 2xl:grid-cols-4">{products.map((p:any)=><button key={p.id} onClick={()=>add(p)} className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-950 text-left"><div className="aspect-[16/10] bg-slate-800">{p.image_url?<img src={p.image_url} alt="" className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-slate-600">No image</div>}</div><div className="p-3"><b>{p.name}</b><small className="block text-slate-500">{p.sale_unit||'piece'}</small><div className="text-cyan-300">{Number(p.price).toFixed(2)} {currency}</div></div></button>)}</div>:<div className="space-y-1">{products.map((p:any)=><button key={p.id} onClick={()=>add(p)} className="grid w-full grid-cols-[1fr_160px_120px] border-b border-slate-800 p-3 text-left"><span><b>{p.name}</b><small className="block text-slate-500">{p.sale_unit||'piece'}</small></span><span>{p.barcode||p.sku}</span><span>{Number(p.price).toFixed(2)} {currency}</span></button>)}</div>}</main>
   <aside className={`${panel} flex flex-col`}><div className="border-b border-slate-800 p-5"><div className="flex justify-between"><h2 className="text-xl font-black">Current Order</h2><button className="text-rose-400" onClick={()=>K([])}>Clear</button></div>{table&&<small className="text-cyan-300">Table: {table.name}</small>}{heldId&&<small className="ml-2 text-amber-300">Recalled held order</small>}</div><div className="flex-1 p-4">{!cart.length&&<div className="py-16 text-center text-slate-600">No items yet</div>}{cart.map((z:any)=><div key={z.id} className="mb-2 rounded-xl border border-slate-800 p-3"><div className="flex justify-between"><b>{z.name}</b><span>{(z.price*z.quantity).toFixed(2)}</span></div><div className="mt-2 flex items-center gap-2"><button className="h-8 w-8 rounded bg-slate-800" onClick={()=>K(a=>a.map((v:any)=>v.id===z.id?{...v,quantity:Math.max(1,v.quantity-1)}:v))}>−</button><b>{z.quantity}</b><button className="h-8 w-8 rounded bg-slate-800" onClick={()=>K(a=>a.map((v:any)=>v.id===z.id?{...v,quantity:v.quantity+1}:v))}>+</button><button className="ml-auto text-xs text-rose-400" onClick={()=>K(a=>a.filter((v:any)=>v.id!==z.id))}>Remove</button></div><input className={`${inp} mt-2`} placeholder="Item comment (optional)" value={z.notes||''} onChange={e=>K(a=>a.map((v:any)=>v.id===z.id?{...v,notes:e.target.value}:v))}/></div>)}</div>
   <div className="border-t border-slate-800 p-5"><div className="text-sm"><div className="flex justify-between"><span>Subtotal</span><b>{subtotal.toFixed(2)}</b></div>{disc>0&&<div className="flex justify-between text-emerald-300"><span>Discount {disc}%</span><b>-{discount.toFixed(2)}</b></div>}<div className="flex justify-between"><span>Tax</span><b>{tax.toFixed(2)}</b></div>{adj!==0&&<div className="flex justify-between text-amber-300"><span>{pay?.name} adjustment</span><b>{adj>0?'+':''}{adj.toFixed(2)}</b></div>}<div className="mt-2 flex justify-between text-2xl font-black"><span>Total</span><span>{total.toFixed(2)} {currency}</span></div></div><div className="mt-3 grid grid-cols-2 gap-2"><select className={inp} value={pay?.id||''} onChange={e=>P(x.payment_methods.find((m:any)=>m.id===e.target.value)||null)}><option value="">Payment Method</option>{x.payment_methods.map((m:any)=><option key={m.id} value={m.id}>{m.name}{m.adjustment_percent?` (${m.adjustment_type==='discount'?'-':'+'}${m.adjustment_percent}%)`:''}</option>)}</select><button className={btn} disabled={!cart.length||!shift} onClick={checkout}>Pay</button></div>{!shift&&cart.length>0&&<div className="mt-2 text-center text-xs text-amber-300">Open a shift before taking payment.</div>}<div className="mt-2 grid grid-cols-3 gap-2"><button className={ghost} disabled={!cart.length} onClick={hold}>Hold</button><button className={ghost} onClick={()=>{setCustomDisc(String(disc||''));Z('discount')}}>Discount</button><button className={ghost} onClick={()=>Z('customer')}>Customer</button></div></div></aside></div>

  {modal==='discount'&&<Modal t="Apply Discount" x={()=>Z('')}><p className="mb-4 text-sm text-slate-400">Choose a preset or enter a custom percentage. The invoice recalculates immediately.</p><div className="grid grid-cols-3 gap-2">{[5,10,15,20,30].map(n=><button key={n} className={disc===n?btn:ghost} onClick={()=>{D(n);Z('')}}>{n}%</button>)}<button className={ghost} onClick={()=>{D(0);Z('')}}>No Discount</button></div><div className="mt-4 rounded-2xl border border-slate-800 p-4"><label className="text-xs font-black uppercase text-slate-400">Custom Discount %</label><div className="mt-2 flex gap-2"><input className={inp} type="number" min="0" max="100" step="0.01" placeholder="Example: 12.5" value={customDisc} onChange={e=>setCustomDisc(e.target.value)}/><button className={btn} onClick={()=>{const n=Math.max(0,Math.min(100,Number(customDisc||0)));D(n);Z('')}}>Apply</button></div><div className="mt-3 grid grid-cols-3 gap-2 text-sm"><div><small className="text-slate-500">Before</small><b className="block">{(subtotal+tax).toFixed(2)}</b></div><div><small className="text-slate-500">Discount</small><b className="block text-emerald-300">-{(subtotal*Math.max(0,Math.min(100,Number(customDisc||0)))/100).toFixed(2)}</b></div><div><small className="text-slate-500">Calculated</small><b className="block text-cyan-300">{Math.max(0,subtotal-(subtotal*Math.max(0,Math.min(100,Number(customDisc||0)))/100)+tax).toFixed(2)}</b></div></div></div></Modal>}
  {modal==='customer'&&<Modal t="Customer Details" x={()=>Z('')}><div className="space-y-3"><Field l="Customer Name"><input className={inp} placeholder="Customer name" value={customer.name} onChange={e=>U({...customer,name:e.target.value})}/></Field><Field l="Phone"><input className={inp} placeholder="05xxxxxxxx" value={customer.phone} onChange={e=>U({...customer,phone:e.target.value})}/></Field><Field l="Email"><input className={inp} placeholder="Optional" value={customer.email} onChange={e=>U({...customer,email:e.target.value})}/></Field><Field l="Notes"><textarea className={inp} placeholder="Optional customer notes" value={customer.notes} onChange={e=>U({...customer,notes:e.target.value})}/></Field><button className={`${btn} w-full`} onClick={()=>Z('')}>Save Customer</button></div></Modal>}
  {modal==='payments'&&<Modal t="Payment Methods" x={()=>Z('')}><div className="grid gap-2 md:grid-cols-3"><input className={inp} placeholder="Method name" value={payForm.name} onChange={e=>setPayForm({...payForm,name:e.target.value})}/><select className={inp} value={payForm.adjustment_type} onChange={e=>setPayForm({...payForm,adjustment_type:e.target.value})}><option value="markup">Markup %</option><option value="discount">Discount %</option></select><input className={inp} type="number" min="0" max="100" placeholder="Automatic %" value={payForm.adjustment_percent} onChange={e=>setPayForm({...payForm,adjustment_percent:Number(e.target.value)})}/></div><button className={`${btn} mt-3`} onClick={addPayment}>+ Add Payment Method</button><div className="mt-3">{x.payment_methods.map((m:any)=><div key={m.id} className="border-b border-slate-800 py-3"><b>{m.name}</b><small className="ml-3 text-slate-400">{m.adjustment_percent?`${m.adjustment_type} ${m.adjustment_percent}%`:'No adjustment'}</small></div>)}</div></Modal>}
  {modal==='tables'&&<Modal t="Dining Map" x={()=>Z('')}><div className="grid gap-2 md:grid-cols-3"><input className={inp} placeholder="Table name" value={tableForm.name} onChange={e=>setTableForm({...tableForm,name:e.target.value})}/><input className={inp} placeholder="Area" value={tableForm.area} onChange={e=>setTableForm({...tableForm,area:e.target.value})}/><input className={inp} type="number" min="1" placeholder="Seats" value={tableForm.seats} onChange={e=>setTableForm({...tableForm,seats:Number(e.target.value)})}/></div><button className={`${btn} mt-3`} onClick={addTable}>+ Add Table</button><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-3">{x.tables.map((t:any)=><div key={t.id} className={`rounded-2xl border p-4 ${table?.id===t.id?'border-cyan-400':'border-slate-700'} ${t.status==='closed'?'opacity-50':''}`}><b>{t.name}</b><small className="block text-slate-500">{t.area||'Main'} · {t.seats} seats · {t.status}</small><div className="mt-2 flex gap-1">{t.status!=='closed'&&<button className="text-cyan-300" onClick={()=>{T(t);Z('')}}>Select</button>}<button className="ml-auto text-xs" onClick={async()=>{await extra('table_status',{table_id:t.id,status:t.status==='closed'?'open':'closed'});load()}}>{t.status==='closed'?'Open':'Close'}</button></div></div>)}</div></Modal>}
  {modal==='track'&&<Modal t="Invoice Tracking" x={()=>Z('')}><div className="space-y-2">{d.orders.filter((o:any)=>o.status==='completed').slice(0,50).map((o:any)=><div key={o.id} className="grid grid-cols-[1fr_140px] items-center border-b border-slate-800 py-3"><span><b>{o.order_no}</b><small className="block text-slate-500">{o.cashier_name||x.cashier_name} · {Number(o.total).toFixed(2)} {currency}</small></span><select className={inp} value={o.tracking_status||'new'} onChange={async e=>{await extra('tracking',{order_id:o.id,status:e.target.value});load()}}><option value="new">New</option><option value="preparing">Preparing</option><option value="ready">Ready</option><option value="delivered">Delivered</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div>)}</div></Modal>}
  {modal==='holds'&&<Modal t="Held Orders" x={()=>Z('')}><div>{held.length===0?<p className="text-slate-500">No held orders.</p>:held.map((o:any)=><div key={o.id} className="flex items-center justify-between border-b border-slate-800 py-3"><span><b>{o.order_no}</b><small className="block text-slate-500">{o.customer_name||o.customer_phone||'Walk-in'} · {Number(o.total).toFixed(2)} {currency}</small></span><button className={btn} onClick={()=>recall(o)}>Recall</button></div>)}</div></Modal>}
 </div>
}
function Modal({t,x,children}:any){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-3xl border border-slate-700 bg-slate-900 p-6"><div className="mb-4 flex justify-between"><h2 className="text-xl font-black">{t}</h2><button onClick={x}>✕</button></div>{children}</div></div>}
function Field({l,children}:any){return <label className="block"><span className="mb-1 block text-xs font-black uppercase text-slate-400">{l}</span>{children}</label>}
