"use client";
import {useEffect,useState} from "react";
import Sidebar from "./Sidebar";import DashboardHeader from "./DashboardHeader";
import {ArrowRight,CheckCircle2,FileText,Megaphone,Palette,Send,Sparkles} from "lucide-react";
type Item={id:string;campaign_name?:string|null;caption?:string|null;status?:string|null;platforms?:string[]|null;media_url?:string|null;external_post_id?:string|null;error_message?:string|null;created_at?:string|null};type Run={id:string;status?:string|null;action?:string|null;input?:Record<string,unknown>|null;output?:Record<string,unknown>|null;created_at?:string|null};
export default function FoxyMarketingLive(){const[items,setItems]=useState<Item[]>([]),[runs,setRuns]=useState<Run[]>([]),[task,setTask]=useState("Create today's AVERO OS post for Facebook and Instagram"),[busy,setBusy]=useState(false),[note,setNote]=useState("");
async function load(){try{const[q,r]=await Promise.all([fetch("/api/marketing/content",{cache:"no-store"}),fetch("/api/ai-departments/marketing",{cache:"no-store"})]);if(q.ok)setItems((await q.json()).items||[]);if(r.ok)setRuns((await r.json()).runs||[])}catch{}}
useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);const latest=items[0],run=runs[0];const status=String(latest?.status||run?.status||"ready").toLowerCase();const stage=status==="published"?6:status==="publishing"?5:["approved","scheduled"].includes(status)?5:["approval_required","draft"].includes(status)?4:run?3:1;
async function create(){if(!task.trim()||busy)return;setBusy(true);setNote("");try{const r=await fetch("/api/ai-departments/marketing/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task,channel:"dashboard",content_type:"post",platforms:["facebook","instagram"],worker_key:"content_planner"})});const j=await r.json();setNote(r.ok?"Foxy created a real draft in AVERO.":j.error||"Could not create content");await load()}finally{setBusy(false)}}
async function publish(){if(!latest||busy)return;setBusy(true);setNote("");try{const r=await fetch(`/api/marketing/content/${latest.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"approve_publish",platforms:latest.platforms?.length?latest.platforms:["facebook","instagram"]})});const j=await r.json();setNote(j.message||j.error||"Publishing updated");await load()}finally{setBusy(false)}}
const steps=[{t:"1. Brief",d:String(run?.input?.task||task),i:<FileText/>},{t:"2. Brand brain",d:"Company profile, audience and brand rules loaded",i:<Sparkles/>},{t:"3. Content",d:latest?.caption||"Waiting for Foxy to create the draft",i:<Megaphone/>},{t:"4. Creative",d:latest?.media_url?"Real media is ready":"Creative is prepared when publishing needs media",i:<Palette/>},{t:"5. Approval",d:latest?.status||"Waiting",i:<CheckCircle2/>},{t:"6. Publish",d:latest?.external_post_id||latest?.error_message||"Ready after approval",i:<Send/>}];
return <div className="min-h-screen bg-slate-950 text-white"><Sidebar/><div className="ml-64 min-h-screen"><DashboardHeader/><main className="p-4 md:p-7"><div className="mx-auto max-w-6xl space-y-6"><section className="rounded-3xl border border-violet-400/20 bg-[radial-gradient(circle_at_top_left,rgba(168,85,247,.15),transparent_35%),#020617] p-6 md:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.3em] text-violet-300">Foxy · PR & Marketing</p><h1 className="mt-3 text-3xl font-black md:text-4xl">One brief. Real content. Real approval. Real publishing.</h1><p className="mt-3 text-sm text-slate-300">Vercel Native · no Make runtime.</p></div><div className="text-5xl">🦊</div></div></section>
<section className="rounded-3xl border border-slate-800 bg-slate-900/60 p-5"><div className="flex flex-col gap-3 md:flex-row"><input value={task} onChange={e=>setTask(e.target.value)} onKeyDown={e=>e.key==="Enter"&&create()} className="min-w-0 flex-1 rounded-2xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm outline-none focus:border-violet-400" placeholder="Tell Foxy what to create…"/><button onClick={create} disabled={busy} className="rounded-2xl bg-violet-500 px-5 py-3 text-sm font-black disabled:opacity-50">{busy?"Working…":"Create with Foxy"}</button></div>{note&&<p className="mt-3 text-sm text-violet-200">{note}</p>}</section>
<section className="grid gap-3 md:grid-cols-3">{steps.map((s,n)=><div key={s.t} className={`rounded-3xl border p-5 transition ${n+1<=stage?"border-violet-400/35 bg-violet-400/10":"border-slate-800 bg-slate-900/45"}`}><div className={`${n+1===stage?"animate-pulse":""} text-violet-300`}>{s.i}</div><h3 className="mt-4 font-black">{s.t}</h3><p className="mt-2 line-clamp-4 text-sm leading-6 text-slate-400">{s.d}</p></div>)}</section>
{latest&&<section className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl border border-slate-800 bg-slate-900/60 p-5"><p className="text-xs font-black uppercase tracking-[.2em] text-violet-300">Latest real content</p><h2 className="mt-2 text-xl font-black">{latest.campaign_name||"Marketing draft"}</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-slate-300">{latest.caption||"No caption yet"}</p></div><div className="rounded-3xl border border-slate-800 bg-slate-900/60 p-5"><p className="text-xs text-slate-500">Current status</p><p className="mt-2 text-2xl font-black text-white">{latest.status||"draft"}</p><p className="mt-4 text-xs leading-5 text-slate-500">{latest.error_message||latest.external_post_id||"AVERO will record the real platform result here."}</p>{!["published","publishing"].includes(status)&&<button onClick={publish} disabled={busy} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-cyan-500 px-4 py-3 text-sm font-black text-slate-950 disabled:opacity-50">Approve & Publish <ArrowRight size={16}/></button>}</div></section>}
</div></main></div></div>}
