"use client";
import { useCallback,useEffect,useState } from "react";
import Link from "next/link";
import { useLanguage } from "./LanguageProvider";

type Store={slug:string;pickup_branch_id:string|null;pickup_address:string;prep_minutes:number;enabled:boolean;logo_url?:string|null;hero_image_url?:string|null;primary_color?:string;accent_color?:string;contact_phone?:string|null;contact_email?:string|null;whatsapp_url?:string|null;map_url?:string|null;help_url?:string|null;announcement_text?:string|null;popup_enabled?:boolean;popup_image_url?:string|null;popup_title?:string|null;popup_body?:string|null;popup_link?:string|null;about_title?:string|null;about_body?:string|null;about_image_url?:string|null;locations_json?:any[];gallery_json?:any[];custom_links_json?:any[]};
type Product={id:string;sku?:string;barcode?:string|null;name:string;description?:string|null;price:number;active:boolean;show_on_go:boolean;category_id:string|null;calories?:number|null;allergens?:string[]};
type Data={company:{name:string};store:Store|null;branches:{id:string;name:string}[];products:Product[];orders:any[];can_manage:boolean;selected_company_id:string;available_companies:{id:string;name:string}[]};
const input="w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-white outline-none focus:border-cyan-400";
const button="rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950 disabled:opacity-50";
export default function GoMerchantWorkspace(){
 const {language}=useLanguage(),ar=language==="ar",L=(en:string,aa:string)=>ar?aa:en;
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[companyId,setCompanyId]=useState(""),[menuSearch,setMenuSearch]=useState("");
 const [branchName,setBranchName]=useState(""),[address,setAddress]=useState(""),[branchId,setBranchId]=useState(""),[minutes,setMinutes]=useState(30);
 const [appearance,setAppearance]=useState<any>({});
 const load=useCallback(async()=>{const r=await fetch(`/api/go/manage${companyId?`?company=${encodeURIComponent(companyId)}`:""}`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||L("Could not load GO","تعذّر تحميل GO"));setData(j);setAddress(j.store?.pickup_address||"");setBranchId(j.store?.pickup_branch_id||j.branches?.[0]?.id||"");setMinutes(j.store?.prep_minutes||30);setAppearance({logo_url:j.store?.logo_url||"",hero_image_url:j.store?.hero_image_url||"",primary_color:j.store?.primary_color||"#06b6d4",accent_color:j.store?.accent_color||"#f59e0b",contact_phone:j.store?.contact_phone||"",contact_email:j.store?.contact_email||"",whatsapp_url:j.store?.whatsapp_url||"",map_url:j.store?.map_url||"",help_url:j.store?.help_url||"",announcement_text:j.store?.announcement_text||"",popup_enabled:!!j.store?.popup_enabled,popup_image_url:j.store?.popup_image_url||"",popup_title:j.store?.popup_title||"",popup_body:j.store?.popup_body||"",popup_link:j.store?.popup_link||"",about_title:j.store?.about_title||"",about_body:j.store?.about_body||"",about_image_url:j.store?.about_image_url||"",locations_json:j.store?.locations_json||[],gallery_json:j.store?.gallery_json||[],custom_links_json:j.store?.custom_links_json||[]})},[companyId,language]);
 useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
 async function change(payload:Record<string,unknown>){setBusy(true);setError("");try{const r=await fetch(`/api/go/manage${companyId?`?company=${encodeURIComponent(companyId)}`:""}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok)throw new Error(j.error||L("Could not save","تعذّر الحفظ"));await load();setBranchName("")}catch(e){setError(e instanceof Error?e.message:L("Could not save","تعذّر الحفظ"))}finally{setBusy(false)}}
 if(!data)return <div className="mt-8 rounded-2xl border border-slate-800 p-6 text-slate-300">{error||L("Loading GO settings…","جارٍ تحميل إعدادات GO…")}</div>;
 const published=data.products.filter(p=>p.active&&p.show_on_go).length;
 return <div className="mt-8 space-y-7">
 {error&&<p className="rounded-xl border border-rose-600/50 bg-rose-500/10 p-4 text-rose-200">{error}</p>}
 {data.available_companies.length>0&&<label className="block max-w-lg text-sm text-slate-300">{L("Menu company (King)","شركة المنيو (King)")}<select className={input+" mt-2"} value={data.selected_company_id} onChange={e=>{setCompanyId(e.target.value);setData(null)}}><option value={data.selected_company_id}>{data.company.name}</option>{data.available_companies.filter(c=>c.id!==data.selected_company_id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}
 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-bold">{L("Store setup","إعداد المتجر")}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">
 {data.branches.length===0?<><label>{L("Branch name","اسم الفرع")}<input className={input+" mt-2"} value={branchName} onChange={e=>setBranchName(e.target.value)}/></label></>:<label>{L("Pickup branch","فرع الاستلام")}<select className={input+" mt-2"} value={branchId} onChange={e=>setBranchId(e.target.value)}>{data.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>}
 <label>{L("Pickup address","عنوان الاستلام")}<input className={input+" mt-2"} value={address} onChange={e=>setAddress(e.target.value)}/></label>
 <label>{L("Preparation minutes","دقائق التحضير")}<input type="number" min="5" max="240" className={input+" mt-2"} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label></div>
 {data.branches.length===0?<button className={button+" mt-4"} disabled={busy||branchName.trim().length<2||address.trim().length<8} onClick={()=>change({kind:"branch",name:branchName,address})}>{L("Add branch","إضافة الفرع")}</button>:<button className={button+" mt-4"} disabled={busy||!branchId||address.trim().length<8||!published} onClick={()=>change({kind:"store",branch_id:branchId,address,prep_minutes:minutes,enabled:!data.store?.enabled})}>{data.store?.enabled?L("Stop orders","إيقاف الطلبات"):L("Save and open orders","حفظ وفتح الطلبات")}</button>}
 {data.store?.slug&&<Link href={`/go/${data.store.slug}`} target="_blank" className="ml-3 mt-4 inline-block rounded-xl border border-cyan-400 px-4 py-3 text-cyan-300">{L("Open QR website ↗","فتح موقع QR ↗")}</Link>}</section>

 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-bold">{L("Website appearance","شكل موقع الطلبات")}</h2><p className="mt-1 text-sm text-slate-400">{L("Make the QR site look like the merchant's own website.","خلّي موقع QR يظهر كأنه موقع خاص بالمتجر.")}</p>
 <div className="mt-5 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="grid gap-3 sm:grid-cols-2">
 {([["logo_url","Logo URL","رابط الشعار"],["hero_image_url","Cover image URL","رابط صورة الغلاف"],["contact_phone","Contact phone","هاتف التواصل"],["contact_email","Contact email","بريد التواصل"],["whatsapp_url","WhatsApp link","رابط واتساب"],["map_url","Map link","رابط الموقع"],["help_url","Help center link","رابط مركز المساعدة"]] as const).map(([k,en,aa])=><label key={k} className="text-sm text-slate-300">{L(en,aa)}<input className={input+" mt-2"} value={appearance[k]||""} onChange={e=>setAppearance({...appearance,[k]:e.target.value})}/></label>)}
 <label className="text-sm text-slate-300">{L("Primary color","اللون الأساسي")}<div className="mt-2 flex gap-2"><input type="color" value={appearance.primary_color||"#06b6d4"} onChange={e=>setAppearance({...appearance,primary_color:e.target.value})}/><input className={input} value={appearance.primary_color||""} onChange={e=>setAppearance({...appearance,primary_color:e.target.value})}/></div></label>
 <label className="text-sm text-slate-300">{L("Accent color","لون الأزرار")}<div className="mt-2 flex gap-2"><input type="color" value={appearance.accent_color||"#f59e0b"} onChange={e=>setAppearance({...appearance,accent_color:e.target.value})}/><input className={input} value={appearance.accent_color||""} onChange={e=>setAppearance({...appearance,accent_color:e.target.value})}/></div></label>
 <div className="sm:col-span-2 grid gap-3 sm:grid-cols-2"><ImageUpload label={L("Upload logo","رفع الشعار")} onUploaded={url=>setAppearance({...appearance,logo_url:url})}/><ImageUpload label={L("Upload cover / banner","رفع الغلاف / البانر")} onUploaded={url=>setAppearance({...appearance,hero_image_url:url})}/><ImageUpload label={L("Upload promotion popup","رفع صورة البوب أب")} onUploaded={url=>setAppearance({...appearance,popup_image_url:url})}/><ImageUpload label={L("Upload About us image","رفع صورة من نحن")} onUploaded={url=>setAppearance({...appearance,about_image_url:url})}/></div>
 <label className="sm:col-span-2 text-sm text-slate-300">{L("Announcement bar","الشريط الإعلاني المتحرك")}<input className={input+" mt-2"} value={appearance.announcement_text||""} onChange={e=>setAppearance({...appearance,announcement_text:e.target.value})}/></label>
 <label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={!!appearance.popup_enabled} onChange={e=>setAppearance({...appearance,popup_enabled:e.target.checked})}/>{L("Show promotion popup","إظهار البوب أب الإعلاني")}</label>
 <input className={input} placeholder={L("Popup title","عنوان البوب أب")} value={appearance.popup_title||""} onChange={e=>setAppearance({...appearance,popup_title:e.target.value})}/><textarea className={input+" sm:col-span-2"} placeholder={L("Popup description","وصف العرض")} value={appearance.popup_body||""} onChange={e=>setAppearance({...appearance,popup_body:e.target.value})}/><input className={input+" sm:col-span-2"} placeholder={L("Popup button link","رابط زر العرض")} value={appearance.popup_link||""} onChange={e=>setAppearance({...appearance,popup_link:e.target.value})}/>
 <input className={input} placeholder={L("About us title","عنوان من نحن")} value={appearance.about_title||""} onChange={e=>setAppearance({...appearance,about_title:e.target.value})}/><textarea className={input+" sm:col-span-2 min-h-28"} placeholder={L("About us content","محتوى من نحن")} value={appearance.about_body||""} onChange={e=>setAppearance({...appearance,about_body:e.target.value})}/>
 <button className={button} disabled={busy||!data.can_manage} onClick={()=>change({kind:"appearance",...appearance})}>{L("Save website design","حفظ تصميم الموقع")}</button></div>
 <div className="overflow-hidden rounded-3xl border border-slate-700 bg-slate-950"><div className="h-28 bg-cover bg-center" style={{backgroundColor:appearance.primary_color,backgroundImage:appearance.hero_image_url?`url("${appearance.hero_image_url}")`:undefined}}/><div className="p-5"><div className="flex items-center gap-3">{appearance.logo_url&&<img src={appearance.logo_url} alt="" className="h-12 w-12 rounded-xl object-cover"/>}<strong>{data.company.name}</strong></div><p className="mt-3 text-sm text-slate-400">{L("Live preview of the QR ordering page","معاينة مباشرة لصفحة طلب QR")}</p><button className="mt-4 w-full rounded-xl p-3 font-bold text-slate-950" style={{backgroundColor:appearance.accent_color}}>{L("Order now","اطلب الآن")}</button></div></div></div></section>

 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><div className="flex justify-between gap-4"><h2 className="text-xl font-bold">{L("Menu items","أصناف المنيو")}</h2>{data.available_companies.length===0&&<Link href="/pos?area=add-items" className="text-cyan-300">{L("Add items ↗","إضافة أصناف ↗")}</Link>}</div>
 <input className={input+" mt-4"} placeholder={L("Search by item name, SKU or barcode","بحث باسم الصنف أو الكود أو الباركود")} value={menuSearch} onChange={e=>setMenuSearch(e.target.value)}/><div className="mt-4 max-h-[560px] space-y-4 overflow-y-auto pr-2">{data.products.filter(p=>[p.name,p.sku,p.barcode].some(v=>String(v||"").toLowerCase().includes(menuSearch.toLowerCase()))).map(p=><ProductEditor key={p.id} p={p} busy={busy} canManage={data.can_manage} L={L} change={change}/>)}</div></section>

 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-bold">{L("Recent pickup orders","طلبات الاستلام الأخيرة")}</h2><div className="mt-4 space-y-3">{data.orders.length===0&&<p className="text-slate-400">{L("No orders yet.","لا توجد طلبات بعد.")}</p>}{data.orders.map(o=><div key={o.id} className="rounded-xl border border-slate-700 p-4"><div className="flex justify-between"><strong>{o.order_no} · {o.customer_name}</strong><span>{Number(o.total).toFixed(2)} SAR</span></div><p className="mt-2 text-sm text-slate-400">{o.customer_phone}</p></div>)}</div></section>
 </div>;
}
function ProductEditor({p,busy,canManage,L,change}:{p:Product;busy:boolean;canManage:boolean;L:(a:string,b:string)=>string;change:(x:Record<string,unknown>)=>Promise<void>}){
 const [description,setDescription]=useState(p.description||""),[calories,setCalories]=useState(p.calories?.toString()||""),[allergens,setAllergens]=useState((p.allergens||[]).join(", "));
 useEffect(()=>{setDescription(p.description||"");setCalories(p.calories?.toString()||"");setAllergens((p.allergens||[]).join(", "))},[p.description,p.calories,p.allergens]);
 return <div className="rounded-xl border border-slate-800 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><strong>{p.name}</strong><p className="text-sm text-slate-400">{Number(p.price).toFixed(2)} SAR</p></div><button disabled={busy||!canManage||!p.active} onClick={()=>change({kind:"product",id:p.id,published:!p.show_on_go})} className="rounded-xl border border-cyan-500/40 px-3 py-2 text-sm text-cyan-300">{p.show_on_go?L("Published","منشور"):L("Publish","نشر")}</button></div><div className="mt-3 grid gap-3 md:grid-cols-3"><input className={input} placeholder={L("Description","الوصف")} value={description} onChange={e=>setDescription(e.target.value)}/><input className={input} type="number" min="0" placeholder={L("Calories","السعرات")} value={calories} onChange={e=>setCalories(e.target.value)}/><input className={input} placeholder={L("Allergens, comma separated","مسببات الحساسية، مفصولة بفاصلة")} value={allergens} onChange={e=>setAllergens(e.target.value)}/></div><button className="mt-3 rounded-lg border border-slate-600 px-3 py-2 text-xs" disabled={busy||!canManage} onClick={()=>change({kind:"product_details",id:p.id,description,calories,allergens:allergens.split(",")})}>{L("Save item details","حفظ تفاصيل الصنف")}</button></div>
}
function ImageUpload({label,onUploaded}:{label:string;onUploaded:(url:string)=>void}){const[busy,setBusy]=useState(false);async function upload(file?:File){if(!file)return;setBusy(true);try{const fd=new FormData();fd.append("file",file);const r=await fetch("/api/go/upload",{method:"POST",body:fd}),j=await r.json();if(!r.ok)throw new Error(j.error||"Upload failed");onUploaded(j.url)}finally{setBusy(false)}}return <label className="cursor-pointer rounded-xl border border-dashed border-slate-600 p-4 text-center text-sm text-slate-300 hover:border-cyan-400">{busy?"Uploading…":label}<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" className="hidden" disabled={busy} onChange={e=>upload(e.target.files?.[0])}/></label>}