"use client";
import {useEffect,useState} from "react";
import {useLanguage} from "./LanguageProvider";
const field="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white";
const fonts=["Inter","Geist","Arial","Georgia","Times New Roman"];
export default function GoWebsiteBuilder(){
 const{language}=useLanguage(),ar=language==="ar",L=(e:string,a:string)=>ar?a:e;const[data,setData]=useState<any>(null),[site,setSite]=useState<any>({}),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/go/manage",{cache:"no-store"}),j=await r.json();if(r.ok){setData(j);setSite({...(j.store||{}),font_family:j.store?.font_family||"Geist"})}}useEffect(()=>{load()},[]);
 async function save(){setBusy(true);await fetch("/api/go/manage",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"appearance",...site})});setBusy(false);await load()}
 async function upload(file:File|undefined,key:string){if(!file)return;const fd=new FormData();fd.append("file",file);const r=await fetch("/api/go/upload",{method:"POST",body:fd}),j=await r.json();if(r.ok)setSite((s:any)=>({...s,[key]:j.url}))}
 if(!data)return <div className="p-8 text-slate-400">{L("Loading website…","جارٍ تحميل الموقع…")}</div>;
 const slug=data.store?.slug;
 return <div className="grid min-h-[calc(100vh-88px)] grid-cols-1 bg-slate-950 xl:grid-cols-[350px_1fr]">
 <aside className="max-h-[calc(100vh-88px)] overflow-y-auto border-r border-slate-800 p-5"><h1 className="text-2xl font-bold">{L("Website Builder","مصمم الموقع")}</h1><p className="mt-1 text-sm text-slate-400">{L("Design your customer-facing website visually.","صمّم موقعك الذي يراه العملاء بشكل مرئي.")}</p>
 <Panel title={L("Brand","الهوية")}><Upload label={L("Logo","الشعار")} onFile={f=>upload(f,"logo_url")}/><Upload label={L("Cover / banner","الغلاف / البانر")} onFile={f=>upload(f,"hero_image_url")}/><label>{L("Primary color","اللون الأساسي")}<input type="color" className="ml-3" value={site.primary_color||"#06b6d4"} onChange={e=>setSite({...site,primary_color:e.target.value})}/></label><label>{L("Button color","لون الأزرار")}<input type="color" className="ml-3" value={site.accent_color||"#f59e0b"} onChange={e=>setSite({...site,accent_color:e.target.value})}/></label><label>{L("Font","الخط")}<select className={field+" mt-1"} value={site.font_family||"Geist"} onChange={e=>setSite({...site,font_family:e.target.value})}>{fonts.map(x=><option key={x}>{x}</option>)}</select></label></Panel>
 <Panel title={L("Header & announcement","الهيدر والإعلان")}><input className={field} placeholder={L("Announcement bar text","نص الشريط المتحرك")} value={site.announcement_text||""} onChange={e=>setSite({...site,announcement_text:e.target.value})}/></Panel>
 <Panel title={L("Promotion popup","البوب أب")}><label className="flex gap-2"><input type="checkbox" checked={!!site.popup_enabled} onChange={e=>setSite({...site,popup_enabled:e.target.checked})}/>{L("Show popup","إظهار البوب أب")}</label><Upload label={L("Popup image","صورة البوب أب")} onFile={f=>upload(f,"popup_image_url")}/><input className={field} placeholder={L("Title","العنوان")} value={site.popup_title||""} onChange={e=>setSite({...site,popup_title:e.target.value})}/><textarea className={field} placeholder={L("Offer text","نص العرض")} value={site.popup_body||""} onChange={e=>setSite({...site,popup_body:e.target.value})}/></Panel>
 <Panel title={L("About us","من نحن")}><Upload label={L("Section image","صورة القسم")} onFile={f=>upload(f,"about_image_url")}/><input className={field} placeholder={L("Section title","عنوان القسم")} value={site.about_title||""} onChange={e=>setSite({...site,about_title:e.target.value})}/><textarea className={field+" min-h-24"} placeholder={L("About your company","عن شركتك")} value={site.about_body||""} onChange={e=>setSite({...site,about_body:e.target.value})}/></Panel>
 <Panel title={L("Contact & links","التواصل والروابط")}><input className={field} placeholder={L("Phone","الهاتف")} value={site.contact_phone||""} onChange={e=>setSite({...site,contact_phone:e.target.value})}/><input className={field} placeholder="Email" value={site.contact_email||""} onChange={e=>setSite({...site,contact_email:e.target.value})}/><input className={field} placeholder="WhatsApp" value={site.whatsapp_url||""} onChange={e=>setSite({...site,whatsapp_url:e.target.value})}/><input className={field} placeholder={L("Map link","رابط الخريطة")} value={site.map_url||""} onChange={e=>setSite({...site,map_url:e.target.value})}/><input className={field} placeholder={L("Help center","مركز المساعدة")} value={site.help_url||""} onChange={e=>setSite({...site,help_url:e.target.value})}/></Panel>
 <button disabled={busy} onClick={save} className="sticky bottom-3 mt-5 w-full rounded-xl bg-cyan-400 p-3 font-bold text-slate-950">{busy?L("Saving…","جارٍ الحفظ…"):L("Save website","حفظ الموقع")}</button></aside>
 <section className="min-h-[700px] bg-slate-900 p-4"><div className="mb-3 flex items-center justify-between"><span className="text-sm text-slate-400">{L("Live website preview","معاينة الموقع المباشرة")}</span>{slug&&<a href={`/go/${slug}`} target="_blank" className="text-sm text-cyan-300">{L("Open live site ↗","فتح الموقع ↗")}</a>}</div>{slug?<iframe title="Website preview" className="h-[calc(100vh-145px)] w-full rounded-2xl border border-slate-700 bg-white" src={`/go/${slug}?preview=1`}/>:<div className="grid h-full place-items-center text-slate-500">{L("Configure AVERO GO first.","جهّز AVERO GO أولاً.")}</div>}</section></div>
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <details open className="mt-5 rounded-2xl border border-slate-800 bg-slate-900 p-4"><summary className="cursor-pointer font-semibold">{title}</summary><div className="mt-4 space-y-3 text-sm text-slate-300">{children}</div></details>}
function Upload({label,onFile}:{label:string;onFile:(f:File|undefined)=>void}){return <label className="block cursor-pointer rounded-xl border border-dashed border-slate-600 p-3 text-center hover:border-cyan-400">{label}<input className="hidden" type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>onFile(e.target.files?.[0])}/></label>}