"use client";
import {useEffect,useState} from "react";import {useLanguage} from "./LanguageProvider";
type Section={id:string;type:string;enabled:boolean;title?:string};
const templates=[{id:"restaurant_modern",name:"Restaurant modern"},{id:"minimal",name:"Minimal"},{id:"bold",name:"Bold"}];
const types=["hero","menu","offers","about","gallery","locations","contact","text","image","button"];
export default function GoWebsiteBuilder(){const{language}=useLanguage(),ar=language==="ar",L=(e:string,a:string)=>ar?a:e;const[data,setData]=useState<any>(null),[site,setSite]=useState<any>({}),[selected,setSelected]=useState("hero"),[tab,setTab]=useState<"insert"|"pages"|"themes">("insert"),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/go/manage",{cache:"no-store"}),j=await r.json();if(r.ok){setData(j);setSite({...j.store,site_sections:j.store?.site_sections||defaultSections()})}}useEffect(()=>{load()},[]);
 async function save(){setBusy(true);await fetch("/api/go/manage",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"appearance",...site})});setBusy(false)}
 async function upload(file:File|undefined,key:string){if(!file)return;const fd=new FormData();fd.append("file",file);const r=await fetch("/api/go/upload",{method:"POST",body:fd}),j=await r.json();if(r.ok)setSite((s:any)=>({...s,[key]:j.url}))}
 function add(type:string){const s={id:`${type}-${Date.now()}`,type,enabled:true,title:type[0].toUpperCase()+type.slice(1)};setSite({...site,site_sections:[...(site.site_sections||[]),s]});setSelected(s.id)}
 function remove(id:string){setSite({...site,site_sections:(site.site_sections||[]).filter((x:Section)=>x.id!==id)});setSelected("hero")}
 function move(id:string,d:number){const a=[...(site.site_sections||[])],i=a.findIndex((x:Section)=>x.id===id),j=i+d;if(i<0||j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];setSite({...site,site_sections:a})}
 if(!data)return <div className="p-8 text-slate-400">Loading…</div>;const sections:Section[]=site.site_sections||[],current=sections.find(s=>s.id===selected),slug=data.store?.slug;
 return <div className="flex min-h-[calc(100vh-88px)] bg-slate-950 text-white">
 <aside className="w-16 shrink-0 border-r border-slate-800 bg-slate-950 p-2">{(["insert","pages","themes"] as const).map(x=><button key={x} onClick={()=>setTab(x)} className={`mb-2 w-full rounded-xl px-1 py-3 text-[10px] ${tab===x?"bg-cyan-400/15 text-cyan-300":"text-slate-400"}`}>{x==="insert"?"+ "+L("Insert","إضافة"):x==="pages"?L("Pages","صفحات"):L("Themes","قوالب")}</button>)}</aside>
 <aside className="w-72 shrink-0 overflow-y-auto border-r border-slate-800 bg-slate-900/60 p-4">
 {tab==="insert"&&<><h2 className="font-bold">{L("Insert","إضافة")}</h2><div className="mt-4 grid grid-cols-2 gap-2">{types.map(t=><button key={t} onClick={()=>add(t)} className="rounded-xl border border-slate-700 bg-slate-950 p-3 text-xs capitalize hover:border-cyan-400">{t}</button>)}</div><h3 className="mt-6 text-sm font-bold">{L("Sections","الأقسام")}</h3><div className="mt-2 space-y-2">{sections.map(s=><button key={s.id} onClick={()=>setSelected(s.id)} className={`flex w-full items-center justify-between rounded-lg border p-2 text-left text-xs ${selected===s.id?"border-cyan-400":"border-slate-800"}`}><span>{s.title||s.type}</span><span onClick={e=>{e.stopPropagation();remove(s.id)}}>×</span></button>)}</div></>}
 {tab==="pages"&&<><h2 className="font-bold">{L("Pages","الصفحات")}</h2><p className="mt-2 text-xs text-slate-400">{L("Home is ready. Add sections now; standalone pages will use the same site identity.","الصفحة الرئيسية جاهزة. أضف الأقسام الآن، والصفحات المستقلة تستخدم نفس هوية الموقع.")}</p>{["Home","Menu","About us","Locations","Contact"].map(x=><div key={x} className="mt-2 rounded-xl border border-slate-800 p-3 text-sm">{x}</div>)}</>}
 {tab==="themes"&&<><h2 className="font-bold">{L("Templates & theme","القالب والهوية")}</h2><div className="mt-3 space-y-2">{templates.map(t=><button key={t.id} onClick={()=>setSite({...site,site_template:t.id})} className={`w-full rounded-xl border p-4 text-left text-sm ${site.site_template===t.id?"border-cyan-400":"border-slate-700"}`}>{t.name}</button>)}</div><Upload label={L("Upload logo","رفع الشعار")} onFile={f=>upload(f,"logo_url")}/><Upload label={L("Upload cover","رفع الغلاف")} onFile={f=>upload(f,"hero_image_url")}/><label className="mt-3 block text-xs">{L("Primary color","اللون الأساسي")} <input type="color" value={site.primary_color||"#06b6d4"} onChange={e=>setSite({...site,primary_color:e.target.value})}/></label><label className="mt-3 block text-xs">{L("Button color","لون الأزرار")} <input type="color" value={site.accent_color||"#f59e0b"} onChange={e=>setSite({...site,accent_color:e.target.value})}/></label></>}
 </aside>
 <main className="min-w-0 flex-1 p-4"><div className="mb-3 flex items-center justify-between rounded-xl border border-slate-800 bg-slate-900 px-4 py-2"><span className="text-sm font-bold">{data.company.name} · {L("Website Builder","مصمم الموقع")}</span><div className="flex gap-2">{slug&&<a target="_blank" href={`/go/${slug}`} className="rounded-lg border border-slate-700 px-3 py-2 text-xs">{L("Preview","معاينة")}</a>}<button disabled={busy} onClick={save} className="rounded-lg bg-cyan-400 px-4 py-2 text-xs font-bold text-slate-950">{busy?L("Saving…","جارٍ الحفظ…"):L("Publish","نشر")}</button></div></div>
 <div className="relative h-[calc(100vh-160px)] overflow-hidden rounded-2xl border border-slate-700 bg-white">{slug?<iframe className="h-full w-full" src={`/go/${slug}?preview=1`} title="Website"/>:<div className="grid h-full place-items-center text-slate-500">Configure AVERO GO first</div>}{current&&<div className="absolute bottom-4 left-1/2 flex -translate-x-1/2 gap-2 rounded-xl bg-slate-950/95 p-2 text-xs shadow-2xl"><span className="px-2 py-1">{current.title||current.type}</span><button onClick={()=>move(current.id,-1)}>↑</button><button onClick={()=>move(current.id,1)}>↓</button><button onClick={()=>remove(current.id)} className="text-rose-300">Delete</button></div>}</div></main></div>}
function defaultSections():Section[]{return[{id:"hero",type:"hero",enabled:true,title:"Hero"},{id:"menu",type:"menu",enabled:true,title:"Menu"},{id:"about",type:"about",enabled:true,title:"About us"},{id:"locations",type:"locations",enabled:true,title:"Locations"},{id:"contact",type:"contact",enabled:true,title:"Contact"}]}
function Upload({label,onFile}:{label:string;onFile:(f:File|undefined)=>void}){return <label className="mt-3 block cursor-pointer rounded-xl border border-dashed border-slate-600 p-3 text-center text-xs">{label}<input className="hidden" type="file" accept="image/*" onChange={e=>onFile(e.target.files?.[0])}/></label>}