"use client";
import{useEffect,useRef,useState}from"react";
import{LoaderCircle,Send,X}from"lucide-react";
type Msg={id?:string;role:string;message:string;created_at?:string};
type Point={x:number;y:number};
const marketingRegex=/بوست|post|ماركت|marketing|فيس|facebook|فايس|انستا|instagram|سناب|snap|تيك|tiktok|ستوري|story|اعلان|إعلان|صورة|نزل|نزّل|publish|content/i;
const SIZE=64,PAD=10;
export default function HelpChatBubble(){
 const[open,setOpen]=useState(false),[messages,setMessages]=useState<Msg[]>([]),[text,setText]=useState(""),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[pos,setPos]=useState<Point>({x:-200,y:-200});
 const end=useRef<HTMLDivElement>(null),drag=useRef<{startX:number;startY:number;originX:number;originY:number;moved:boolean;pointerId:number}|null>(null);
 function clamp(p:Point):Point{if(typeof window==="undefined")return p;return{x:Math.max(PAD,Math.min(p.x,window.innerWidth-SIZE-PAD)),y:Math.max(PAD,Math.min(p.y,window.innerHeight-SIZE-PAD))}}
 useEffect(()=>{let initial:Point|undefined;try{const saved=localStorage.getItem("avero-assistant-position");if(saved)initial=JSON.parse(saved)}catch{}setPos(clamp(initial||{x:window.innerWidth-SIZE-24,y:window.innerHeight-SIZE-24}));const resize=()=>setPos(p=>clamp(p));window.addEventListener("resize",resize);return()=>window.removeEventListener("resize",resize)},[]);
 async function load(){const response=await fetch("/api/help-center/chat",{cache:"no-store"});if(response.status===401)return;setReady(true);if(response.ok){const data=await response.json();setMessages(data.messages||[])}}
 useEffect(()=>{load();const timer=window.setInterval(load,15000);return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth"})},[messages,open]);
 async function send(){const message=text.trim();if(!message||busy)return;const isMarketing=marketingRegex.test(message),pending=isMarketing?"تمام. AVERO عم يوجّه الأمر لـ Foxy وعم يجهّز التنفيذ...":"تمام. AVERO عم يحلل الطلب ويدوّر على الحل المناسب...";setText("");setBusy(true);setMessages(c=>[...c,{role:"user",message},{role:"assistant",message:pending}]);const endpoint=isMarketing?"/api/marketing/chat-command":"/api/help-center/chat",response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message})}),data=await response.json().catch(()=>({}));setBusy(false);if(response.ok){const answer=data.message||data.reply?.message||"تم التنفيذ.";setMessages(c=>[...c.filter(i=>i.message!==pending),{role:"assistant",message:answer}]);if(isMarketing)window.dispatchEvent(new CustomEvent("avero-marketing-updated"))}else setMessages(c=>[...c.filter(i=>i.message!==pending),{role:"assistant",message:data.error||"ما قدرت نفّذ الطلب بهالشكل. جرّب اكتبه بطريقة أبسط."}])}
 function down(e:React.PointerEvent<HTMLButtonElement>){e.currentTarget.setPointerCapture(e.pointerId);drag.current={startX:e.clientX,startY:e.clientY,originX:pos.x,originY:pos.y,moved:false,pointerId:e.pointerId}}
 function move(e:React.PointerEvent<HTMLButtonElement>){if(!drag.current||drag.current.pointerId!==e.pointerId)return;const dx=e.clientX-drag.current.startX,dy=e.clientY-drag.current.startY;if(Math.abs(dx)+Math.abs(dy)>5){drag.current.moved=true;setOpen(false)}setPos(clamp({x:drag.current.originX+dx,y:drag.current.originY+dy}))}
 function up(){if(!drag.current)return;const wasMoved=drag.current.moved;drag.current=null;try{localStorage.setItem("avero-assistant-position",JSON.stringify(pos))}catch{}if(!wasMoved)setOpen(v=>!v)}
 if(!ready)return null;
 const panelW=390,panelH=Math.min(560,typeof window!=="undefined"?window.innerHeight-24:560),vw=typeof window!=="undefined"?window.innerWidth:1200,vh=typeof window!=="undefined"?window.innerHeight:800,actualW=Math.min(panelW,vw-24),panelLeft=Math.max(12,Math.min(pos.x+SIZE+12+actualW<=vw?pos.x+SIZE+12:pos.x-actualW-12,vw-actualW-12)),panelTop=Math.max(12,Math.min(pos.y+SIZE+12+panelH<=vh?pos.y+SIZE+12:pos.y-panelH-12,vh-panelH-12));
 return <><style jsx global>{`@keyframes averoEyeBlink{0%,42%,46%,74%,78%,100%{transform:scaleY(1)}44%,76%{transform:scaleY(.08)}}@keyframes averoPupilLook{0%,100%{transform:translate(-58%,-50%)}35%{transform:translate(-38%,-50%)}68%{transform:translate(-50%,-42%)}}@keyframes averoAura{0%,100%{box-shadow:0 0 0 0 rgba(34,211,238,.18),0 12px 34px rgba(6,182,212,.26)}50%{box-shadow:0 0 0 10px rgba(34,211,238,.04),0 14px 42px rgba(6,182,212,.38)}}`}</style>
  <div className="fixed z-[90]" style={{left:pos.x,top:pos.y,touchAction:"none"}}><button aria-label="AVERO Assistant" title="Drag anywhere · click to open" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{drag.current=null}} className="relative flex h-16 w-16 cursor-grab select-none items-center justify-center rounded-[22px] border border-cyan-200/40 bg-cyan-400 text-slate-950 active:cursor-grabbing" style={{animation:"averoAura 3.2s ease-in-out infinite"}}>
   <span className="relative block h-[26px] w-[40px] overflow-hidden rounded-[55%_45%_55%_45%/65%_65%_35%_35%] border-[2.5px] border-slate-950" style={{animation:"averoEyeBlink 5s ease-in-out infinite",transformOrigin:"center"}}><span className="absolute left-1/2 top-1/2 h-[14px] w-[14px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-slate-950"><span className="absolute left-1/2 top-1/2 h-[5px] w-[5px] rounded-full bg-cyan-100" style={{animation:"averoPupilLook 4.2s ease-in-out infinite"}}/></span></span>
   <span className="pointer-events-none absolute inset-0 rounded-[22px] border border-white/20"/>
  </button></div>
  {open&&<div className="fixed z-[89] flex flex-col overflow-hidden rounded-3xl border border-cyan-400/20 bg-slate-950 text-white shadow-2xl" style={{left:panelLeft,top:panelTop,width:actualW,height:panelH}}><div className="flex items-center justify-between border-b border-slate-800 bg-slate-900 p-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-400"><span className="relative block h-[15px] w-[24px] overflow-hidden rounded-[55%_45%_55%_45%/65%_65%_35%_35%] border-2 border-slate-950" style={{animation:"averoEyeBlink 5s ease-in-out infinite"}}><span className="absolute left-1/2 top-1/2 h-[8px] w-[8px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-slate-950"/></span></div><div><b>AVERO Assistant</b><p className="text-xs text-slate-500">Commands · problem solving · department routing</p></div></div><button onClick={()=>setOpen(false)} className="rounded-lg p-1 text-slate-400 hover:bg-slate-800"><X size={18}/></button></div>
   <div className="flex-1 space-y-3 overflow-y-auto p-4">{!messages.length&&<div className="rounded-2xl border border-cyan-400/15 bg-cyan-400/5 p-4 text-sm text-slate-300">أنا مساعد AVERO. قلّي شو المشكلة أو شو بدك تنفّذ: بوست، محتوى، ترتيب شغل، أو أمر لأي قسم، وأنا بوجّه الطلب للمكان الصح.</div>}{messages.map((item,index)=><div key={item.id||index} className={`flex ${item.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[84%] rounded-2xl px-3 py-2 text-sm leading-6 ${item.role==="user"?"bg-cyan-400 text-slate-950":"border border-slate-800 bg-slate-900 text-slate-200"}`}>{item.message}</div></div>)}{busy&&<div className="flex items-center gap-2 text-xs text-cyan-300"><LoaderCircle className="animate-spin" size={14}/> عم نفذ الطلب...</div>}<div ref={end}/></div>
   <div className="border-t border-slate-800 p-3"><div className="flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")send()}} placeholder="اكتب أمر أو مشكلة..." className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-900 px-3 py-3 text-sm outline-none focus:border-cyan-400"/><button onClick={send} disabled={busy||!text.trim()} className="rounded-xl bg-cyan-400 px-3 text-slate-950 disabled:opacity-50"><Send size={18}/></button></div></div>
  </div>}</>}
