"use client";
import {useEffect,useMemo,useState} from "react";
import {useLanguage} from "@/app/components/LanguageProvider";
const input="w-full rounded-xl border border-slate-800 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-500";
const tabs=[
 {key:"Dashboard",en:"Dashboard",ar:"لوحة التحكم"},{key:"Items",en:"Items",ar:"الأصناف"},{key:"Warehouses",en:"Warehouses",ar:"المستودعات"},{key:"Stock",en:"Stock",ar:"المخزون"},{key:"Movements",en:"Movements",ar:"الحركات"},{key:"Transfers",en:"Transfers",ar:"التحويلات"},{key:"Stock Count",en:"Stock Count",ar:"الجرد"},{key:"Waste",en:"Waste",ar:"الهدر"},{key:"Expiry",en:"Expiry",ar:"الصلاحية"},{key:"Reports",en:"Reports",ar:"التقارير"}
];
export default function InventoryWorkspace(){
 const {language}=useLanguage();const ar=language==='ar';const L=(en:string,arabic:string)=>ar?arabic:en;
 const[d,setD]=useState<any>({items:[],warehouses:[],units:[],suppliers:[],balances:[],batches:[],movements:[],transfers:[],counts:[],waste:[],summary:{}}),[tab,setTab]=useState("Dashboard"),[inventoryMenuOpen,setInventoryMenuOpen]=useState(false),[modal,setModal]=useState<string|null>(null),[f,setF]=useState<any>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[q,setQ]=useState("");
 async function load(){setLoading(true);const r=await fetch('/api/inventory',{cache:'no-store'});const j=await r.json();if(r.ok)setD(j);setLoading(false)}useEffect(()=>{load()},[]);
 async function add(kind:string,data=f){setSaving(true);const r=await fetch('/api/inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,data})});const j=await r.json();setSaving(false);if(!r.ok)return alert(j.error||'Save failed');setModal(null);setF({});await load()}
 const item=(id:string)=>d.items.find((x:any)=>x.id===id),wh=(id:string)=>d.warehouses.find((x:any)=>x.id===id),itemQty=(id:string)=>d.balances.filter((b:any)=>b.item_id===id).reduce((a:number,b:any)=>a+Number(b.qty_on_hand||0),0);const shown=useMemo(()=>d.items.filter((x:any)=>`${x.name} ${x.sku} ${x.category||''} ${x.barcode||''}`.toLowerCase().includes(q.toLowerCase())),[d.items,q]);
 const Card=({a,b}:{a:string,b:any})=><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><p className="text-xs text-slate-500">{a}</p><p className="mt-2 text-2xl font-black">{b}</p></div>;
 const currentTab=tabs.find(x=>x.key===tab)!;
 return <div className="space-y-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-black uppercase tracking-[.28em] text-cyan-300">{L('Operations','العمليات')}</p><h1 className="mt-2 text-3xl font-black">{L('Inventory','المخزون')}</h1><p className="text-sm text-slate-400">{L('Live warehouse control, receiving, transfers, counts, waste, costing and expiry.','إدارة مباشرة للمستودعات والاستلام والتحويلات والجرد والهدر والتكلفة والصلاحية.')}</p></div><div className="flex flex-wrap gap-2"><Btn onClick={()=>setModal('receive')}>+ {L('Receive Stock','استلام مخزون')}</Btn><Btn onClick={()=>setModal('transfer')}>↔ {L('Transfer','تحويل')}</Btn><Btn onClick={()=>setModal('count')}># {L('Stock Count','جرد')}</Btn><Btn onClick={()=>setModal('waste')}>− {L('Waste','هدر')}</Btn><Btn primary onClick={()=>setModal('item')}>+ {L('Item','صنف')}</Btn></div></div>
 <div className="relative inline-block"><button onClick={()=>setInventoryMenuOpen(v=>!v)} className="inline-flex items-center gap-3 rounded-xl border border-slate-700 bg-slate-900 px-4 py-2.5 text-sm font-black text-slate-200"><span>☰</span><span>{L('Inventory Menu','قائمة المخزون')}</span><span className="text-cyan-300">· {ar?currentTab.ar:currentTab.en}</span><span className={`text-[10px] text-slate-500 transition ${inventoryMenuOpen?'rotate-180':''}`}>▼</span></button>{inventoryMenuOpen&&<div className={`absolute top-12 z-30 w-64 rounded-2xl border border-slate-700 bg-slate-950 p-2 shadow-2xl ${ar?'right-0':'left-0'}`}>{tabs.map(x=><button key={x.key} onClick={()=>{setTab(x.key);setInventoryMenuOpen(false)}} className={`flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-sm font-bold ${tab===x.key?'bg-cyan-400 text-slate-950':'text-slate-300 hover:bg-slate-900'}`}><span>{ar?x.ar:x.en}</span>{tab===x.key&&<span>✓</span>}</button>)}</div>}</div>
 {loading?<p className="p-10 text-center text-slate-500">Loading inventory...</p>:<>
 {tab==='Dashboard'&&<div className="space-y-4"><div className="grid gap-3 md:grid-cols-4 xl:grid-cols-7"><Card a="Items" b={d.summary.items||0}/><Card a="Warehouses" b={d.summary.warehouses||0}/><Card a="Stock Value" b={`${Number(d.summary.total_value||0).toFixed(2)} SAR`}/><Card a="Low Stock" b={d.summary.low_stock||0}/><Card a="Out of Stock" b={d.summary.out_of_stock||0}/><Card a="Expiring ≤30d" b={d.summary.expiring_30d||0}/><Card a="Waste Value" b={`${Number(d.summary.waste_value||0).toFixed(2)} SAR`}/></div><div className="grid gap-4 lg:grid-cols-2"><Panel title="Recent Movements">{d.movements.length?d.movements.slice(0,8).map((m:any)=><Row key={m.id}><span>{item(m.item_id)?.name||'Item'} · <span className="capitalize text-slate-500">{String(m.movement_type).replaceAll('_',' ')}</span></span><b className={Number(m.quantity)>=0?'text-emerald-300':'text-rose-300'}>{Number(m.quantity)>0?'+':''}{Number(m.quantity).toFixed(2)}</b></Row>):<Empty text="No movements yet."/>}</Panel><Panel title="Inventory Controls"><div className="grid grid-cols-2 gap-3 text-sm"><Info a="Negative Stock" b="Blocked by default"/><Info a="Costing" b="Weighted Average"/><Info a="Receiving" b="Batch & expiry ready"/><Info a="Transfers" b="In transit → received"/><Info a="Stock Count" b="Auto variance posting"/><Info a="Waste" b="Costed automatically"/></div></Panel></div></div>}
 {tab==='Items'&&<div className="space-y-3"><input className={input} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search item, SKU, barcode or category..."/><div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900">{shown.length?shown.map((x:any)=><div key={x.id} className="grid grid-cols-[1.5fr_.8fr_.8fr_.7fr_.7fr] gap-3 border-b border-slate-800 px-5 py-4 text-sm"><div><b>{x.name}</b><p className="text-xs text-slate-500">{x.sku} · {x.barcode||'No barcode'}</p></div><span className="capitalize">{String(x.item_type).replaceAll('_',' ')}</span><span>{x.category||'—'}</span><span>{itemQty(x.id).toFixed(2)}</span><span>{Number(x.average_cost||0).toFixed(2)} SAR</span></div>):<Empty text="No items yet."/>}</div></div>}
 {tab==='Warehouses'&&<div><div className="mb-3 flex justify-end"><Btn onClick={()=>setModal('warehouse')}>+ Warehouse</Btn></div><div className="grid gap-3 md:grid-cols-3">{d.warehouses.length?d.warehouses.map((x:any)=><div key={x.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><b>{x.name}</b><p className="mt-1 text-xs text-slate-500">{x.code} · {x.warehouse_type}</p><p className="mt-4 text-sm">{x.city||'No city'}</p></div>):<Empty text="No warehouses yet."/>}</div></div>}
 {tab==='Stock'&&<Panel title="Stock by Warehouse">{d.balances.length?d.balances.map((b:any)=><div key={b.id} className="grid grid-cols-5 border-b border-slate-800 py-3 text-sm"><b>{item(b.item_id)?.name||'Item'}</b><span>{wh(b.warehouse_id)?.name||'Warehouse'}</span><span>On Hand {Number(b.qty_on_hand).toFixed(2)}</span><span>Reserved {Number(b.qty_reserved).toFixed(2)}</span><span>Available {(Number(b.qty_on_hand)-Number(b.qty_reserved)).toFixed(2)}</span></div>):<Empty text="No stock balances yet."/>}</Panel>}
 {tab==='Movements'&&<Panel title="Stock Ledger">{d.movements.length?d.movements.map((m:any)=><div key={m.id} className="grid grid-cols-6 border-b border-slate-800 py-3 text-sm"><span>{new Date(m.movement_date).toLocaleDateString()}</span><b>{item(m.item_id)?.name||'Item'}</b><span>{wh(m.warehouse_id)?.name||'Warehouse'}</span><span className="capitalize">{String(m.movement_type).replaceAll('_',' ')}</span><span>{Number(m.quantity)>0?'+':''}{Number(m.quantity).toFixed(2)}</span><span>{Number(m.total_cost||0).toFixed(2)} SAR</span></div>):<Empty text="No movements yet."/>}</Panel>}
 {tab==='Transfers'&&<div><div className="mb-3 flex justify-end"><Btn onClick={()=>setModal('transfer')}>+ New Transfer</Btn></div><Panel title="Warehouse Transfers">{d.transfers.length?d.transfers.map((t:any)=><div key={t.id} className="grid grid-cols-[1fr_1fr_1fr_.7fr_.7fr] items-center border-b border-slate-800 py-3 text-sm"><b>{t.transfer_no}</b><span>{wh(t.from_warehouse_id)?.name||'From'}</span><span>{wh(t.to_warehouse_id)?.name||'To'}</span><span className="capitalize">{String(t.status).replaceAll('_',' ')}</span>{t.status==='in_transit'?<button onClick={()=>add('receive_transfer',{transfer_id:t.id})} className="rounded-lg bg-emerald-400 px-3 py-2 text-xs font-black text-slate-950">Receive</button>:<span className="text-emerald-300">Completed</span>}</div>):<Empty text="No transfers yet."/>}</Panel></div>}
 {tab==='Stock Count'&&<div><div className="mb-3 flex justify-end"><Btn onClick={()=>setModal('count')}>+ New Count</Btn></div><Panel title="Stock Counts">{d.counts.length?d.counts.map((c:any)=><div key={c.id} className="grid grid-cols-4 border-b border-slate-800 py-3 text-sm"><b>{c.count_no}</b><span>{wh(c.warehouse_id)?.name||'Warehouse'}</span><span>{c.count_date}</span><span className="capitalize text-emerald-300">{c.status}</span></div>):<Empty text="No stock counts yet."/>}</Panel></div>}
 {tab==='Waste'&&<div><div className="mb-3 flex justify-end"><Btn onClick={()=>setModal('waste')}>+ Record Waste</Btn></div><Panel title="Waste & Damage">{d.waste.length?d.waste.map((w:any)=><div key={w.id} className="grid grid-cols-5 border-b border-slate-800 py-3 text-sm"><span>{new Date(w.waste_date).toLocaleDateString()}</span><b>{item(w.item_id)?.name||'Item'}</b><span>{wh(w.warehouse_id)?.name||'Warehouse'}</span><span className="capitalize">{String(w.reason_code).replaceAll('_',' ')}</span><b className="text-rose-300">{(Number(w.quantity)*Number(w.unit_cost)).toFixed(2)} SAR</b></div>):<Empty text="No waste recorded yet."/>}</Panel></div>}
 {tab==='Expiry'&&<Panel title="Batch & Expiry Control">{d.batches.length?d.batches.map((b:any)=><div key={b.id} className="grid grid-cols-5 border-b border-slate-800 py-3 text-sm"><b>{item(b.item_id)?.name||'Item'}</b><span>{wh(b.warehouse_id)?.name||'Warehouse'}</span><span>Batch {b.batch_no}</span><span>{b.expiry_date||'No expiry'}</span><span>{Number(b.qty_on_hand).toFixed(2)}</span></div>):<Empty text="No tracked batches yet."/>}</Panel>}
 {tab==='Reports'&&<div className="grid gap-3 md:grid-cols-3">{['Stock Balance','Stock Movement Ledger','Inventory Valuation','Expiry Report','Waste Report','Transfer Report','Stock Count Variance','Low Stock Report','Dead Stock Analysis'].map(x=><div key={x} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><b>{x}</b><p className="mt-2 text-xs text-slate-500">Live report foundation ready for filters and export.</p></div>)}</div>}
 </>}
 {modal&&<Modal title={titles[modal]||modal} close={()=>{setModal(null);setF({})}}><div className="grid gap-4 md:grid-cols-2">
 {modal==='receive'&&<><Sel l="Item *" k="item_id" f={f} setF={setF} opts={d.items.map((x:any)=>[x.id,`${x.name} (${x.sku})`])}/><Sel l="Warehouse *" k="warehouse_id" f={f} setF={setF} opts={d.warehouses.map((x:any)=>[x.id,x.name])}/><I l="Quantity *" k="quantity" type="number" f={f} setF={setF}/><I l="Unit Cost *" k="unit_cost" type="number" f={f} setF={setF}/><I l="Supplier Invoice / GRN No." k="reference_no" f={f} setF={setF}/><I l="Batch No." k="batch_no" f={f} setF={setF}/><I l="Manufacture Date" k="manufacture_date" type="date" f={f} setF={setF}/><I l="Expiry Date" k="expiry_date" type="date" f={f} setF={setF}/></>}
 {modal==='transfer'&&<><Sel l="From Warehouse *" k="from_warehouse_id" f={f} setF={setF} opts={d.warehouses.map((x:any)=>[x.id,x.name])}/><Sel l="To Warehouse *" k="to_warehouse_id" f={f} setF={setF} opts={d.warehouses.map((x:any)=>[x.id,x.name])}/><Sel l="Item *" k="item_id" f={f} setF={setF} opts={d.items.map((x:any)=>[x.id,`${x.name} (${x.sku})`])}/><I l="Quantity *" k="quantity" type="number" f={f} setF={setF}/><I l="Notes" k="notes" f={f} setF={setF}/></>}
 {modal==='count'&&<><Sel l="Warehouse *" k="warehouse_id" f={f} setF={setF} opts={d.warehouses.map((x:any)=>[x.id,x.name])}/><Sel l="Item *" k="item_id" f={f} setF={setF} opts={d.items.map((x:any)=>[x.id,`${x.name} (${x.sku})`])}/><I l="Counted Quantity *" k="counted_qty" type="number" f={f} setF={setF}/><I l="Notes" k="notes" f={f} setF={setF}/></>}
 {modal==='waste'&&<><Sel l="Warehouse *" k="warehouse_id" f={f} setF={setF} opts={d.warehouses.map((x:any)=>[x.id,x.name])}/><Sel l="Item *" k="item_id" f={f} setF={setF} opts={d.items.map((x:any)=>[x.id,`${x.name} (${x.sku})`])}/><I l="Quantity *" k="quantity" type="number" f={f} setF={setF}/><label className="text-xs font-bold text-slate-400">Reason<select className={input} value={f.reason_code||'damage'} onChange={e=>setF({...f,reason_code:e.target.value})}><option value="damage">Damage</option><option value="expired">Expired</option><option value="spoilage">Spoilage</option><option value="theft">Theft</option><option value="production_loss">Production Loss</option><option value="sample">Sample</option><option value="other">Other</option></select></label><I l="Notes" k="notes" f={f} setF={setF}/></>}
 {modal==='warehouse'&&<><I l="Warehouse Name *" k="name" f={f} setF={setF}/><I l="Code (auto if blank)" k="code" f={f} setF={setF}/><I l="City" k="city" f={f} setF={setF}/><I l="Country" k="country" f={f} setF={setF}/><I l="Address" k="address" f={f} setF={setF}/></>}
 {modal==='item'&&<><I l="Item Name *" k="name" f={f} setF={setF}/><I l="SKU (auto if blank)" k="sku" f={f} setF={setF}/><I l="Barcode" k="barcode" f={f} setF={setF}/><I l="Category" k="category" f={f} setF={setF}/><label className="text-xs font-bold text-slate-400">Item Type<select className={input} value={f.item_type||'raw_material'} onChange={e=>setF({...f,item_type:e.target.value})}><option value="raw_material">Raw Material</option><option value="finished_good">Finished Good</option><option value="packaging">Packaging</option><option value="consumable">Consumable</option><option value="spare_part">Spare Part</option><option value="asset">Asset</option><option value="service">Service</option></select></label><Sel l="Base Unit" k="base_unit_id" f={f} setF={setF} opts={d.units.map((x:any)=>[x.id,x.name])}/><I l="Reorder Point" k="reorder_point" type="number" f={f} setF={setF}/><I l="Safety Stock" k="safety_stock" type="number" f={f} setF={setF}/><Sel l="Preferred Supplier" k="supplier_id" f={f} setF={setF} opts={d.suppliers.map((x:any)=>[x.id,x.name])}/><I l="Supplier Item Code" k="supplier_item_code" f={f} setF={setF}/><div className="md:col-span-2 grid gap-3 sm:grid-cols-4"><Check l="Track Batches" k="track_batches" f={f} setF={setF}/><Check l="Track Expiry" k="track_expiry" f={f} setF={setF}/><Check l="Track Serials" k="track_serials" f={f} setF={setF}/><Check l="Allow Negative" k="allow_negative_stock" f={f} setF={setF}/></div></>}
 </div><button disabled={saving} onClick={()=>add(modal==='receive'?'receive_stock':modal==='count'?'stock_count':modal)} className="mt-6 w-full rounded-xl bg-cyan-400 py-3 font-black text-slate-950 disabled:opacity-50">{saving?'Saving...':'Confirm'}</button></Modal>}
 </div>}
const titles:any={receive:'Receive Stock / GRN',transfer:'Warehouse Transfer',count:'Stock Count',waste:'Waste / Damage',item:'New Item',warehouse:'New Warehouse'};
function Btn({children,onClick,primary=false}:any){return <button onClick={onClick} className={primary?'rounded-xl bg-cyan-400 px-4 py-2 text-sm font-black text-slate-950':'rounded-xl border border-slate-700 px-4 py-2 text-sm font-bold'}>{children}</button>}
function Panel({title,children}:any){return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h3 className="mb-3 font-black">{title}</h3>{children}</div>}
function Row({children}:any){return <div className="flex justify-between border-b border-slate-800 py-3 text-sm last:border-0">{children}</div>}
function Empty({text}:any){return <p className="p-8 text-center text-sm text-slate-500">{text}</p>}
function Info({a,b}:any){return <div className="rounded-xl bg-slate-950 p-3"><p className="text-xs text-slate-500">{a}</p><b className="mt-1 block">{b}</b></div>}
function Modal({title,close,children}:any){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-3xl border border-slate-700 bg-slate-900 p-6"><div className="flex justify-between"><h2 className="text-2xl font-black">{title}</h2><button onClick={close} className="text-2xl">×</button></div><div className="mt-5">{children}</div></div></div>}
function I({l,k,f,setF,type='text'}:any){return <label className="text-xs font-bold text-slate-400">{l}<input type={type} className={input} value={f[k]||''} onChange={e=>setF({...f,[k]:e.target.value})}/></label>}
function Sel({l,k,f,setF,opts}:any){return <label className="text-xs font-bold text-slate-400">{l}<select className={input} value={f[k]||''} onChange={e=>setF({...f,[k]:e.target.value})}><option value="">Select...</option>{opts.map((o:any)=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></label>}
function Check({l,k,f,setF}:any){return <label className="flex items-center gap-2 rounded-xl border border-slate-800 p-3 text-xs font-bold"><input type="checkbox" checked={!!f[k]} onChange={e=>setF({...f,[k]:e.target.checked})}/>{l}</label>}
