"use client";
import {useEffect,useMemo,useState} from "react";
const input="w-full rounded-xl border border-slate-800 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-500";
const tabs=["Dashboard","Items","Warehouses","Stock","Movements","Transfers","Stock Count","Waste","Expiry","Reports"];
export default function InventoryWorkspace(){
 const[d,setD]=useState<any>({items:[],warehouses:[],units:[],suppliers:[],balances:[],batches:[],movements:[],summary:{}}),[tab,setTab]=useState("Dashboard"),[modal,setModal]=useState<string|null>(null),[f,setF]=useState<any>({}),[loading,setLoading]=useState(true),[q,setQ]=useState("");
 async function load(){setLoading(true);const r=await fetch('/api/inventory',{cache:'no-store'});const j=await r.json();if(r.ok)setD(j);setLoading(false)}useEffect(()=>{load()},[]);
 async function add(kind:string){const payload=kind==='stock'?{kind:'stock_movement',data:f}:{kind,data:f};const r=await fetch('/api/inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)return alert(j.error||'Save failed');setModal(null);setF({});load()}
 const itemQty=(id:string)=>d.balances.filter((b:any)=>b.item_id===id).reduce((a:number,b:any)=>a+Number(b.qty_on_hand||0),0);const shown=useMemo(()=>d.items.filter((x:any)=>`${x.name} ${x.sku} ${x.category||''} ${x.barcode||''}`.toLowerCase().includes(q.toLowerCase())),[d.items,q]);const Card=({a,b}:{a:string,b:any})=><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><p className="text-xs text-slate-500">{a}</p><p className="mt-2 text-2xl font-black">{b}</p></div>;
 return <div className="space-y-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.28em] text-cyan-300">Operations</p><h1 className="mt-2 text-3xl font-black">Inventory</h1><p className="text-sm text-slate-400">Universal stock, warehouses, costing, suppliers, batches and control.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>setModal('unit')} className="rounded-xl border border-slate-700 px-4 py-2 text-sm font-bold">+ Unit</button><button onClick={()=>setModal('warehouse')} className="rounded-xl border border-slate-700 px-4 py-2 text-sm font-bold">+ Warehouse</button><button onClick={()=>setModal('stock')} className="rounded-xl border border-cyan-700 px-4 py-2 text-sm font-bold text-cyan-300">Adjust Stock</button><button onClick={()=>setModal('item')} className="rounded-xl bg-cyan-400 px-4 py-2 text-sm font-black text-slate-950">+ Item</button></div></div>
 <div className="flex gap-2 overflow-x-auto">{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm font-bold ${tab===x?'bg-cyan-400 text-slate-950':'border border-slate-800 bg-slate-900 text-slate-400'}`}>{x}</button>)}</div>
 {loading?<p className="p-10 text-center text-slate-500">Loading inventory...</p>:<>
 {tab==='Dashboard'&&<div className="space-y-4"><div className="grid gap-3 md:grid-cols-6"><Card a="Items" b={d.summary.items||0}/><Card a="Warehouses" b={d.summary.warehouses||0}/><Card a="Stock Value" b={`${Number(d.summary.total_value||0).toFixed(2)} SAR`}/><Card a="Low Stock" b={d.summary.low_stock||0}/><Card a="Out of Stock" b={d.summary.out_of_stock||0}/><Card a="Expiring ≤30d" b={d.summary.expiring_30d||0}/></div><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h3 className="font-black">Recent Movements</h3>{d.movements.length?d.movements.slice(0,8).map((m:any)=><div key={m.id} className="flex justify-between border-b border-slate-800 py-3 text-sm"><span className="capitalize">{String(m.movement_type).replaceAll('_',' ')}</span><span>{Number(m.quantity).toFixed(2)}</span></div>):<p className="py-8 text-center text-slate-500">No stock movements yet.</p>}</div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h3 className="font-black">Inventory Engine</h3><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><Info a="Negative Stock" b="Blocked by default"/><Info a="Costing" b="Weighted Average"/><Info a="Batches / Expiry" b="Optional per item"/><Info a="Serial Tracking" b="Optional per item"/><Info a="Supplier Link" b="Preferred + supplier code"/><Info a="Units" b="Purchase → Base conversion"/></div></div></div></div>}
 {tab==='Items'&&<div className="space-y-3"><input className={input} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search item, SKU, barcode or category..."/><div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900">{shown.length?shown.map((x:any)=><div key={x.id} className="grid grid-cols-[1.5fr_.8fr_.8fr_.7fr_.7fr] gap-3 border-b border-slate-800 px-5 py-4 text-sm"><div><b>{x.name}</b><p className="text-xs text-slate-500">{x.sku} · {x.barcode||'No barcode'}</p></div><span className="capitalize">{String(x.item_type).replaceAll('_',' ')}</span><span>{x.category||'—'}</span><span>{itemQty(x.id).toFixed(2)}</span><span>{Number(x.average_cost||0).toFixed(2)} SAR</span></div>):<p className="p-10 text-center text-slate-500">No items yet.</p>}</div></div>}
 {tab==='Warehouses'&&<div className="grid gap-3 md:grid-cols-3">{d.warehouses.length?d.warehouses.map((x:any)=><div key={x.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><b>{x.name}</b><p className="mt-1 text-xs text-slate-500">{x.code} · {x.warehouse_type}</p><p className="mt-4 text-sm">{x.city||'No city'}</p></div>):<div className="rounded-2xl border border-slate-800 bg-slate-900 p-10 text-center text-slate-500 md:col-span-3">No warehouses yet.</div>}</div>}
 {tab==='Stock'&&<div className="rounded-2xl border border-slate-800 bg-slate-900">{d.balances.length?d.balances.map((b:any)=><div key={b.id} className="grid grid-cols-5 border-b border-slate-800 p-4 text-sm"><span>{d.items.find((i:any)=>i.id===b.item_id)?.name||b.item_id}</span><span>{d.warehouses.find((w:any)=>w.id===b.warehouse_id)?.name||'Warehouse'}</span><span>On Hand {Number(b.qty_on_hand).toFixed(2)}</span><span>Reserved {Number(b.qty_reserved).toFixed(2)}</span><span>Available {(Number(b.qty_on_hand)-Number(b.qty_reserved)).toFixed(2)}</span></div>):<p className="p-10 text-center text-slate-500">No stock balances yet.</p>}</div>}
 {tab==='Movements'&&<div className="rounded-2xl border border-slate-800 bg-slate-900">{d.movements.length?d.movements.map((m:any)=><div key={m.id} className="grid grid-cols-5 border-b border-slate-800 p-4 text-sm"><span>{new Date(m.movement_date).toLocaleDateString()}</span><span>{d.items.find((i:any)=>i.id===m.item_id)?.name||'Item'}</span><span className="capitalize">{String(m.movement_type).replaceAll('_',' ')}</span><span>{Number(m.quantity).toFixed(2)}</span><span>{Number(m.total_cost||0).toFixed(2)}</span></div>):<p className="p-10 text-center text-slate-500">No movements yet.</p>}</div>}
 {tab==='Expiry'&&<div className="rounded-2xl border border-slate-800 bg-slate-900">{d.batches.length?d.batches.map((b:any)=><div key={b.id} className="grid grid-cols-4 border-b border-slate-800 p-4 text-sm"><span>{d.items.find((i:any)=>i.id===b.item_id)?.name||'Item'}</span><span>{b.batch_no}</span><span>{b.expiry_date||'No expiry'}</span><span>{Number(b.qty_on_hand).toFixed(2)}</span></div>):<p className="p-10 text-center text-slate-500">No tracked batches yet.</p>}</div>}
 {['Transfers','Stock Count','Waste','Reports'].includes(tab)&&<div className="rounded-2xl border border-slate-800 bg-slate-900 p-12 text-center"><h3 className="text-xl font-black">{tab}</h3><p className="mt-2 text-sm text-slate-500">Database foundation is ready. Workflow UI comes in the next slice.</p></div>}
 </>}
 {modal&&<Modal title={modal==='stock'?'Stock Adjustment':`New ${modal}`} close={()=>{setModal(null);setF({})}}><div className="grid gap-4 md:grid-cols-2">
 {modal==='unit'&&<><I l="Unit Name *" k="name" f={f} setF={setF}/><I l="Code *" k="code" f={f} setF={setF}/><I l="Symbol" k="symbol" f={f} setF={setF}/><label className="text-xs font-bold text-slate-400">Category<select className={input} value={f.category||'count'} onChange={e=>setF({...f,category:e.target.value})}><option value="count">Count</option><option value="weight">Weight</option><option value="volume">Volume</option><option value="length">Length</option><option value="other">Other</option></select></label></>}
 {modal==='warehouse'&&<><I l="Warehouse Name *" k="name" f={f} setF={setF}/><I l="Code (auto if blank)" k="code" f={f} setF={setF}/><label className="text-xs font-bold text-slate-400">Type<select className={input} value={f.warehouse_type||'warehouse'} onChange={e=>setF({...f,warehouse_type:e.target.value})}><option value="warehouse">Warehouse</option><option value="branch">Branch</option><option value="store">Store</option><option value="vehicle">Vehicle</option><option value="virtual">Virtual</option></select></label><I l="City" k="city" f={f} setF={setF}/><I l="Country" k="country" f={f} setF={setF}/><I l="Address" k="address" f={f} setF={setF}/></>}
 {modal==='stock'&&<><Sel l="Item *" k="item_id" f={f} setF={setF} opts={d.items.map((x:any)=>[x.id,`${x.name} (${x.sku})`])}/><Sel l="Warehouse *" k="warehouse_id" f={f} setF={setF} opts={d.warehouses.map((x:any)=>[x.id,x.name])}/><I l="Quantity (+ in / - out) *" k="quantity" type="number" f={f} setF={setF}/><I l="Unit Cost (optional)" k="unit_cost" type="number" f={f} setF={setF}/><I l="Reference No." k="reference_no" f={f} setF={setF}/><I l="Reason" k="reason" f={f} setF={setF}/></>}
 {modal==='item'&&<><I l="Item Name *" k="name" f={f} setF={setF}/><I l="SKU (auto if blank)" k="sku" f={f} setF={setF}/><I l="Barcode" k="barcode" f={f} setF={setF}/><I l="Category" k="category" f={f} setF={setF}/><I l="Brand" k="brand" f={f} setF={setF}/><label className="text-xs font-bold text-slate-400">Item Type<select className={input} value={f.item_type||'raw_material'} onChange={e=>setF({...f,item_type:e.target.value})}><option value="raw_material">Raw Material</option><option value="finished_good">Finished Good</option><option value="packaging">Packaging</option><option value="consumable">Consumable</option><option value="spare_part">Spare Part</option><option value="asset">Asset</option><option value="service">Service</option></select></label><Sel l="Base Unit" k="base_unit_id" f={f} setF={setF} opts={d.units.map((x:any)=>[x.id,`${x.name}${x.symbol?` (${x.symbol})`:''}`])}/><Sel l="Purchase Unit" k="purchase_unit_id" f={f} setF={setF} opts={d.units.map((x:any)=>[x.id,x.name])}/><I l="Purchase → Base Factor" k="purchase_to_base_factor" type="number" f={f} setF={setF}/><Sel l="Preferred Supplier" k="supplier_id" f={f} setF={setF} opts={d.suppliers.map((x:any)=>[x.id,x.name])}/><I l="Supplier Item Code" k="supplier_item_code" f={f} setF={setF}/><I l="Last Purchase Cost" k="last_purchase_cost" type="number" f={f} setF={setF}/><I l="Lead Time (days)" k="lead_time_days" type="number" f={f} setF={setF}/><I l="Minimum Order Qty" k="minimum_order_qty" type="number" f={f} setF={setF}/><I l="Reorder Point" k="reorder_point" type="number" f={f} setF={setF}/><I l="Safety Stock" k="safety_stock" type="number" f={f} setF={setF}/><I l="Min Stock" k="min_stock" type="number" f={f} setF={setF}/><I l="Max Stock" k="max_stock" type="number" f={f} setF={setF}/><Sel l="Opening Warehouse" k="opening_warehouse_id" f={f} setF={setF} opts={d.warehouses.map((x:any)=>[x.id,x.name])}/><I l="Opening Qty" k="opening_qty" type="number" f={f} setF={setF}/><I l="Opening Unit Cost" k="opening_unit_cost" type="number" f={f} setF={setF}/><div className="md:col-span-2 grid gap-3 sm:grid-cols-4"><Check l="Track Batches" k="track_batches" f={f} setF={setF}/><Check l="Track Expiry" k="track_expiry" f={f} setF={setF}/><Check l="Track Serials" k="track_serials" f={f} setF={setF}/><Check l="Allow Negative" k="allow_negative_stock" f={f} setF={setF}/></div></>}
 </div><button onClick={()=>add(modal)} className="mt-6 w-full rounded-xl bg-cyan-400 py-3 font-black text-slate-950">Save</button></Modal>}
 </div>}
function Modal({title,close,children}:any){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-3xl border border-slate-700 bg-slate-900 p-6"><div className="flex justify-between"><h2 className="text-2xl font-black">{title}</h2><button onClick={close} className="text-2xl">×</button></div><div className="mt-5">{children}</div></div></div>}
function I({l,k,f,setF,type='text'}:any){return <label className="text-xs font-bold text-slate-400">{l}<input type={type} className={input} value={f[k]||''} onChange={e=>setF({...f,[k]:e.target.value})}/></label>}
function Sel({l,k,f,setF,opts}:any){return <label className="text-xs font-bold text-slate-400">{l}<select className={input} value={f[k]||''} onChange={e=>setF({...f,[k]:e.target.value})}><option value="">—</option>{opts.map((o:any)=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></label>}
function Check({l,k,f,setF}:any){return <label className="flex items-center gap-2 rounded-xl border border-slate-800 p-3 text-sm"><input type="checkbox" checked={!!f[k]} onChange={e=>setF({...f,[k]:e.target.checked})}/>{l}</label>}
function Info({a,b}:any){return <div className="rounded-xl bg-slate-950 p-4"><p className="text-slate-500">{a}</p><b>{b}</b></div>}
