"use client";
import Link from "next/link";
import { Activity, Building2, CheckCircle2, ChevronRight, ShieldCheck } from "lucide-react";
import { useLanguage } from "./LanguageProvider";
type Company={id:string;name:string;status:string};type Props={companies:Company[];subscribers:Record<string,string[]>};
const APPS=[["app_sell","POS"],["app_accounting","Accounting"],["app_hr","HR & Employees"],["app_loyalty","Loyalty & Promotions"],["app_intelligence","AI & Automation"],["app_zatca","ZATCA Fatoora"]] as const;
export default function KingManagerMonitoring({companies,subscribers}:Props){const{language}=useLanguage();const ar=language==="ar";return <main className="mx-auto max-w-[1500px] space-y-6 px-4 py-6 md:px-8 text-white">
<section className="rounded-3xl border border-slate-800 bg-slate-900/60 p-6"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-cyan-300"><ShieldCheck size={16}/> AVERO KING · MANAGER MONITORING</div><h1 className="mt-3 text-3xl font-black">{ar?"مراقبة النظام والعملاء":"System & Client Monitoring"}</h1><p className="mt-2 text-sm text-slate-400">{ar?"راجع تطبيقات AVERO أولاً، ثم راقب كل عميل حسب التطبيقات المفعلة على اشتراكه.":"Review AVERO applications first, then monitor each client according to enabled subscriptions."}</p></section>
<section><h2 className="mb-3 text-lg font-bold">{ar?"1. فحص نظام AVERO":"1. AVERO System Review"}</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{APPS.map(([key,name])=><div key={key} className="rounded-2xl border border-slate-800 bg-slate-900/55 p-4"><div className="flex items-center justify-between"><Activity size={18} className="text-cyan-300"/><span className="rounded-full bg-slate-950 px-2 py-1 text-[10px] text-slate-400">{subscribers[key]?.length||0} {ar?"عميل":"clients"}</span></div><p className="mt-3 font-bold">{name}</p><p className="mt-1 text-xs text-slate-500">{ar?"متاح للفحص على حساب King قبل اعتماد التحديث.":"Available for King review before release."}</p></div>)}</div><div className="mt-3 rounded-2xl border border-cyan-400/15 bg-cyan-400/[.04] p-4 text-xs leading-5 text-slate-400">{ar?"AVERO يعمل من كود موحّد: بعد ما تفحص التعديل وتعمل Deploy للإصدار المعتمد، يصل التحديث تلقائياً لكل العملاء على نفس الإصدار، بينما ظهور كل Application يبقى حسب اشتراك العميل.":"AVERO uses one shared codebase: once a reviewed release is deployed, clients on that release receive it automatically, while application visibility remains subscription-based."}</div></section>
<section><h2 className="mb-3 text-lg font-bold">{ar?"2. مراقبة العملاء":"2. Client Monitoring"}</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{companies.map(c=>{const enabled=APPS.filter(([k])=>(subscribers[k]||[]).includes(c.id)).map(([,n])=>n);return <Link key={c.id} href={"/manager-monitoring?company="+c.id} className="group rounded-2xl border border-slate-800 bg-slate-900/55 p-5 hover:border-cyan-400/30"><div className="flex items-center justify-between"><Building2 size={18} className="text-cyan-300"/><ChevronRight size={16} className="text-slate-600 group-hover:text-cyan-300"/></div><p className="mt-3 font-bold">{c.name}</p><p className="mt-1 text-xs text-slate-500">{c.status}</p><div className="mt-3 flex flex-wrap gap-1.5">{enabled.length?enabled.map(n=><span key={n} className="rounded-lg bg-slate-950 px-2 py-1 text-[10px] text-slate-400">{n}</span>):<span className="text-[10px] text-slate-600">{ar?"لا تطبيقات مفعلة":"No enabled apps"}</span>}</div></Link>})}</div></section></main>}