"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import Sidebar from "./Sidebar";import DashboardHeader from "./DashboardHeader";import{Paperclip,Send,Loader2,MessageCircle}from"lucide-react";
type Conversation={id:string;customer_id:string;direction:"inbound"|"outbound";message:string;created_at:string;ai_generated?:boolean};type Stats={inbound:number;outbound:number;leads:number;qualified:number};
export default function LeoSalesLive(){const[messages,setMessages]=useState<Conversation[]>([]),[stats,setStats]=useState<Stats>({inbound:0,outbound:0,leads:0,qualified:0}),[draft,setDraft]=useState(""),[file,setFile]=useState<File|null>(null),[sending,setSending]=useState(false),[error,setError]=useState("");const bottom=useRef<HTMLDivElement>(null),fileInput=useRef<HTMLInputElement>(null);
 async function load(){try{const r=await fetch("/api/ai-departments/sales/conversations",{cache:"no-store"});if(r.ok){const j=await r.json();setMessages(j.conversations||[]);setStats(j.stats||{inbound:0,outbound:0,leads:0,qualified:0})}}catch{}}
 useEffect(()=>{load();const t=setInterval(load,3000);return()=>clearInterval(t)},[]);
 const activeCustomer=useMemo(()=>messages.find(m=>m.direction==="inbound")?.customer_id||messages[0]?.customer_id||"",[messages]);const chat=useMemo(()=>messages.filter(m=>m.customer_id===activeCustomer).slice().reverse(),[messages,activeCustomer]);useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"})},[chat.length]);
 async function send(){if((!draft.trim()&&!file)||!activeCustomer||sending)return;setSending(true);setError("");try{const f=new FormData();f.set("customer_id",activeCustomer);f.set("message",draft.trim());if(file)f.set("file",file);const r=await fetch("/api/ai-departments/sales/send",{method:"POST",body:f});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Send failed");setDraft("");setFile(null);if(fileInput.current)fileInput.current.value="";await load()}catch(e){setError(e instanceof Error?e.message:"Send failed")}finally{setSending(false)}}
 return <div className="min-h-screen bg-slate-950 text-white"><Sidebar/><div className="ml-64 min-h-screen"><DashboardHeader/><main className="p-4 md:p-7"><div className="mx-auto max-w-6xl space-y-4"><section className="flex items-center justify-between rounded-3xl border border-amber-400/20 bg-slate-900/70 p-5"><div><p className="text-xs font-black uppercase tracking-[.25em] text-amber-300">Leo · Live Sales Inbox</p><h1 className="mt-1 text-2xl font-black">WhatsApp</h1><p className="mt-1 text-xs text-slate-400">Real customer chat · AI + human replies · 24-hour workspace</p></div><div className="text-4xl">🦁</div></section><section className="grid grid-cols-4 gap-2"><Kpi label="Messages" value={stats.inbound}/><Kpi label="Replies" value={stats.outbound}/><Kpi label="Leads" value={stats.leads}/><Kpi label="Qualified" value={stats.qualified}/></section>
 <section className="overflow-hidden rounded-3xl border border-slate-800 bg-slate-900/70"><div className="flex h-[68vh] min-h-[520px] flex-col"><div className="flex items-center gap-3 border-b border-slate-800 bg-slate-900 px-5 py-4"><div className="grid h-10 w-10 place-items-center rounded-full bg-emerald-500/15 text-emerald-300"><MessageCircle size={20}/></div><div><p className="font-black">Customer chat</p><p className="text-xs text-emerald-400">● Live WhatsApp · Vercel Native</p></div></div>
 <div className="flex-1 overflow-y-auto bg-[radial-gradient(circle_at_top,#132033,transparent_45%)] px-4 py-5 md:px-8">{chat.map(m=><div key={m.id} className={`mb-2 flex ${m.direction==="outbound"?"justify-end":"justify-start"}`}><div className={`max-w-[78%] rounded-2xl px-4 py-2.5 text-sm shadow ${m.direction==="outbound"?"rounded-br-md bg-emerald-700 text-white":"rounded-bl-md bg-slate-800 text-slate-100"}`}><p className="whitespace-pre-wrap break-words">{m.message}</p><div className="mt-1 flex items-center justify-end gap-2 text-[10px] opacity-60"><span>{new Date(m.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</span>{m.direction==="outbound"&&<span>{m.ai_generated?"Leo":"Human"} ✓</span>}</div></div></div>)}{!chat.length&&<div className="grid h-full place-items-center text-sm text-slate-500">Waiting for a WhatsApp customer message…</div>}<div ref={bottom}/></div>
 <div className="border-t border-slate-800 bg-slate-900 p-3"><input ref={fileInput} type="file" className="hidden" accept="image/*,video/*,audio/*,.pdf,.doc,.docx,.xls,.xlsx,.txt" onChange={e=>setFile(e.target.files?.[0]||null)}/>{file&&<div className="mb-2 flex items-center justify-between rounded-xl bg-slate-800 px-3 py-2 text-xs"><span className="truncate">📎 {file.name}</span><button onClick={()=>{setFile(null);if(fileInput.current)fileInput.current.value=""}} className="ml-3 text-slate-400">✕</button></div>}{error&&<p className="mb-2 text-xs text-rose-400">{error}</p>}<div className="flex items-end gap-2"><button onClick={()=>fileInput.current?.click()} className="grid h-11 w-11 shrink-0 place-items-center rounded-full text-slate-300 hover:bg-slate-800" title="Attach image, video or file"><Paperclip size={21}/></button><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} rows={1} placeholder="Message customer…" className="max-h-28 min-h-11 flex-1 resize-none rounded-2xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm outline-none focus:border-emerald-500"/><button onClick={send} disabled={sending||(!draft.trim()&&!file)||!activeCustomer} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-emerald-600 text-white disabled:opacity-40">{sending?<Loader2 className="animate-spin" size={19}/>:<Send size={19}/>}</button></div></div></div></section></div></main></div></div>}
function Kpi({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-3"><p className="text-[10px] uppercase tracking-wide text-slate-500">{label} · 24h</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
