"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Archive, Boxes, ChefHat, ImagePlus, Loader2, PackagePlus, Pencil, Plus, RefreshCw, Search, ShoppingCart, Store, Truck, WalletCards, Gauge, WandSparkles } from "lucide-react";
import LegacyPosWorkspace from "./PosWorkspace";

type Row = Record<string, any>;
type Data = { products: Row[]; stock: Record<string,number>; categories: Row[]; units: Row[]; branches: Row[]; suppliers: Row[]; recipes: Row[]; recipeItems: Row[]; purchases: Row[]; purchaseItems: Row[]; orders: Row[]; orderItems: Row[]; payments: Row[]; expenses: Row[]; summary:any; company?:Row };
const empty:Data={products:[],stock:{},categories:[],units:[],branches:[],suppliers:[],recipes:[],recipeItems:[],purchases:[],purchaseItems:[],orders:[],orderItems:[],payments:[],expenses:[],summary:{}};
const nav = [["terminal","POS",ShoppingCart],["products","Products",Store],["inventory","Inventory",Boxes],["recipes","Recipes",ChefHat],["suppliers","Suppliers",Truck],["purchases","Purchases",PackagePlus],["expenses","Expenses",WalletCards],["reports","Reports",Gauge]] as const;
const money=(n:any)=>new Intl.NumberFormat("en-SA",{style:"currency",currency:"SAR",maximumFractionDigits:2}).format(Number(n||0));
const blank=()=>({id:"",name:"",sku:"",barcode:"",category_name:"",unit_code:"PCS",product_type:"stock",b2c_price:0,b2b_price:0,cost_price:0,tax_enabled:false,tax_rate:15,min_stock:0,track_stock:true,image_url:"",description:"",active:true});

export default function PosCommerceWorkspace(){
  const [tab,setTab]=useState("products");
  const [data,setData]=useState<Data>(empty);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
  const [form,setForm]=useState<any>(blank());
  const [query,setQuery]=useState(""),[type,setType]=useState("all"),[category,setCategory]=useState("all");
  const [codeMode,setCodeMode]=useState<"auto"|"manual">("auto");
  const fileRef=useRef<HTMLInputElement|null>(null);

  async function load(){setLoading(true);try{const r=await fetch("/api/pos",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"POS load failed");setData(j)}catch(e){setNotice(e instanceof Error?e.message:"POS load failed")}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);

  const categories=useMemo(()=>Array.from(new Set(data.products.map(p=>String(p.category_name||"").trim()).filter(Boolean))).sort(),[data.products]);
  const filtered=data.products.filter(p=>p.active!==false&&(!query||`${p.name} ${p.sku||""} ${p.barcode||""} ${p.category_name||""}`.toLowerCase().includes(query.toLowerCase()))&&(type==="all"||p.product_type===type)&&(category==="all"||p.category_name===category));

  function generateCodes(){const d=new Date();const ymd=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}`;setForm((f:any)=>({...f,sku:`PRD-${ymd}-${Math.floor(1000+Math.random()*9000)}`,barcode:`6281${String(Date.now()).slice(-8)}${Math.floor(Math.random()*10)}`}));}

  async function upload(file:File){setBusy(true);setNotice("");try{const fd=new FormData();fd.append("file",file);const r=await fetch("/api/pos/product-image",{method:"POST",body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error||"Image upload failed");setForm((f:any)=>({...f,image_url:j.url}));setNotice("Image optimized and uploaded successfully")}catch(e){setNotice(e instanceof Error?e.message:"Image upload failed")}finally{setBusy(false)}}

  async function save(){setBusy(true);setNotice("");try{const payload={...form};if(codeMode==="auto"&&(!payload.sku||!payload.barcode)){const d=new Date();const ymd=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}`;payload.sku=payload.sku||`PRD-${ymd}-${Math.floor(1000+Math.random()*9000)}`;payload.barcode=payload.barcode||`6281${String(Date.now()).slice(-8)}${Math.floor(Math.random()*10)}`;}const r=await fetch("/api/pos/product",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not save product");setNotice(form.id?"Product updated":"Product added successfully");setForm(blank());setCodeMode("auto");await load()}catch(e){setNotice(e instanceof Error?e.message:"Could not save product")}finally{setBusy(false)}}
  async function archive(id:string){if(!confirm("Archive this product?"))return;setBusy(true);try{const r=await fetch("/api/pos/product",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not archive product");await load()}catch(e){setNotice(e instanceof Error?e.message:"Could not archive product")}finally{setBusy(false)}}
  function edit(p:Row){const unit=data.units.find(u=>u.id===p.unit_id);const symbol=String(unit?.symbol||"pcs").toLowerCase();const unitCode=symbol==="g"?"GRAM":symbol==="kg"?"KG":symbol==="l"?"LTR":"PCS";setForm({...blank(),...p,unit_code:unitCode,b2c_price:Number(p.b2c_price??p.sale_price??0),b2b_price:Number(p.b2b_price||0),tax_enabled:Boolean(p.tax_enabled||Number(p.tax_rate)>0)});setCodeMode("manual");window.scrollTo({top:0,behavior:"smooth"})}

  if(tab!=="products") return <div className="space-y-4"><TopNav tab={tab} setTab={setTab}/><LegacyPosWorkspace/></div>;
  return <div className="space-y-5">
    <TopNav tab={tab} setTab={setTab}/>
    <section className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex items-center gap-3"><div className="rounded-2xl bg-cyan-400/10 p-3 text-cyan-300"><Store/></div><div><h1 className="text-3xl font-black">Products</h1><p className="text-sm text-slate-400">Manage products and services for any business activity.</p></div></div><div className="flex flex-wrap gap-2"><div className="relative min-w-64"><Search size={16} className="absolute left-3 top-3 text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products..." className="w-full rounded-xl border border-slate-700 bg-slate-950 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-cyan-400"/></div><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm"><option value="all">All Types</option><option value="stock">Stock</option><option value="service">Service</option><option value="prepared">Prepared / Recipe</option><option value="bundle">Bundle</option></select><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm"><option value="all">All Categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><button onClick={()=>{setForm(blank());setCodeMode("auto")}} className="inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-4 py-2.5 text-sm font-black text-slate-950"><Plus size={16}/> Add Product</button></div></section>
    {notice&&<div className="rounded-xl border border-cyan-400/25 bg-cyan-400/5 px-4 py-3 text-sm text-cyan-100">{notice}</div>}
    <div className="grid gap-5 2xl:grid-cols-[590px_1fr]">
      <section className="rounded-3xl border border-slate-800 bg-slate-900/65 p-5 shadow-2xl"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Add / Edit Product</h2><p className="mt-1 text-xs text-slate-500">Universal catalog for retail, restaurants, services and more.</p></div><div className="flex rounded-xl border border-slate-700 bg-slate-950 p-1 text-xs"><button onClick={()=>{setCodeMode("auto");generateCodes()}} className={`rounded-lg px-3 py-2 font-black ${codeMode==="auto"?"bg-cyan-500 text-slate-950":"text-slate-400"}`}><WandSparkles size={13} className="mr-1 inline"/>Generate Codes</button><button onClick={()=>setCodeMode("manual")} className={`rounded-lg px-3 py-2 font-black ${codeMode==="manual"?"bg-slate-800 text-white":"text-slate-400"}`}>Use My Own Codes</button></div></div>
        <div className="grid gap-4">
          <Field label="Product / Service Name" required><Input value={form.name} onChange={(v)=>setForm({...form,name:v})} placeholder="e.g. Margherita Pizza / Cleaning Service"/></Field>
          <div className="grid gap-3 md:grid-cols-2"><Field label="SKU / Item Code"><Input value={form.sku} onChange={(v)=>setForm({...form,sku:v})} placeholder={codeMode==="auto"?"Auto-generated":"Enter your code"}/></Field><Field label="Barcode"><Input value={form.barcode} onChange={(v)=>setForm({...form,barcode:v})} placeholder={codeMode==="auto"?"Auto-generated":"Enter barcode"}/></Field></div>
          <div className="grid gap-3 md:grid-cols-3"><Field label="Category" required><Input value={form.category_name} onChange={(v)=>setForm({...form,category_name:v})} placeholder="Type any category"/></Field><Field label="Unit" required><Select value={form.unit_code} onChange={(v)=>setForm({...form,unit_code:v})} options={[["GRAM","GRAM (g)"],["KG","KG (kg)"],["PCS","PCS (piece)"],["LTR","LTR (liter)"]]}/></Field><Field label="Product Type" required><Select value={form.product_type} onChange={(v)=>setForm({...form,product_type:v,track_stock:v!=="service"})} options={[["stock","Product (Stock Item)"],["service","Service"],["prepared","Prepared / Recipe"],["bundle","Bundle"]]}/></Field></div>
          <div className="grid gap-3 md:grid-cols-3"><Field label="B2C Price (Retail)" required><Num value={form.b2c_price} onChange={(v)=>setForm({...form,b2c_price:v})}/></Field><Field label="B2B Price (Wholesale)"><Num value={form.b2b_price} onChange={(v)=>setForm({...form,b2b_price:v})}/></Field><Field label="Cost Price"><Num value={form.cost_price} onChange={(v)=>setForm({...form,cost_price:v})}/></Field></div>
          <div className="grid gap-3 md:grid-cols-3"><div className="rounded-2xl border border-slate-800 bg-slate-950 p-3"><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.tax_enabled} onChange={e=>setForm({...form,tax_enabled:e.target.checked})}/> Apply Tax</label><p className="mt-1 text-[11px] text-slate-500">Leave unchecked for non-tax businesses.</p></div><Field label="Tax Rate (%)"><Num disabled={!form.tax_enabled} value={form.tax_rate} onChange={(v)=>setForm({...form,tax_rate:v})}/></Field><Field label="Minimum Stock"><Num value={form.min_stock} onChange={(v)=>setForm({...form,min_stock:v})}/></Field></div>
          <div className="grid gap-4 md:grid-cols-2"><Field label="Product Image"><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/><button type="button" onClick={()=>fileRef.current?.click()} className="grid min-h-40 w-full place-items-center overflow-hidden rounded-2xl border border-dashed border-slate-700 bg-slate-950 text-slate-400 hover:border-cyan-400">{form.image_url?<img src={form.image_url} alt="Product" className="h-40 w-full object-cover"/>:<div className="text-center"><ImagePlus className="mx-auto mb-2"/><p className="font-bold">Click to upload image</p><p className="mt-1 text-[11px]">PNG, JPG, WebP · auto resize & optimize</p></div>}</button></Field><Field label="Description"><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Write a product description..." className="min-h-40 w-full resize-none rounded-2xl border border-slate-700 bg-slate-950 p-3 text-sm outline-none focus:border-cyan-400"/></Field></div>
          <div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-800 pt-4"><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/><span><b>Active</b><span className="ml-2 text-xs text-slate-500">Product available for use</span></span></label><div className="flex gap-2"><button onClick={()=>setForm(blank())} className="rounded-xl border border-slate-700 px-5 py-3 text-sm font-bold">Clear</button><button disabled={busy} onClick={save} className="rounded-xl bg-cyan-400 px-6 py-3 text-sm font-black text-slate-950 disabled:opacity-50">{busy?<Loader2 className="animate-spin" size={17}/>:form.id?"Update Product":"Save Product"}</button></div></div>
        </div>
      </section>
      <section className="overflow-hidden rounded-3xl border border-slate-800 bg-slate-900/65 shadow-2xl"><div className="flex items-center justify-between border-b border-slate-800 p-5"><div><h2 className="text-xl font-black">Product Catalog <span className="text-slate-500">({filtered.length} items)</span></h2><p className="mt-1 text-xs text-slate-500">B2C, B2B, stock and product images in one place.</p></div><button onClick={load} className="rounded-xl border border-slate-700 p-2 text-slate-400"><RefreshCw size={16}/></button></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-slate-950/70 text-slate-500"><tr><th className="p-4">Image</th><th>Name</th><th>SKU</th><th>Category</th><th>Unit</th><th>B2C Price</th><th>B2B Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(p=>{const unit=data.units.find(u=>u.id===p.unit_id);return <tr key={p.id} className="border-t border-slate-800 hover:bg-slate-950/40"><td className="p-3">{p.image_url?<img src={p.image_url} alt="" className="h-12 w-12 rounded-xl object-cover"/>:<div className="grid h-12 w-12 place-items-center rounded-xl bg-slate-800 text-slate-600"><ImagePlus size={18}/></div>}</td><td><p className="font-bold text-white">{p.name}</p><p className="max-w-48 truncate text-[10px] text-slate-500">{p.description||p.product_type}</p></td><td>{p.sku||"—"}</td><td>{p.category_name||"General"}</td><td>{unit?.symbol||"pcs"}</td><td>{money(p.b2c_price??p.sale_price)}</td><td>{money(p.b2b_price)}</td><td>{p.track_stock?Number(data.stock[p.id]||0).toFixed(2):"—"}</td><td><span className="rounded-full bg-emerald-500/10 px-3 py-1 font-bold text-emerald-300">Active</span></td><td><div className="flex gap-2"><button onClick={()=>edit(p)} className="rounded-lg bg-cyan-500/10 p-2 text-cyan-300"><Pencil size={14}/></button><button onClick={()=>archive(p.id)} className="rounded-lg bg-rose-500/10 p-2 text-rose-300"><Archive size={14}/></button></div></td></tr>})}</tbody></table>{!loading&&!filtered.length&&<div className="grid min-h-64 place-items-center text-sm text-slate-600">No products yet. Add your first product.</div>}{loading&&<div className="grid min-h-64 place-items-center text-slate-500"><Loader2 className="animate-spin"/></div>}</div></section>
    </div>
  </div>
}

function TopNav({tab,setTab}:{tab:string;setTab:(v:string)=>void}){return <div className="flex gap-2 overflow-x-auto rounded-2xl border border-slate-800 bg-slate-900/60 p-2">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex shrink-0 items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-black ${tab===id?"bg-cyan-500 text-slate-950":"text-slate-400 hover:bg-slate-800"}`}><Icon size={15}/>{label}</button>)}</div>}
function Field({label,required,children}:{label:string;required?:boolean;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-300">{label}{required&&<span className="text-rose-400"> *</span>}</span>{children}</label>}
function Input({value,onChange,placeholder}:{value:any;onChange:(v:string)=>void;placeholder?:string}){return <input value={value??""} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm outline-none focus:border-cyan-400"/>}
function Num({value,onChange,disabled=false}:{value:any;onChange:(v:number)=>void;disabled?:boolean}){return <input type="number" min="0" step="0.01" disabled={disabled} value={value??0} onChange={e=>onChange(Number(e.target.value||0))} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm outline-none focus:border-cyan-400 disabled:opacity-40"/>}
function Select({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:[string,string][]}){return <select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm outline-none focus:border-cyan-400">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}
