"use client";

import { useEffect, useMemo, useState } from "react";
import { ImageIcon, Search } from "lucide-react";

type Row = Record<string, any>;
type Data = { products:Row[]; stock:Record<string,number>; branches:Row[] };
type CartLine={product_id:string;name:string;quantity:number;unit_price:number;discount:number;tax_rate:number};
const money=(n:any)=>new Intl.NumberFormat("en-SA",{style:"currency",currency:"SAR",maximumFractionDigits:2}).format(Number(n||0));

export default function PosTerminalEnhanced({data,onRefresh}:{data:Data;onRefresh:()=>Promise<void>}){
 const [q,setQ]=useState(""),[cat,setCat]=useState("all"),[cart,setCart]=useState<CartLine[]>([]),[branch,setBranch]=useState(data.branches?.[0]?.id||""),[method,setMethod]=useState("cash"),[customer,setCustomer]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 useEffect(()=>{if(!branch&&data.branches?.[0])setBranch(data.branches[0].id)},[data.branches,branch]);
 const categories=useMemo(()=>Array.from(new Set((data.products||[]).map(p=>String(p.category_name||"").trim()).filter(Boolean))).sort((a,b)=>a.localeCompare(b)),[data.products]);
 const shown=(data.products||[]).filter(p=>p.active!==false&&(!q||`${p.name} ${p.sku||""} ${p.barcode||""} ${p.category_name||""} ${p.description||""}`.toLowerCase().includes(q.toLowerCase()))&&(cat==="all"||String(p.category_name||"")===cat));
 function add(p:Row){setCart(c=>{const x=c.find(i=>i.product_id===p.id);const price=Number(p.b2c_price??p.sale_price??0);const tax=p.tax_enabled===false?0:Number(p.tax_rate||0);return x?c.map(i=>i.product_id===p.id?{...i,quantity:i.quantity+1,unit_price:price,tax_rate:tax}:i):[...c,{product_id:p.id,name:p.name,quantity:1,unit_price:price,discount:0,tax_rate:tax}]})}
 const totals=useMemo(()=>cart.reduce((a,i)=>{const net=Math.max(0,i.quantity*i.unit_price-i.discount);return{sub:a.sub+net,tax:a.tax+net*i.tax_rate/100}},{sub:0,tax:0}),[cart]);
 async function checkout(){if(!cart.length)return;setBusy(true);setNotice("");try{const r=await fetch("/api/pos",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"sale.complete",branch_id:branch,payment_method:method,customer_name:customer,items:cart})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Sale failed");setCart([]);setCustomer("");setNotice("Sale completed successfully");await onRefresh()}catch(e){setNotice(e instanceof Error?e.message:"Sale failed")}finally{setBusy(false)}}
 return <div className="space-y-4">
  {notice&&<div className="rounded-xl border border-cyan-400/20 bg-cyan-400/5 px-4 py-3 text-sm text-cyan-100">{notice}</div>}
  <div className="grid gap-4 xl:grid-cols-[1.45fr_.55fr]">
   <section className="rounded-3xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="mb-4 text-xl font-black">Sales Terminal</h2>
    <div className="mb-4 grid gap-3 md:grid-cols-[1fr_260px]"><div className="relative"><Search className="absolute left-3 top-3 text-slate-600" size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, category, SKU or barcode" className="w-full rounded-xl border border-slate-700 bg-slate-950 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-cyan-500"/></div><select value={cat} onChange={e=>setCat(e.target.value)} className="rounded-xl border border-slate-700 bg-slate-950 px-3 text-sm"><option value="all">All categories ({data.products.filter(p=>p.active!==false).length})</option>{categories.map(c=><option key={c} value={c}>{c} ({data.products.filter(p=>p.active!==false&&String(p.category_name||"")===c).length})</option>)}</select></div>
    {categories.length>0&&<div className="mb-4 flex gap-2 overflow-x-auto pb-1"><button onClick={()=>setCat("all")} className={`shrink-0 rounded-full px-4 py-2 text-xs font-black ${cat==="all"?"bg-cyan-400 text-slate-950":"bg-slate-950 text-slate-400"}`}>All</button>{categories.map(c=><button key={c} onClick={()=>setCat(c)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-black ${cat===c?"bg-cyan-400 text-slate-950":"bg-slate-950 text-slate-400"}`}>{c}</button>)}</div>}
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{shown.map(p=><button key={p.id} onClick={()=>add(p)} className="group overflow-hidden rounded-2xl border border-slate-800 bg-slate-950 text-left transition hover:-translate-y-0.5 hover:border-cyan-500/50"><div className="relative aspect-[4/3] w-full overflow-hidden bg-slate-900">{p.image_url?<img src={p.image_url} alt={p.name} className="h-full w-full object-cover transition duration-300 group-hover:scale-105"/>:<div className="grid h-full place-items-center text-slate-700"><ImageIcon size={34}/></div>}<span className="absolute left-2 top-2 rounded-full bg-slate-950/85 px-2.5 py-1 text-[10px] font-bold text-cyan-200 backdrop-blur">{p.category_name||"General"}</span></div><div className="p-3"><p className="truncate font-black">{p.name}</p>{p.description&&<p className="mt-1 line-clamp-2 min-h-8 text-[10px] text-slate-500">{p.description}</p>}<div className="mt-3 flex items-end justify-between"><span className="text-lg font-black text-cyan-300">{money(p.b2c_price??p.sale_price)}</span><span className="text-[10px] text-slate-500">{p.track_stock?`Stock ${Number(data.stock[p.id]||0).toFixed(2)}`:"Service"}</span></div></div></button>)}</div>
    {!shown.length&&<div className="grid min-h-64 place-items-center text-sm text-slate-600">No products match this search or category.</div>}
   </section>
   <section className="rounded-3xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="mb-4 text-xl font-black">Current Sale</h2><div className="space-y-2">{cart.map(i=><div key={i.product_id} className="rounded-2xl bg-slate-950 p-3"><div className="flex justify-between gap-2"><p className="text-sm font-bold">{i.name}</p><button onClick={()=>setCart(c=>c.filter(x=>x.product_id!==i.product_id))} className="text-xs text-rose-400">Remove</button></div><div className="mt-2 grid grid-cols-3 gap-2"><input type="number" min=".01" step=".01" value={i.quantity} onChange={e=>setCart(c=>c.map(x=>x.product_id===i.product_id?{...x,quantity:Number(e.target.value||0)}:x))} className="rounded-lg border border-slate-800 bg-slate-900 px-2 py-2 text-xs"/><input type="number" value={i.unit_price} onChange={e=>setCart(c=>c.map(x=>x.product_id===i.product_id?{...x,unit_price:Number(e.target.value||0)}:x))} className="rounded-lg border border-slate-800 bg-slate-900 px-2 py-2 text-xs"/><input type="number" placeholder="Discount" value={i.discount} onChange={e=>setCart(c=>c.map(x=>x.product_id===i.product_id?{...x,discount:Number(e.target.value||0)}:x))} className="rounded-lg border border-slate-800 bg-slate-900 px-2 py-2 text-xs"/></div></div>)}{!cart.length&&<div className="grid min-h-44 place-items-center rounded-2xl border border-dashed border-slate-800 text-sm text-slate-600">Tap a product to start</div>}</div><div className="mt-4 space-y-2 border-t border-slate-800 pt-4"><div className="flex justify-between text-sm text-slate-400"><span>Subtotal</span><span>{money(totals.sub)}</span></div><div className="flex justify-between text-sm text-slate-400"><span>Tax</span><span>{money(totals.tax)}</span></div><div className="flex justify-between text-xl font-black"><span>Total</span><span className="text-cyan-300">{money(totals.sub+totals.tax)}</span></div><select value={branch} onChange={e=>setBranch(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm">{data.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Customer (optional)" className="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm"/><select value={method} onChange={e=>setMethod(e.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm"><option value="cash">Cash</option><option value="card">Card</option><option value="bank">Bank</option><option value="online">Online</option><option value="credit">Credit</option></select><button disabled={busy||!cart.length} onClick={checkout} className="w-full rounded-xl bg-cyan-400 px-4 py-3 text-sm font-black text-slate-950 disabled:opacity-40">{busy?"Processing...":"Complete & Pay"}</button></div></section>
  </div>
 </div>
}
