"use client";
import { useEffect, useMemo, useState } from "react";

const box="rounded-2xl border border-slate-800 bg-slate-900 p-5";
const input="w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 outline-none focus:border-cyan-400";
const btn="rounded-xl bg-cyan-400 px-4 py-2.5 font-black text-slate-950 disabled:opacity-40";

export default function RecipeCashierPublisher(){
 const[prod,setProd]=useState<any>({recipes:[]}),[sales,setSales]=useState<any>({products:[],categories:[]}),[selected,setSelected]=useState<any>(null),[form,setForm]=useState<any>({price:0,category_id:'',tax_enabled:false,tax_rate:15}),[busy,setBusy]=useState(false);
 async function load(){const [a,b]=await Promise.all([fetch('/api/production',{cache:'no-store'}),fetch('/api/sales',{cache:'no-store'})]);if(a.ok)setProd(await a.json());if(b.ok)setSales(await b.json())}
 useEffect(()=>{load()},[]);
 const published=useMemo(()=>new Map((sales.products||[]).filter((p:any)=>p.recipe_id).map((p:any)=>[p.recipe_id,p])),[sales.products]);
 async function publish(){if(!selected)return;setBusy(true);const r=await fetch('/api/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'product',data:{name:selected.name,recipe_id:selected.id,category_id:form.category_id||null,price:Number(form.price||0),tax_enabled:!!form.tax_enabled,tax_rate:Number(form.tax_rate||0),show_on_cashier:true,track_inventory:false,sale_unit:'piece'}})});const j=await r.json();setBusy(false);if(!r.ok)return alert(j.error||'Could not publish recipe');setSelected(null);await load()}
 return <section className={box}>
  <div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div><h2 className="text-xl font-black">Cashier Publishing</h2><p className="text-sm text-slate-400">Connect a main recipe directly to a sellable Cashier product. The same item appears in both Hospitality and Retail cashier interfaces.</p></div></div>
  <div className="grid gap-2">{(prod.recipes||[]).map((r:any)=>{const p:any=published.get(r.id);return <div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-800 bg-slate-950 p-4"><div><b>{r.recipe_code?`${r.recipe_code} · `:''}{r.name}</b><small className="block text-slate-500">Yield {r.yield_qty||1} · Main recipe</small></div>{p?<span className="rounded-full bg-emerald-500/15 px-3 py-2 text-xs font-black text-emerald-300">VISIBLE ON CASHIER · {Number(p.price||0).toFixed(2)}</span>:<button className={btn} onClick={()=>{setSelected(r);setForm({price:0,category_id:'',tax_enabled:false,tax_rate:15})}}>+ Add to Cashier</button>}</div>})}</div>
  {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4"><div className="w-full max-w-lg rounded-3xl border border-slate-700 bg-slate-900 p-6"><div className="mb-4 flex justify-between"><div><h3 className="text-xl font-black">Add Recipe to Cashier</h3><p className="text-sm text-slate-400">{selected.name}</p></div><button onClick={()=>setSelected(null)}>✕</button></div><div className="space-y-3"><input className={input} type="number" min="0" step="0.01" placeholder="Selling price" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><select className={input} value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})}><option value="">No category</option>{(sales.categories||[]).map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><label className="flex items-center gap-3 rounded-xl border border-slate-800 bg-slate-950 p-3"><input type="checkbox" checked={form.tax_enabled} onChange={e=>setForm({...form,tax_enabled:e.target.checked})}/><span className="font-bold">Enable tax</span></label>{form.tax_enabled&&<input className={input} type="number" min="0" max="100" value={form.tax_rate} onChange={e=>setForm({...form,tax_rate:e.target.value})}/>}<button disabled={busy||Number(form.price)<0} onClick={publish} className={`${btn} w-full`}>{busy?'Publishing...':'Publish to Cashier'}</button></div></div></div>}
 </section>
}
