"use client";
import{useEffect,useMemo,useRef,useState}from'react';
const panel='rounded-2xl border border-slate-800 bg-slate-900',btn='rounded-xl bg-cyan-400 px-4 py-3 font-black text-slate-950',ghost='rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 font-bold text-slate-300';
export default function SalesPosWorkspace(){
 const[d,S]=useState<any>({products:[],categories:[],orders:[],warehouses:[],shifts:[],settings:null}),[cat,C]=useState('all'),[cart,K]=useState<any[]>([]),[search,Q]=useState('');const ref=useRef<HTMLInputElement>(null);
 async function load(){const r=await fetch('/api/sales',{cache:'no-store'});if(r.ok)S(await r.json())}useEffect(()=>{load()},[]);
 const mode=d.settings?.cashier_mode||'retail',currency=d.settings?.currency||'SAR';
 const products=useMemo(()=>d.products.filter((p:any)=>p.show_on_cashier&&(cat==='all'||p.category_id===cat)&&(!search||`${p.name} ${p.sku||''} ${p.barcode||''}`.toLowerCase().includes(search.toLowerCase()))),[d.products,cat,search]);
 function add(p:any){K((old:any[])=>{const i=old.findIndex(x=>x.id===p.id);return i<0?[...old,{...p,quantity:1}]:old.map((x,n)=>n===i?{...x,quantity:x.quantity+1}:x)})}
 function qty(id:string,n:number){K((old:any[])=>old.map(x=>x.id===id?{...x,quantity:Math.max(0,x.quantity+n)}:x).filter(x=>x.quantity>0))}
 const subtotal=cart.reduce((a:number,x:any)=>a+Number(x.price)*x.quantity,0),tax=cart.reduce((a:number,x:any)=>a+(x.tax_enabled?Number(x.price)*x.quantity*Number(x.tax_rate||0)/100:0),0),total=subtotal+tax;
 async function checkout(method='cash'){if(!cart.length)return;const warehouse=d.settings?.default_warehouse_id||d.warehouses[0]?.id;if(!warehouse)return alert('Default warehouse is required');const shift=d.shifts.find((x:any)=>x.status==='open');const r=await fetch('/api/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'checkout',data:{shift_id:shift?.id||null,warehouse_id:warehouse,service_type:mode==='restaurant'?'dine_in':'retail',lines:cart.map(x=>({product_id:x.id,quantity:x.quantity,discount:0})),payments:[{payment_method:method,amount:total}]}})});const j=await r.json();if(!r.ok)return alert(j.error);K([]);Q('');load()}
 function scan(e:any){if(e.key!=='Enter')return;const code=search.trim();const p=d.products.find((x:any)=>x.barcode===code||x.sku===code);if(p){add(p);Q('')} }
 return <div className="min-h-[75vh] space-y-4">
  <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">Cashier</h1><p className="text-sm text-slate-400">{mode==='restaurant'?'Restaurant cashier':'Retail / Hypermarket cashier'}</p></div><div className="flex gap-2 text-sm"><span className={ghost}>Branch: {d.warehouses[0]?.name||'Main'}</span><span className={ghost}>Shift: {d.shifts.find((x:any)=>x.status==='open')?'OPEN':'—'}</span></div></header>
  <div className="grid min-h-[680px] gap-4 xl:grid-cols-[1fr_410px]">
   <main className={`${panel} p-4`}>
    <div className="mb-4 flex gap-2"><div className="relative flex-1"><input ref={ref} autoFocus value={search} onChange={e=>Q(e.target.value)} onKeyDown={scan} placeholder={mode==='retail'?'Scan barcode or search item...':'Search menu...'} className="w-full rounded-2xl border border-slate-700 bg-slate-950 px-5 py-4 text-lg outline-none focus:border-cyan-400"/></div>{mode==='restaurant'&&<><button className={ghost}>Dine In</button><button className={ghost}>Takeaway</button></>}</div>
    <div className="mb-4 flex gap-2 overflow-x-auto pb-1"><button onClick={()=>C('all')} className={cat==='all'?btn:ghost}>All</button>{d.categories.map((x:any)=><button key={x.id} onClick={()=>C(x.id)} className={cat===x.id?btn:ghost}>{x.name}</button>)}</div>
    <div className={`grid gap-3 ${mode==='restaurant'?'grid-cols-2 md:grid-cols-3 2xl:grid-cols-4':'grid-cols-2 md:grid-cols-3 2xl:grid-cols-5'}`}>{products.map((p:any)=><button key={p.id} onClick={()=>add(p)} className="group overflow-hidden rounded-2xl border border-slate-800 bg-slate-950 text-left hover:border-cyan-500/60">{mode==='restaurant'&&<div className="aspect-[16/10] bg-slate-800">{p.image_url?<img src={p.image_url} alt="" className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-3xl text-slate-600">◫</div>}</div>}<div className="p-4"><div className="font-black">{p.name}</div><div className="mt-1 text-xs text-slate-500">{p.barcode||p.sku}</div><div className="mt-2 text-lg font-black text-cyan-300">{Number(p.price).toFixed(2)} {currency}</div></div></button>)}</div>
   </main>
   <aside className={`${panel} flex flex-col overflow-hidden`}><div className="border-b border-slate-800 p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Current Order</h2><button onClick={()=>K([])} className="text-sm font-bold text-rose-400">Clear</button></div><p className="text-xs text-slate-500">{cart.reduce((a:number,x:any)=>a+x.quantity,0)} items</p></div>
    <div className="flex-1 overflow-y-auto p-4">{!cart.length&&<div className="flex h-full items-center justify-center text-center text-slate-600"><div><div className="text-5xl">▣</div><p className="mt-3 font-bold">No items yet</p><small>Scan or select a product</small></div></div>}{cart.map((x:any)=><div key={x.id} className="mb-2 rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="flex justify-between gap-2"><div><b>{x.name}</b><small className="block text-slate-500">{Number(x.price).toFixed(2)} {currency}</small></div><b>{(Number(x.price)*x.quantity).toFixed(2)}</b></div><div className="mt-3 flex items-center gap-3"><button onClick={()=>qty(x.id,-1)} className="h-9 w-9 rounded-lg bg-slate-800 font-black">−</button><b>{x.quantity}</b><button onClick={()=>qty(x.id,1)} className="h-9 w-9 rounded-lg bg-slate-800 font-black">+</button><button onClick={()=>K(c=>c.filter(y=>y.id!==x.id))} className="ml-auto text-xs font-bold text-rose-400">Remove</button></div></div>)}</div>
    <div className="border-t border-slate-800 bg-slate-950/50 p-5"><div className="space-y-2 text-sm"><div className="flex justify-between"><span className="text-slate-400">Subtotal</span><b>{subtotal.toFixed(2)}</b></div><div className="flex justify-between"><span className="text-slate-400">Tax</span><b>{tax.toFixed(2)}</b></div><div className="flex justify-between border-t border-slate-800 pt-3 text-2xl font-black"><span>Total</span><span className="text-cyan-300">{total.toFixed(2)} {currency}</span></div></div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>checkout('cash')} className={btn}>Cash</button><button onClick={()=>checkout('card')} className="rounded-xl bg-white px-4 py-3 font-black text-black">Card</button></div><div className="mt-2 grid grid-cols-3 gap-2"><button className={ghost}>Hold</button><button className={ghost}>Discount</button><button className={ghost}>Customer</button></div></div>
   </aside>
  </div>
 </div>
}