"use client";

import { useEffect, useMemo, useState } from "react";
import Sidebar from "@/app/components/Sidebar";
import DashboardHeader from "@/app/components/DashboardHeader";
import { useLanguage } from "@/app/components/LanguageProvider";
import { useTheme } from "@/app/components/ThemeProvider";
import { Bell, Building2, Check, Moon, Monitor, Plus, Save, Settings2, ShieldCheck, Sun, Trash2, UserPlus, UsersRound, Volume2 } from "lucide-react";

type Tab="company"|"notification"|"users"|"appearance";
type NotificationKey="new_lead"|"qualified_lead"|"quotation_request"|"negotiation_started"|"high_interest"|"new_customer_message"|"won_deal"|"lost_deal"|"event_soon"|"ai_handoff"|"automation_error"|"subscription_expiry"|"security_alert";
type NotificationPrefs=Record<NotificationKey,boolean>&{master:boolean;sound:boolean};
const defaults:NotificationPrefs={master:true,sound:true,new_lead:true,qualified_lead:true,quotation_request:true,negotiation_started:true,high_interest:true,new_customer_message:true,won_deal:true,lost_deal:false,event_soon:true,ai_handoff:true,automation_error:true,subscription_expiry:true,security_alert:true};
const notificationItems:{key:NotificationKey;en:string;ar:string;enDesc:string;arDesc:string}[]=[
 {key:"new_lead",en:"New lead received",ar:"وصول عميل محتمل جديد",enDesc:"Alert when a new lead enters AVERO.",arDesc:"تنبيه عند دخول عميل محتمل جديد إلى AVERO."},
 {key:"qualified_lead",en:"Lead becomes qualified",ar:"تحوّل العميل إلى مؤهل",enDesc:"Alert when AI or staff qualifies a lead.",arDesc:"تنبيه عندما يصنّف الذكاء الاصطناعي أو الفريق العميل كمؤهل."},
 {key:"quotation_request",en:"Quotation requested",ar:"طلب عرض سعر",enDesc:"Alert when a customer asks for price or proposal.",arDesc:"تنبيه عندما يطلب العميل سعراً أو عرضاً."},
 {key:"negotiation_started",en:"Negotiation starts",ar:"بدء التفاوض",enDesc:"Alert when the lead enters negotiation.",arDesc:"تنبيه عند انتقال العميل إلى مرحلة التفاوض."},
 {key:"high_interest",en:"High-interest lead",ar:"عميل عالي الاهتمام",enDesc:"Alert when interest becomes high.",arDesc:"تنبيه عندما يصبح مستوى الاهتمام مرتفعاً."},
 {key:"new_customer_message",en:"New customer message",ar:"رسالة جديدة من العميل",enDesc:"Alert for new WhatsApp/customer replies.",arDesc:"تنبيه عند وصول رد أو رسالة جديدة من العميل."},
 {key:"won_deal",en:"Deal won / booking confirmed",ar:"تم الفوز بالصفقة أو تأكيد الحجز",enDesc:"Alert immediately when a deal is confirmed.",arDesc:"تنبيه مباشر عند تأكيد الطلب أو الحجز."},
 {key:"lost_deal",en:"Deal lost / cancelled",ar:"خسارة أو إلغاء الصفقة",enDesc:"Alert when a lead declines or cancels.",arDesc:"تنبيه عندما يرفض العميل أو يلغي."},
 {key:"event_soon",en:"Upcoming event reminder",ar:"تذكير بموعد قريب",enDesc:"Alert for upcoming booked dates.",arDesc:"تنبيه قبل المواعيد والحجوزات القادمة."},
 {key:"ai_handoff",en:"AI needs human assistance",ar:"الذكاء الاصطناعي يحتاج تدخّل بشري",enDesc:"Alert when the agent needs a person.",arDesc:"تنبيه عندما يحتاج الوكيل إلى تدخل بشري."},
 {key:"automation_error",en:"Integration error",ar:"خطأ في الربط أو الأتمتة",enDesc:"Alert when WhatsApp, an API or integration fails.",arDesc:"تنبيه عند فشل واتساب أو API أو أي تكامل."},
 {key:"subscription_expiry",en:"Subscription or feature expiry",ar:"انتهاء اشتراك أو ميزة",enDesc:"Alert before a feature or subscription expires.",arDesc:"تنبيه قبل انتهاء اشتراك أو ميزة."},
 {key:"security_alert",en:"Security & account alerts",ar:"تنبيهات الأمان والحساب",enDesc:"Important account and permission events.",arDesc:"تنبيهات مهمة للحساب والصلاحيات والأمان."}
];
const input="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-400";
const card="rounded-3xl border border-slate-800 bg-slate-900/55";

export default function SettingsPage(){
 const {language}=useLanguage();const ar=language==="ar";const {theme,setTheme}=useTheme();
 const [tab,setTab]=useState<Tab>("company"),[prefs,setPrefs]=useState<NotificationPrefs>(defaults),[syncing,setSyncing]=useState(true),[saved,setSaved]=useState(false);
 const [companyData,setCompanyData]=useState<any>(null),[company,setCompany]=useState<any>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [cert,setCert]=useState({name:"",issuer:"",certificate_number:"",issued_at:"",expires_at:""});
 const [newUser,setNewUser]=useState({full_name:"",email:"",temporary_password:"",role:"user",permissions:[] as string[]});

 async function loadCompany(){const r=await fetch('/api/company-settings',{cache:'no-store'});const j=await r.json();if(r.ok){setCompanyData(j);setCompany(j.company||{})}else setMessage(j.error||'Could not load company settings')}
 useEffect(()=>{loadCompany();(async()=>{try{const res=await fetch('/api/settings',{cache:'no-store'});if(!res.ok)return;const data=await res.json();if(data.theme)setTheme(data.theme);setPrefs({...defaults,...(data.notification_prefs||{}),master:data.notification_master??true,sound:data.notification_sound??true})}finally{setSyncing(false)}})()},[setTheme]);
 const savePrefs=async(body:Record<string,unknown>)=>{await fetch('/api/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setSaved(true);setTimeout(()=>setSaved(false),1200)};
 const updateNotification=(key:keyof NotificationPrefs,value:boolean)=>setPrefs(prev=>{const next={...prev,[key]:value};const notification_prefs=Object.fromEntries(notificationItems.map(i=>[i.key,next[i.key]]));savePrefs({notification_master:next.master,notification_sound:next.sound,notification_prefs});return next});
 const chooseTheme=(value:"dark"|"light"|"system")=>{setTheme(value);savePrefs({theme:value})};
 async function api(method:string,body:any){setBusy(true);setMessage('');const r=await fetch('/api/company-settings',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();setBusy(false);if(!r.ok){setMessage(j.error||'Action failed');return null}return j}
 async function saveCompany(){const j=await api('PATCH',{kind:'company',data:company});if(j){setMessage(ar?'تم حفظ معلومات الشركة':'Company information saved');loadCompany()}}
 async function addCertificate(){const j=await api('POST',{kind:'add_certificate',data:cert});if(j){setCert({name:"",issuer:"",certificate_number:"",issued_at:"",expires_at:""});setMessage(ar?'تمت إضافة الشهادة':'Certificate added');loadCompany()}}
 async function removeCertificate(id:string){const j=await api('POST',{kind:'remove_certificate',data:{id}});if(j)loadCompany()}
 async function createUser(){const j=await api('POST',{kind:'create_user',data:newUser});if(j){setNewUser({full_name:"",email:"",temporary_password:"",role:"user",permissions:[]});setMessage(ar?'تمت إضافة المستخدم':'User added');loadCompany()}}
 async function saveUser(user:any){const j=await api('PATCH',{kind:'user_access',data:{user_id:user.user_id,role:user.role,permissions:user.permissions}});if(j){setMessage(ar?'تم تحديث صلاحيات المستخدم':'User access updated');loadCompany()}}
 function patchUser(id:string,patch:any){setCompanyData((prev:any)=>({...prev,users:prev.users.map((u:any)=>u.user_id===id?{...u,...patch}:u)}))}
 const permissionGroups=useMemo(()=>{const groups:Record<string,any[]>={};for(const p of companyData?.permissions||[]){const group=String(p.key).split('.')[0];(groups[group] ||= []).push(p)}return groups},[companyData]);
 const tabs=[{key:'company' as Tab,icon:Building2,en:'Company Information',ar:'معلومات الشركة'},{key:'notification' as Tab,icon:Bell,en:'Notification',ar:'التنبيهات'},{key:'users' as Tab,icon:UsersRound,en:'Users & Permissions',ar:'المستخدمون والصلاحيات'},{key:'appearance' as Tab,icon:Settings2,en:'Appearance',ar:'المظهر'}];

 return <div className="min-h-screen bg-slate-950 text-white"><Sidebar/><div className="ml-64 flex min-h-screen flex-col"><DashboardHeader/><main className="flex-1 px-6 py-7"><div className="mx-auto max-w-7xl space-y-6">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs font-black uppercase tracking-[.2em] text-cyan-400">AVERO SETTINGS</div><h1 className="mt-2 text-3xl font-black">{ar?'إعدادات الشركة':'Company Settings'}</h1><p className="mt-2 text-sm text-slate-400">{ar?'بيانات المنشأة، التنبيهات، المستخدمون، والصلاحيات — بعيداً عن الملف الشخصي.':'Company data, notifications, users and access — separate from personal Profile.'}</p></div>{(saved||syncing)&&<div className="rounded-full border border-emerald-500/20 bg-emerald-500/10 px-4 py-2 text-xs text-emerald-300">{syncing?(ar?'جارٍ المزامنة':'Syncing'):(ar?'تم الحفظ':'Saved')}</div>}</div>
  <div className="flex flex-wrap gap-2 rounded-2xl border border-slate-800 bg-slate-900/55 p-2">{tabs.map(t=>{const Icon=t.icon;return <button key={t.key} onClick={()=>setTab(t.key)} className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold ${tab===t.key?'bg-cyan-400 text-slate-950':'text-slate-400 hover:bg-slate-800 hover:text-white'}`}><Icon size={16}/>{ar?t.ar:t.en}</button>})}</div>
  {message&&<div className="rounded-2xl border border-cyan-500/20 bg-cyan-500/5 px-4 py-3 text-sm font-bold text-cyan-200">{message}</div>}

  {tab==='company'&&<div className="space-y-6">
   <section className={`${card} p-6`}><div className="mb-5"><h2 className="text-xl font-black">{ar?'الهوية القانونية والتجارية':'Legal & Business Identity'}</h2><p className="mt-1 text-sm text-slate-500">{ar?'هذه هي بيانات الشركة الأساسية التي تستخدمها AVERO والتكاملات.':'This is the company source of truth used by AVERO and connected apps.'}</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
    <Field label={ar?'اسم الشركة':'Company Name'}><input className={input} value={company.name||''} onChange={e=>setCompany({...company,name:e.target.value})}/></Field>
    <Field label={ar?'البريد الإلكتروني للشركة':'Company Email'}><input className={input} type="email" value={company.email||''} onChange={e=>setCompany({...company,email:e.target.value})}/></Field>
    <Field label={ar?'الهاتف':'Phone'}><input className={input} value={company.phone||''} onChange={e=>setCompany({...company,phone:e.target.value})}/></Field>
    <Field label={ar?'الرقم الموحد للهاتف':'Unified Phone Number'}><input className={input} value={company.unified_phone||''} onChange={e=>setCompany({...company,unified_phone:e.target.value})}/></Field>
    <Field label={ar?'الرقم الضريبي':'VAT Number'}><input className={input} maxLength={15} placeholder="3xxxxxxxxxxxxx3" value={company.vat_number||''} onChange={e=>setCompany({...company,vat_number:e.target.value.replace(/\D/g,'')})}/></Field>
    <Field label={ar?'رقم السجل التجاري':'Commercial Registration'}><input className={input} value={company.commercial_registration_number||''} onChange={e=>setCompany({...company,commercial_registration_number:e.target.value})}/></Field>
    <Field label={ar?'رخصة البلدية':'Municipality License'}><input className={input} value={company.municipality_license_number||''} onChange={e=>setCompany({...company,municipality_license_number:e.target.value})}/></Field>
    <Field label={ar?'عدد الموظفين':'Employee Count'}><input className={input} type="number" min={0} step={1} value={company.employee_count??''} onChange={e=>setCompany({...company,employee_count:e.target.value})}/></Field>
    <Field label={ar?'النشاط':'Industry'}><input className={input} value={company.industry||company.activity_label||''} onChange={e=>setCompany({...company,industry:e.target.value})}/></Field>
    <Field label={ar?'المدينة':'City'}><input className={input} value={company.city||''} onChange={e=>setCompany({...company,city:e.target.value})}/></Field>
    <label className="md:col-span-2 xl:col-span-3"><span className="mb-1.5 block text-xs font-bold text-slate-400">{ar?'العنوان الوطني':'National Address'}</span><textarea rows={3} className={input} value={company.national_address||''} onChange={e=>setCompany({...company,national_address:e.target.value})}/></label>
   </div><button disabled={busy||!companyData?.capabilities?.manage_company} onClick={saveCompany} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 font-black text-slate-950 disabled:opacity-40"><Save size={17}/>{ar?'حفظ معلومات الشركة':'Save Company Information'}</button></section>
   <section className={`${card} p-6`}><div className="mb-5"><h2 className="text-xl font-black">{ar?'الشهادات والاعتمادات':'Certificates & Accreditations'}</h2><p className="mt-1 text-sm text-slate-500">{ar?'سجل الشهادات التي حصلت عليها المنشأة مع جهة الإصدار والتواريخ.':'Track company certificates with issuer and validity dates.'}</p></div>{companyData?.capabilities?.manage_company&&<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><input className={input} placeholder={ar?'اسم الشهادة':'Certificate name'} value={cert.name} onChange={e=>setCert({...cert,name:e.target.value})}/><input className={input} placeholder={ar?'جهة الإصدار':'Issuer'} value={cert.issuer} onChange={e=>setCert({...cert,issuer:e.target.value})}/><input className={input} placeholder={ar?'رقم الشهادة':'Certificate no.'} value={cert.certificate_number} onChange={e=>setCert({...cert,certificate_number:e.target.value})}/><input className={input} type="date" value={cert.expires_at} onChange={e=>setCert({...cert,expires_at:e.target.value})}/><button disabled={busy||!cert.name} onClick={addCertificate} className="rounded-xl bg-cyan-400 px-4 py-2.5 text-sm font-black text-slate-950 disabled:opacity-40"><Plus className="inline" size={16}/> {ar?'إضافة':'Add'}</button></div>}
    <div className="mt-4 space-y-2">{(companyData?.certificates||[]).length===0?<div className="rounded-2xl border border-slate-800 bg-slate-950 p-4 text-sm text-slate-500">{ar?'لا توجد شهادات مسجلة بعد.':'No certificates recorded yet.'}</div>:(companyData.certificates||[]).map((c:any)=><div key={c.id} className="flex items-center justify-between gap-4 rounded-2xl border border-slate-800 bg-slate-950/50 p-4"><div><b>{c.name}</b><p className="mt-1 text-xs text-slate-500">{[c.issuer,c.certificate_number,c.expires_at?`${ar?'تنتهي':'Expires'} ${c.expires_at}`:null].filter(Boolean).join(' · ')}</p></div>{companyData?.capabilities?.manage_company&&<button onClick={()=>removeCertificate(c.id)} className="rounded-lg p-2 text-rose-400 hover:bg-rose-500/10"><Trash2 size={16}/></button>}</div>)}</div>
   </section>
  </div>}

  {tab==='notification'&&<section className={`${card} p-6`}><div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 pb-5"><div className="flex items-start gap-3"><div className="rounded-xl bg-violet-500/10 p-2.5 text-violet-300"><Bell size={21}/></div><div><h2 className="text-xl font-black">{ar?'التنبيهات':'Notification'}</h2><p className="mt-1 text-sm text-slate-500">{ar?'اختر الأحداث التي تريد من AVERO أن ينبهك عليها.':'Choose which events AVERO should notify you about.'}</p></div></div><Toggle checked={prefs.master} onChange={v=>updateNotification('master',v)} label={ar?'كل التنبيهات':'All notifications'}/></div><div className={`mt-5 space-y-3 ${!prefs.master?'pointer-events-none opacity-45':''}`}>{notificationItems.map(item=><div key={item.key} className="flex items-center justify-between gap-4 rounded-2xl border border-slate-800 bg-slate-950/40 p-4"><div><h3 className="text-sm font-medium text-slate-200">{ar?item.ar:item.en}</h3><p className="mt-1 text-xs text-slate-500">{ar?item.arDesc:item.enDesc}</p></div><Toggle checked={prefs[item.key]} onChange={v=>updateNotification(item.key,v)}/></div>)}</div><div className="mt-5 flex items-center justify-between rounded-2xl border border-slate-800 bg-slate-950/40 p-4"><div className="flex items-start gap-3"><Volume2 size={18} className="mt-0.5 text-blue-400"/><div><h3 className="text-sm font-medium">{ar?'صوت التنبيهات':'Notification sound'}</h3><p className="mt-1 text-xs text-slate-500">{ar?'تشغيل صوت عند وصول تنبيه جديد.':'Play a sound when a new alert arrives.'}</p></div></div><Toggle checked={prefs.sound} onChange={v=>updateNotification('sound',v)}/></div></section>}

  {tab==='users'&&<div className="space-y-6">
   {companyData?.capabilities?.create_users&&<section className={`${card} p-6`}><div className="mb-5 flex items-start gap-3"><div className="rounded-xl bg-cyan-500/10 p-2.5 text-cyan-300"><UserPlus size={20}/></div><div><h2 className="text-xl font-black">{ar?'إضافة مستخدم':'Add User'}</h2><p className="mt-1 text-sm text-slate-500">{ar?'المستخدم يدخل على نفس الشركة ويجب تغيير كلمة المرور عند أول دخول.':'The user joins this company and must change the temporary password on first login.'}</p></div></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input className={input} placeholder={ar?'الاسم الكامل':'Full name'} value={newUser.full_name} onChange={e=>setNewUser({...newUser,full_name:e.target.value})}/><input className={input} type="email" placeholder="name@company.com" value={newUser.email} onChange={e=>setNewUser({...newUser,email:e.target.value})}/><input className={input} type="password" placeholder={ar?'كلمة مرور مؤقتة':'Temporary password'} value={newUser.temporary_password} onChange={e=>setNewUser({...newUser,temporary_password:e.target.value})}/><select className={input} value={newUser.role} onChange={e=>setNewUser({...newUser,role:e.target.value})}>{(companyData?.roles||[]).filter((r:any)=>r.key!=='super_admin'||companyData?.capabilities?.manage_permissions).map((r:any)=><option key={r.key} value={r.key}>{r.name}</option>)}</select></div><button disabled={busy||!newUser.email||newUser.temporary_password.length<8} onClick={createUser} className="mt-4 rounded-xl bg-cyan-400 px-5 py-3 text-sm font-black text-slate-950 disabled:opacity-40">{ar?'إضافة المستخدم':'Add User'}</button></section>}
   <section className={`${card} p-6`}><div className="mb-5"><h2 className="text-xl font-black">{ar?'المستخدمون والصلاحيات':'Users & Permissions'}</h2><p className="mt-1 text-sm text-slate-500">{ar?'Super Admin يملك صلاحية كاملة، ويمكن تعديل Admin وUser حسب الحاجة.':'Super Admin owns full company access; Admin and User access can be tailored.'}</p></div><div className="space-y-4">{(companyData?.users||[]).map((u:any)=>{const self=u.user_id===companyData.current_user_id;return <div key={u.user_id} className="rounded-2xl border border-slate-800 bg-slate-950/45 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2"><b>{u.full_name||u.email||u.username||'User'}</b>{self&&<span className="rounded-full bg-cyan-500/10 px-2 py-0.5 text-[10px] font-black text-cyan-300">YOU</span>}</div><p className="mt-1 text-xs text-slate-500">{u.email}</p></div><div className="flex items-center gap-2"><select disabled={self||!companyData?.capabilities?.manage_roles} className="rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-sm disabled:opacity-50" value={u.role} onChange={e=>patchUser(u.user_id,{role:e.target.value})}>{(companyData?.roles||[]).filter((r:any)=>r.key!=='super_admin'||companyData?.capabilities?.manage_permissions).map((r:any)=><option key={r.key} value={r.key}>{r.name}</option>)}</select>{!self&&(companyData?.capabilities?.manage_roles||companyData?.capabilities?.manage_permissions)&&<button disabled={busy} onClick={()=>saveUser(u)} className="rounded-xl bg-cyan-400 px-4 py-2 text-xs font-black text-slate-950">{ar?'حفظ':'Save'}</button>}</div></div>
     {companyData?.capabilities?.manage_permissions&&!self&&<details className="mt-4"><summary className="cursor-pointer text-sm font-bold text-cyan-300">{ar?'تعديل الصلاحيات التفصيلية':'Edit detailed permissions'}</summary><div className="mt-4 grid gap-4 lg:grid-cols-2">{Object.entries(permissionGroups).map(([group,perms]:any)=><div key={group} className="rounded-2xl border border-slate-800 bg-slate-900/50 p-4"><h4 className="mb-3 text-xs font-black uppercase tracking-[.16em] text-slate-500">{group}</h4><div className="space-y-2">{perms.map((p:any)=>{const checked=(u.permissions||[]).includes(p.key);return <label key={p.id} className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1" checked={checked} onChange={e=>patchUser(u.user_id,{permissions:e.target.checked?[...(u.permissions||[]),p.key]:(u.permissions||[]).filter((k:string)=>k!==p.key)})}/><span><b className="font-medium text-slate-200">{p.name}</b><span className="block text-[11px] text-slate-500">{p.key}</span></span></label>})}</div></div>)}</div></details>}
    </div>})}</div></section>
  </div>}

  {tab==='appearance'&&<section><div className="mb-4"><h2 className="text-xl font-black">{ar?'المظهر':'Appearance'}</h2><p className="mt-1 text-sm text-slate-500">{ar?'إعداد شخصي لكل مستخدم، وليس للشركة كلها.':'A personal preference for each user, not the whole company.'}</p></div><div className="grid gap-4 md:grid-cols-3"><ThemeCard active={theme==='dark'} onClick={()=>chooseTheme('dark')} icon={Moon} title={ar?'داكن':'Dark mode'}/><ThemeCard active={theme==='light'} onClick={()=>chooseTheme('light')} icon={Sun} title={ar?'فاتح':'Light mode'}/><ThemeCard active={theme==='system'} onClick={()=>chooseTheme('system')} icon={Monitor} title={ar?'حسب النظام':'System'}/></div></section>}
 </div></main></div></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-400">{label}</span>{children}</label>}
function Toggle({checked,onChange,label}:{checked:boolean;onChange:(v:boolean)=>void;label?:string}){return <button type="button" onClick={()=>onChange(!checked)} className="flex items-center gap-3"><span className="text-xs text-slate-400">{label}</span><span className={`relative h-7 w-12 rounded-full transition ${checked?'bg-emerald-500':'bg-slate-700'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${checked?'left-6':'left-1'}`}/></span></button>}
function ThemeCard({active,onClick,icon:Icon,title}:{active:boolean;onClick:()=>void;icon:any;title:string}){return <button onClick={onClick} className={`rounded-2xl border p-5 text-start ${active?'border-cyan-500 bg-cyan-500/10':'border-slate-800 bg-slate-900/55 hover:border-slate-700'}`}><div className="flex items-center justify-between"><Icon size={20} className="text-cyan-400"/>{active&&<Check size={18} className="text-emerald-400"/>}</div><h3 className="mt-4 font-bold">{title}</h3></button>}
