"use client";
import {useEffect,useMemo,useState} from "react";
const tabs=["Overview","Items & Prices","Purchases","Invoices","Payments","Statement","Documents","Performance"];
const box="rounded-2xl border border-slate-800 bg-slate-900";
const input="w-full rounded-xl border border-slate-800 bg-slate-950 px-3 py-2.5 text-sm outline-none focus:border-cyan-500";
export default function SupplierProfile({id,onBack}:{id:string,onBack:()=>void}){const [d,setD]=useState<any>(null),[tab,setTab]=useState("Overview"),[modal,setModal]=useState<string|null>(null),[f,setF]=useState<any>({});async function load(){const r=await fetch(`/api/suppliers/${id}`,{cache:"no-store"});setD(await r.json())}useEffect(()=>{load()},[id]);async function add(kind:string,data:any){const r=await fetch(`/api/suppliers/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,data})});const j=await r.json();if(!r.ok)return alert(j.error||"Save failed");setModal(null);setF({});load()}
 const tx=d?.transactions||[];const invoices=tx.filter((x:any)=>x.transaction_type==="invoice");const payments=tx.filter((x:any)=>x.transaction_type==="payment");const due=useMemo(()=>tx.reduce((a:number,x:any)=>a+(x.transaction_type==="invoice"?Number(x.amount)-Number(x.paid_amount||0):x.transaction_type==="credit_note"?-Number(x.amount):x.transaction_type==="payment"?-Number(x.amount):0),Number(d?.supplier?.opening_balance||0)),[d]);if(!d)return <p className="p-10 text-slate-500">Loading supplier...</p>;const s=d.supplier;
 const Empty=({text}:{text:string})=><div className={`${box} p-10 text-center text-slate-500`}>{text}</div>;
 return <div className="space-y-5"><button onClick={onBack} className="text-sm font-bold text-cyan-300">← All Suppliers</button><div className={`${box} p-6`}><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-3xl font-black">{s.preferred?"★ ":""}{s.name}</h1><span className="rounded-full bg-slate-800 px-3 py-1 text-xs capitalize">{s.status}</span></div><p className="mt-1 text-sm text-slate-500">{s.supplier_code} · {String(s.supplier_type).replaceAll("_"," ")} · {s.category||"Uncategorized"}</p></div><div className="grid grid-cols-3 gap-3 text-right"><div><p className="text-xs text-slate-500">Balance</p><b className={due>0?"text-amber-300":"text-emerald-300"}>{due.toFixed(2)} {s.currency}</b></div><div><p className="text-xs text-slate-500">Credit Limit</p><b>{Number(s.credit_limit||0).toFixed(2)}</b></div><div><p className="text-xs text-slate-500">Terms</p><b>{s.payment_terms_days?`${s.payment_terms_days} days`:"Cash"}</b></div></div></div></div>
 <div className="flex gap-2 overflow-x-auto">{tabs.map(x=><button key={x} onClick={()=>setTab(x)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm font-bold ${tab===x?"bg-cyan-400 text-slate-950":"border border-slate-800 bg-slate-900 text-slate-400"}`}>{x}</button>)}</div>
 {tab==="Overview"&&<div className="grid gap-4 lg:grid-cols-2"><div className={`${box} p-5`}><h3 className="font-black">Contact & Company</h3><div className="mt-4 grid grid-cols-2 gap-4 text-sm">{[["Contact",s.contact_person],["Phone",s.phone],["WhatsApp",s.whatsapp],["Email",s.email],["City",s.city],["Country",s.country],["Tax No.",s.tax_number],["CR No.",s.cr_number]].map(([a,b])=><div key={a}><p className="text-xs text-slate-500">{a}</p><p className="mt-1">{b||"—"}</p></div>)}</div></div><div className={`${box} p-5`}><h3 className="font-black">Commercial Terms</h3><div className="mt-4 grid grid-cols-2 gap-4 text-sm">{[["Lead Time",`${s.lead_time_days||0} days`],["Minimum Order",`${Number(s.minimum_order||0).toFixed(2)} ${s.currency}`],["Tax Registered",s.tax_enabled?"Yes":"No"],["Tax Rate",`${s.tax_rate||0}%`],["Contract Expiry",s.contract_expiry],["Price List Expiry",s.price_list_expiry]].map(([a,b])=><div key={a}><p className="text-xs text-slate-500">{a}</p><p className="mt-1">{b||"—"}</p></div>)}</div><p className="mt-5 text-xs text-slate-500">Internal Notes</p><p className="mt-1 text-sm">{s.notes||"No notes"}</p></div></div>}
 {tab==="Items & Prices"&&<section><div className="mb-3 flex justify-end"><button onClick={()=>setModal("item")} className="rounded-xl bg-cyan-400 px-4 py-2 text-sm font-black text-slate-950">+ Add Item</button></div>{d.items.length?<div className={box}>{d.items.map((x:any)=><div key={x.id} className="grid grid-cols-4 border-b border-slate-800 p-4 text-sm last:border-0"><b>{x.item_name}</b><span>{x.supplier_item_code||"—"}</span><span>{x.unit||"—"}</span><b>{Number(x.current_price).toFixed(2)} {s.currency}</b></div>)}</div>:<Empty text="No supplier items yet."/>}</section>}
 {tab==="Purchases"&&<Empty text="Purchase Orders will connect here when we build the Purchasing module."/>}
 {tab==="Invoices"&&<section><div className="mb-3 flex justify-end"><button onClick={()=>setModal("invoice")} className="rounded-xl bg-cyan-400 px-4 py-2 text-sm font-black text-slate-950">+ Supplier Invoice</button></div>{invoices.length?<Tx rows={invoices} currency={s.currency}/>:<Empty text="No supplier invoices yet."/>}</section>}
 {tab==="Payments"&&<section><div className="mb-3 flex justify-end"><button onClick={()=>setModal("payment")} className="rounded-xl bg-cyan-400 px-4 py-2 text-sm font-black text-slate-950">+ Record Payment</button></div>{payments.length?<Tx rows={payments} currency={s.currency}/>:<Empty text="No payments recorded yet."/>}</section>}
 {tab==="Statement"&&(tx.length?<Tx rows={tx} currency={s.currency}/>:<Empty text="No statement activity yet."/>)}
 {tab==="Documents"&&<section><div className="mb-3 flex justify-end"><button onClick={()=>setModal("document")} className="rounded-xl bg-cyan-400 px-4 py-2 text-sm font-black text-slate-950">+ Add Document</button></div>{d.documents.length?<div className={box}>{d.documents.map((x:any)=><div key={x.id} className="flex justify-between border-b border-slate-800 p-4 text-sm"><span><b>{x.name}</b><small className="ml-2 text-slate-500">{x.document_type}</small></span><span>Expiry: {x.expiry_date||"—"}</span></div>)}</div>:<Empty text="No documents yet."/>}</section>}
 {tab==="Performance"&&<section><div className="mb-3 flex justify-end"><button onClick={()=>setModal("performance")} className="rounded-xl bg-cyan-400 px-4 py-2 text-sm font-black text-slate-950">+ Performance Review</button></div>{d.performance.length?<div className={box}>{d.performance.map((x:any)=><div key={x.id} className="grid grid-cols-5 border-b border-slate-800 p-4 text-sm"><span>{x.event_date}</span><span>Quality {x.quality_score||"—"}</span><span>Price {x.price_score||"—"}</span><span>Delivery {x.delivery_score||"—"}</span><span>Service {x.service_score||"—"}</span></div>)}</div>:<Empty text="No supplier performance reviews yet."/>}</section>}
 {modal&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className={`${box} w-full max-w-lg p-6`}><div className="flex justify-between"><h2 className="text-xl font-black capitalize">Add {modal}</h2><button onClick={()=>setModal(null)}>×</button></div><div className="mt-5 space-y-3">{modal==="item"&&<><I label="Item Name" k="item_name" f={f} setF={setF}/><I label="Supplier Item Code" k="supplier_item_code" f={f} setF={setF}/><I label="Unit" k="unit" f={f} setF={setF}/><I label="Current Price" k="current_price" type="number" f={f} setF={setF}/></>}{["invoice","payment"].includes(modal)&&<><I label="Reference No." k="reference_no" f={f} setF={setF}/><I label="Amount" k="amount" type="number" f={f} setF={setF}/><I label="Due Date" k="due_date" type="date" f={f} setF={setF}/></>}{modal==="document"&&<><I label="Document Type" k="document_type" f={f} setF={setF}/><I label="Document Name" k="name" f={f} setF={setF}/><I label="File URL" k="file_url" f={f} setF={setF}/><I label="Expiry Date" k="expiry_date" type="date" f={f} setF={setF}/></>}{modal==="performance"&&<>{["quality_score","price_score","delivery_score","service_score"].map(k=><I key={k} label={k.replace("_score","").toUpperCase()+" Score / 5"} k={k} type="number" f={f} setF={setF}/>)}</>}<button onClick={()=>add(["invoice","payment"].includes(modal)?"transaction":modal,{...f,...(["invoice","payment"].includes(modal)?{transaction_type:modal,transaction_date:new Date().toISOString().slice(0,10),currency:s.currency}: {})})} className="w-full rounded-xl bg-cyan-400 py-3 font-black text-slate-950">Save</button></div></div></div>}
 </div>}
function I({label,k,f,setF,type="text"}:any){return <label className="block text-xs font-bold text-slate-400">{label}<input type={type} className={input} value={f[k]||""} onChange={e=>setF({...f,[k]:e.target.value})}/></label>}
function Tx({rows,currency}:any){return <div className={box}>{rows.map((x:any)=><div key={x.id} className="grid grid-cols-4 border-b border-slate-800 p-4 text-sm last:border-0"><span className="capitalize">{String(x.transaction_type).replaceAll("_"," ")}</span><span>{x.reference_no||"—"}</span><span>{x.transaction_date}</span><b>{Number(x.amount).toFixed(2)} {currency}</b></div>)}</div>}
