"use client";
import { useEffect, useMemo, useState } from "react";

const input="w-full rounded-xl border border-slate-800 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-500";
const empty={name:"",supplier_code:"",supplier_type:"local",contact_person:"",phone:"",whatsapp:"",email:"",category:"",city:"",country:"",tax_enabled:false,tax_number:"",cr_number:"",payment_terms_days:"0",credit_limit:"0",currency:"SAR",lead_time_days:"0",minimum_order:"0",preferred:false,status:"active",notes:""};

export default function SuppliersWorkspace(){
 const [rows,setRows]=useState<any[]>([]),[form,setForm]=useState<any>(empty),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[q,setQ]=useState("");
 async function load(){setLoading(true);const r=await fetch("/api/suppliers",{cache:"no-store"});const j=await r.json();setRows(j.suppliers||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function save(){if(!form.name.trim())return alert("Supplier name is required");setSaving(true);const r=await fetch("/api/suppliers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();setSaving(false);if(!r.ok)return alert(j.error||"Could not save supplier");setForm(empty);setOpen(false);load()}
 const shown=useMemo(()=>rows.filter(x=>`${x.name} ${x.supplier_code} ${x.category||""} ${x.phone||""}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 const balance=(x:any)=>Number(x.opening_balance||0);
 return <div className="space-y-6">
  <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.28em] text-cyan-300">Procurement</p><h1 className="mt-2 text-3xl font-black">Suppliers</h1><p className="mt-1 text-sm text-slate-400">Supplier profiles, commercial terms, balances, documents and performance.</p></div><button onClick={()=>setOpen(true)} className="rounded-xl bg-cyan-400 px-5 py-3 text-sm font-black text-slate-950">+ Add Supplier</button></div>
  <div className="grid gap-3 md:grid-cols-4">{[["Total Suppliers",rows.length],["Preferred",rows.filter(x=>x.preferred).length],["On Hold / Blocked",rows.filter(x=>["hold","blocked"].includes(x.status)).length],["Opening Payables",rows.reduce((a,x)=>a+balance(x),0).toFixed(2)+" SAR"]].map(([a,b])=><div key={a} className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><p className="text-xs text-slate-500">{a}</p><p className="mt-2 text-2xl font-black">{b}</p></div>)}</div>
  <div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><input value={q} onChange={e=>setQ(e.target.value)} className={input} placeholder="Search supplier, code, category or phone..."/></div>
  <div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div className="grid grid-cols-[1.4fr_.8fr_.8fr_.7fr_.6fr] gap-3 border-b border-slate-800 px-5 py-3 text-xs font-bold uppercase text-slate-500"><span>Supplier</span><span>Type</span><span>Category</span><span>Terms</span><span>Status</span></div>{loading?<p className="p-8 text-center text-slate-500">Loading...</p>:shown.length===0?<p className="p-10 text-center text-slate-500">No suppliers yet. Add the first supplier.</p>:shown.map(x=><div key={x.id} className="grid grid-cols-[1.4fr_.8fr_.8fr_.7fr_.6fr] gap-3 border-b border-slate-800/70 px-5 py-4 text-sm last:border-0"><div><p className="font-bold">{x.preferred?"★ ":""}{x.name}</p><p className="text-xs text-slate-500">{x.supplier_code} · {x.phone||"No phone"}</p></div><span className="capitalize text-slate-300">{String(x.supplier_type).replaceAll("_"," ")}</span><span className="text-slate-300">{x.category||"—"}</span><span className="text-slate-300">{x.payment_terms_days?`${x.payment_terms_days} days`:"Cash"}</span><span className="capitalize text-slate-300">{x.status}</span></div>)}</div>
  {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-3xl border border-slate-700 bg-slate-900 p-6"><div className="mb-6 flex items-center justify-between"><div><h2 className="text-2xl font-black">New Supplier</h2><p className="text-sm text-slate-500">Start simple. The supplier profile can grow later.</p></div><button onClick={()=>setOpen(false)} className="text-2xl text-slate-400">×</button></div><div className="grid gap-4 md:grid-cols-2">
   <label className="text-xs font-bold text-slate-400">Supplier Name *<input className={input} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>
   <label className="text-xs font-bold text-slate-400">Supplier Code <input className={input} placeholder="Auto generated if blank" value={form.supplier_code} onChange={e=>setForm({...form,supplier_code:e.target.value})}/></label>
   <label className="text-xs font-bold text-slate-400">Supplier Type<select className={input} value={form.supplier_type} onChange={e=>setForm({...form,supplier_type:e.target.value})}><option value="local">Local</option><option value="international">International</option><option value="manufacturer">Manufacturer</option><option value="distributor">Distributor</option><option value="service_provider">Service Provider</option></select></label>
   <label className="text-xs font-bold text-slate-400">Category<input className={input} placeholder="Food, Packaging, Maintenance..." value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label>
   {[["Contact Person","contact_person"],["Phone","phone"],["WhatsApp","whatsapp"],["Email","email"],["City","city"],["Country","country"],["Tax Number","tax_number"],["CR Number","cr_number"]].map(([a,k])=><label key={k} className="text-xs font-bold text-slate-400">{a}<input className={input} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}
   <label className="text-xs font-bold text-slate-400">Payment Terms (days)<input type="number" className={input} value={form.payment_terms_days} onChange={e=>setForm({...form,payment_terms_days:e.target.value})}/></label>
   <label className="text-xs font-bold text-slate-400">Credit Limit<input type="number" className={input} value={form.credit_limit} onChange={e=>setForm({...form,credit_limit:e.target.value})}/></label>
   <label className="text-xs font-bold text-slate-400">Lead Time (days)<input type="number" className={input} value={form.lead_time_days} onChange={e=>setForm({...form,lead_time_days:e.target.value})}/></label>
   <label className="text-xs font-bold text-slate-400">Minimum Order<input type="number" className={input} value={form.minimum_order} onChange={e=>setForm({...form,minimum_order:e.target.value})}/></label>
   <label className="flex items-center gap-3 rounded-xl border border-slate-800 p-3 text-sm"><input type="checkbox" checked={form.tax_enabled} onChange={e=>setForm({...form,tax_enabled:e.target.checked})}/> Tax registered</label>
   <label className="flex items-center gap-3 rounded-xl border border-slate-800 p-3 text-sm"><input type="checkbox" checked={form.preferred} onChange={e=>setForm({...form,preferred:e.target.checked})}/> Preferred supplier ★</label>
   <label className="md:col-span-2 text-xs font-bold text-slate-400">Internal Notes<textarea className={input+" min-h-24"} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label>
  </div><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setOpen(false)} className="rounded-xl border border-slate-700 px-5 py-3 text-sm font-bold">Cancel</button><button disabled={saving} onClick={save} className="rounded-xl bg-cyan-400 px-6 py-3 text-sm font-black text-slate-950 disabled:opacity-50">{saving?"Saving...":"Create Supplier"}</button></div></div></div>}
 </div>
}
