"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {ArrowDown,ArrowRight,ArrowUp,FileText,Pencil,Trophy,UsersRound} from "lucide-react";
import {useLanguage} from "./LanguageProvider";
import AgentAvatar from "./AgentAvatar";
type S={total:number;qualified:number;quotation:number;negotiation:number;won:number;lost:number};
const defs=["leads","qualified","quotations","won","zayn","naya"];
export default function UniversalAiDashboard({sales}:{sales:S;features:string[];agentResults?:any[];topPerformer?:any}){
 const{language}=useLanguage(),ar=language==="ar",[edit,setEdit]=useState(false),[order,setOrder]=useState(defs);
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem("avero-dashboard-order")||"[]");if(Array.isArray(x)&&x.length===defs.length)setOrder(x.map((k:string)=>k==="leo"?"zayn":k==="foxy"?"naya":k))}catch{}},[]);
 function move(i:number,d:number){const a=[...order],j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];setOrder(a);localStorage.setItem("avero-dashboard-order",JSON.stringify(a))}
 function card(k:string){const kpis:any={leads:["Leads",sales.total,<UsersRound key="i"/>],qualified:["Qualified",sales.qualified,<UsersRound key="i"/>],quotations:["Quotations",sales.quotation,<FileText key="i"/>],won:["Won",sales.won,<Trophy key="i"/>]};if(kpis[k]){const v=kpis[k];return <Kpi label={v[0]} value={v[1]} icon={v[2]}/>};const zayn=k==="zayn";return <Link href={zayn?"/ai-sales":"/ai-marketing"} className="group block rounded-3xl border border-slate-800 bg-slate-900/55 p-5 transition hover:-translate-y-0.5 hover:border-cyan-400/25"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className="overflow-hidden rounded-2xl border border-cyan-400/10 bg-slate-950"><AgentAvatar agent={zayn?"zayn":"naya"} size={52}/></div><div><b className="text-lg font-semibold text-white">{zayn?"ZAYN":"NAYA"}</b><p className="text-xs text-cyan-200">{zayn?"Sales Director":"Marketing Director"}</p></div></div><ArrowRight size={17} className="text-slate-600 group-hover:text-cyan-200"/></div><p className="mt-4 text-xs leading-5 text-slate-500">{zayn?"WhatsApp leads, qualification and sales actions.":"Content, campaigns, publishing and performance."}</p></Link>}
 return <main className="flex-1 overflow-y-auto px-4 py-6 md:px-7 md:py-8"><div className="mx-auto max-w-6xl space-y-6"><section className="rounded-3xl border border-slate-800 bg-slate-900/45 p-6"><div className="flex justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-cyan-300">AVERO OS · Intelligence</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] text-white">{ar?"شغلك اليوم، بشكل واضح.":"Your business today, at a glance."}</h1></div><button onClick={()=>setEdit(!edit)} className="h-fit rounded-xl border border-slate-800 bg-slate-950/35 px-4 py-2 text-sm font-medium text-slate-300"><Pencil size={15} className="mr-2 inline"/>{edit?"Done":"Edit Dashboard"}</button></div></section><section className="grid gap-4 md:grid-cols-2">{order.map((k,i)=><div key={k} className="relative">{edit&&<div className="absolute right-3 top-3 z-10 flex gap-1 rounded-lg border border-slate-800 bg-slate-950 p-1"><button onClick={()=>move(i,-1)}><ArrowUp size={16}/></button><button onClick={()=>move(i,1)}><ArrowDown size={16}/></button></div>}{card(k)}</div>)}</section></div></main>
}
function Kpi({label,value,icon}:any){return <div className="rounded-3xl border border-slate-800 bg-slate-900/55 p-5"><div className="flex justify-between text-sm text-slate-500"><span>{label}</span><span className="text-cyan-300">{icon}</span></div><p className="mt-5 text-4xl font-semibold tracking-[-.04em] text-white">{value}</p></div>}
