"use client";

import Link from "next/link";
import { Sparkles, Megaphone, BriefcaseBusiness, MessagesSquare, ArrowRight, UsersRound, Trophy, FileText, Activity, ShieldCheck, PackageCheck, BarChart3, Warehouse } from "lucide-react";
import { useLanguage } from "./LanguageProvider";

type SalesSnapshot = { total: number; qualified: number; quotation: number; negotiation: number; won: number; lost: number; };
type Agent = { key: string; name: string; animal: string; description: string; href: string; crm?: string; icon: typeof Sparkles; enabled: boolean; metric?: string; };

export default function UniversalAiDashboard({ sales, features }: { sales: SalesSnapshot; features: string[] }) {
  const { language } = useLanguage();
  const ar = language === "ar";
  const agents: Agent[] = [
    { key: "ai_sales", name: "Leo Sales", animal: "🦁", description: ar ? "تأهيل العملاء، واتساب، عروض الأسعار والمتابعة." : "WhatsApp sales, lead qualification, quotations and follow-up.", href: "/ai-sales", crm: "/crm/sales", icon: Sparkles, enabled: features.includes("ai_sales"), metric: ar ? `${sales.total} عميل محتمل` : `${sales.total} leads` },
    { key: "ai_marketing", name: "Foxy Marketing", animal: "🦊", description: ar ? "محتوى، حملات، سوشال ميديا ونمو." : "Content, campaigns, social media and growth actions.", href: "/ai-marketing", crm: "/crm/marketing", icon: Megaphone, enabled: features.includes("ai_marketing") },
    { key: "ai_hr", name: "Aero HR & Booking", animal: "🦅", description: ar ? "HR، حجوزات، مواعيد، تأكيدات وتذكيرات." : "HR, bookings, scheduling, confirmations and reminders.", href: "/ai-hr", crm: "/crm/hr", icon: BriefcaseBusiness, enabled: features.includes("ai_hr") },
    { key: "ai_support", name: "Gor Support", animal: "🦍", description: ar ? "حل مشاكل العملاء والدعم وخدمة ما بعد البيع." : "Customer questions, support issues and service handling.", href: "/ai-support", crm: "/crm/support", icon: MessagesSquare, enabled: features.includes("ai_support") },
    { key: "ai_inventory", name: "Vexa Inventory", animal: "🐍", description: ar ? "مخزون، نفاد، هدر، صلاحية وطلبات شراء." : "Stock levels, low-stock alerts, waste, expiry and replenishment.", href: "/ai-inventory", icon: PackageCheck, enabled: features.includes("ai_inventory") },
    { key: "ai_customer_care", name: "Rex Customer Care", animal: "🐕", description: ar ? "ولاء العملاء، المتابعة، الشكاوى والتقييمات." : "Loyalty, feedback, complaints and post-purchase follow-up.", href: "/ai-customer-care", icon: UsersRound, enabled: features.includes("ai_customer_care") },
    { key: "ai_analytics", name: "Nova Analytics", animal: "🐈", description: ar ? "تحليل بيانات، تقارير، فرص نمو وتوصيات." : "Data analysis, reports, growth opportunities and recommendations.", href: "/ai-analytics", icon: BarChart3, enabled: features.includes("ai_analytics") },
    { key: "ai_warehouse", name: "Bruno Warehouse", animal: "🐻", description: ar ? "استلام، تحويلات، جرد، حركة أصناف وسجلات." : "Receiving, transfers, stock counts, item movements and records.", href: "/ai-warehouse", icon: Warehouse, enabled: features.includes("ai_warehouse") },
  ];
  const enabledCount = agents.filter((agent) => agent.enabled).length;
  const snapshot = ar ? [["الإجمالي",sales.total],["مؤهلون",sales.qualified],["عرض سعر",sales.quotation],["تفاوض",sales.negotiation],["تم الفوز",sales.won],["مفقود",sales.lost]] : [["Total",sales.total],["Qualified",sales.qualified],["Quotation",sales.quotation],["Negotiation",sales.negotiation],["Won",sales.won],["Lost",sales.lost]];

  return <main className="flex-1 overflow-y-auto px-4 py-6 md:px-7 md:py-8"><div className="mx-auto max-w-[1500px] space-y-7">
    <div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.24em] text-cyan-400">{ar ? "AVERO OS" : "AVERO OS"}</p><h1 className="text-3xl font-bold tracking-tight text-white">{ar ? "نظام تشغيل المنشأة الذكي" : "Business Operations Platform"}</h1><p className="mt-2 text-sm text-slate-400">{ar ? "فريق AI كامل لإدارة المبيعات، التسويق، HR، الدعم، المخزون، العملاء، التحليلات والمستودع." : "A complete AI team for sales, marketing, HR, support, inventory, care, analytics and warehouse operations."}</p></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label={ar ? "الوكلاء المفعّلون" : "Active Agents"} value={enabledCount} icon={Activity} /><Kpi label={ar ? "عملاء المبيعات" : "Sales Leads"} value={sales.total} icon={UsersRound} /><Kpi label={ar ? "عروض الأسعار" : "Quotations"} value={sales.quotation} icon={FileText} /><Kpi label={ar ? "الصفقات المكتسبة" : "Won Deals"} value={sales.won} icon={Trophy} /></section>
    <section><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="text-xl font-semibold text-white">{ar ? "فريق AVERO OS" : "AVERO OS AI Team"}</h2><p className="mt-1 text-sm text-slate-500">{ar ? "افتح أي وكيل وغيّر أوامره من داخل النظام بدون الرجوع إلى Make." : "Open any agent and control its commands from the dashboard without going back to Make."}</p></div><ShieldCheck className="text-cyan-400" /></div><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{agents.map(({ name, animal, description, href, crm, icon: Icon, enabled, metric }) => <div key={name} className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl border border-slate-700 bg-slate-950 text-3xl">{animal}</div><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-base font-semibold text-white">{name}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${enabled ? "bg-emerald-500/10 text-emerald-400" : "bg-slate-800 text-slate-500"}`}>{enabled ? (ar ? "مفعّل" : "ENABLED") : (ar ? "غير مفعّل" : "NOT ENABLED")}</span></div><p className="mt-2 text-sm leading-6 text-slate-400">{description}</p>{metric && <p className="mt-3 text-sm font-medium text-cyan-300">{metric}</p>}</div></div><Icon size={20} className="text-cyan-400"/></div><div className="mt-5 flex flex-wrap gap-2 border-t border-slate-800 pt-4"><Link href={href} className="inline-flex items-center gap-2 rounded-lg bg-cyan-600 px-3 py-2 text-sm font-medium text-white hover:bg-cyan-500">{ar ? "فتح" : "Open"} <ArrowRight size={14}/></Link>{crm && <Link href={crm} className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-sm font-medium text-slate-300 hover:border-slate-600 hover:text-white">CRM</Link>}</div></div>)}</div></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><h2 className="text-lg font-semibold text-white">{ar ? "ملخص CRM المبيعات" : "Sales CRM Snapshot"}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{snapshot.map(([label,value]) => <div key={String(label)} className="rounded-xl border border-slate-800 bg-slate-950/50 p-4"><div className="text-xs text-slate-500">{label}</div><div className="mt-2 text-2xl font-bold text-white">{value}</div></div>)}</div></section>
  </div></main>;
}
function Kpi({ label, value, icon: Icon }: { label: string; value: number; icon: typeof Activity }) { return <div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex items-center justify-between"><span className="text-sm text-slate-400">{label}</span><Icon size={20} className="text-cyan-400"/></div><div className="mt-5 text-3xl font-bold text-white">{value}</div></div> }
