// @ts-nocheck
import {NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
import {getAuthorizationContext,isKingAdmin,isTenantAdmin,hasPermission} from "@/lib/auth/authorization";
const db=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SECRET_KEY!,{auth:{persistSession:false}});
async function ctx(){const a=await getAuthorizationContext();if(!a?.profile?.company_id)return null;return{a,s:db(),companyId:a.profile.company_id}}
function canManage(a:any){return isKingAdmin(a)||isTenantAdmin(a)||hasPermission(a,"users.permissions.manage")||hasPermission(a,"inventory.manage")}
export async function GET(){const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorized"},{status:401});if(!canManage(c.a))return NextResponse.json({error:"Forbidden"},{status:403});const [{data:users,error:e1},{data:warehouses,error:e2},{data:access,error:e3}]=await Promise.all([c.s.from("user_profiles").select("user_id,role,first_name,last_name,full_name,job_title").eq("company_id",c.companyId).order("created_at"),c.s.from("inventory_warehouses").select("id,name,code").eq("company_id",c.companyId).eq("active",true).order("name"),c.s.from("inventory_warehouse_access").select("*").eq("company_id",c.companyId)]);const error=e1||e2||e3;if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({users:users||[],warehouses:warehouses||[],access:access||[]})}
export async function POST(req:Request){const c=await ctx();if(!c)return NextResponse.json({error:"Unauthorized"},{status:401});if(!canManage(c.a))return NextResponse.json({error:"Forbidden"},{status:403});const b=await req.json();if(!b.user_id||!b.warehouse_id)return NextResponse.json({error:"User and warehouse are required"},{status:400});const payload={company_id:c.companyId,user_id:b.user_id,warehouse_id:b.warehouse_id,can_view:b.can_view!==false,can_manage:!!b.can_manage,can_transfer:!!b.can_transfer,can_count:!!b.can_count,can_view_cost:!!b.can_view_cost,updated_at:new Date().toISOString()};const {data,error}=await c.s.from("inventory_warehouse_access").upsert(payload,{onConflict:"company_id,user_id,warehouse_id"}).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});await c.s.from("inventory_audit_log").insert({company_id:c.companyId,entity_type:"warehouse_access",entity_id:data.id,action:"update_access",details:payload,created_by:c.a.user.id});return NextResponse.json({record:data})}
