"use client";
import {useEffect,useMemo,useState} from "react";
import Sidebar from "@/app/components/Sidebar";import DashboardHeader from "@/app/components/DashboardHeader";import {useLanguage} from "@/app/components/LanguageProvider";
type C={id:string;customer_code?:string;name:string;phone?:string;email?:string;tax_number?:string;commercial_registration?:string;national_address?:string;iban?:string;address?:string;city?:string;notes?:string;customer_type:"individual"|"business";orders:number;total:number;cash:number;card:number;credit:number;other:number};
const inp="w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-400";
const blank={name:"",phone:"",email:"",commercial_registration:"",tax_number:"",national_address:"",iban:"",address:"",city:"",notes:""};
export default function CustomersPage(){const{language}=useLanguage(),ar=language==="ar",L=(e:string,a:string)=>ar?a:e;const[rows,setRows]=useState<C[]>([]),[q,setQ]=useState(""),[edit,setEdit]=useState<any|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){const r=await fetch("/api/customers",{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Failed");setRows(j.customers||[])}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 const filtered=useMemo(()=>rows.filter(c=>[c.customer_code,c.name,c.phone,c.email,c.tax_number,c.commercial_registration].some(v=>String(v||"").toLowerCase().includes(q.toLowerCase()))),[rows,q]);
 async function save(){if(!edit?.name?.trim())return;setBusy(true);setError("");try{const r=await fetch("/api/customers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(edit)}),j=await r.json();if(!r.ok)throw new Error(j.error||L("Could not save customer","تعذّر حفظ العميل"));setEdit(null);await load()}catch(e){setError(e instanceof Error?e.message:"Error")}finally{setBusy(false)}}
 return <div className="min-h-screen bg-slate-950 text-white"><Sidebar/><div className="min-h-screen md:ml-64"><DashboardHeader/><main className="mx-auto max-w-7xl p-5 md:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">{L("Customers","العملاء")}</h1><p className="mt-2 text-slate-400">{L("Individuals and business customers with complete sales history.","عملاء أفراد وشركات مع سجل المبيعات الكامل.")}</p></div><button onClick={()=>setEdit({...blank})} className="rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950">+ {L("Add customer","إضافة عميل")}</button></div>
 <input className={inp+" mt-6 max-w-lg"} placeholder={L("Search by name, phone, code, CR or VAT number","بحث بالاسم أو الهاتف أو الكود أو السجل أو الرقم الضريبي")} value={q} onChange={e=>setQ(e.target.value)}/>{error&&<p className="mt-3 text-rose-300">{error}</p>}
 <div className="mt-5 overflow-x-auto rounded-2xl border border-slate-800 bg-slate-900/60"><table className="w-full text-sm"><thead className="border-b border-slate-800 text-slate-400"><tr>{[L("Customer","العميل"),L("Type","النوع"),L("Orders","الطلبات"),L("Purchases","المشتريات"),L("Cash","نقدي"),L("Card","بطاقة"),L("Credit","آجل"),""].map((x,i)=><th key={i} className="px-4 py-3 text-left font-semibold">{x}</th>)}</tr></thead><tbody>{filtered.map(c=><tr key={c.id} className="border-b border-slate-800/70"><td className="px-4 py-4"><strong>{c.name}</strong><div className="text-xs text-slate-500">{c.phone||c.email||c.customer_code}</div></td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-xs ${c.customer_type==="business"?"bg-cyan-400/10 text-cyan-300":"bg-slate-800 text-slate-300"}`}>{c.customer_type==="business"?"B2B":L("Individual","فرد")}</span></td><td className="px-4 py-4">{c.orders}</td>{[c.total,c.cash,c.card,c.credit].map((v,i)=><td key={i} className="px-4 py-4">{Number(v||0).toFixed(2)} SAR</td>)}<td className="px-4 py-4"><button className="text-cyan-300" onClick={()=>setEdit({...blank,...c})}>{L("Edit","تعديل")}</button></td></tr>)}</tbody></table></div>
 {edit&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-3xl border border-slate-700 bg-slate-900 p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{edit.id?L("Edit customer","تعديل العميل"):L("Add customer","إضافة عميل")}</h2><p className="mt-1 text-xs text-slate-400">{L("Only the name is required. Completing CR + VAT number + National address automatically marks this customer as B2B.","الاسم فقط إلزامي. إدخال السجل التجاري + الرقم الضريبي + العنوان الوطني يحوّل العميل تلقائياً إلى B2B.")}</p></div><button onClick={()=>setEdit(null)}>✕</button></div><div className="mt-5 grid gap-3 md:grid-cols-2">
 {([["name","Name *","الاسم *"],["phone","Phone","الهاتف"],["email","Email","البريد الإلكتروني"],["commercial_registration","Commercial registration","السجل التجاري"],["tax_number","VAT number","الرقم الضريبي"],["national_address","National address","العنوان الوطني"],["iban","IBAN","رقم الآيبان"],["city","City","المدينة"],["address","Additional address","عنوان إضافي"]] as const).map(([k,e,a])=><label key={k} className="text-sm text-slate-300">{L(e,a)}<input className={inp+" mt-1"} value={edit[k]||""} onChange={ev=>setEdit({...edit,[k]:ev.target.value})}/></label>)}<label className="md:col-span-2 text-sm text-slate-300">{L("Notes","ملاحظات")}<textarea className={inp+" mt-1 min-h-20"} value={edit.notes||""} onChange={e=>setEdit({...edit,notes:e.target.value})}/></label></div><div className="mt-5 flex items-center justify-between"><span className="text-sm text-slate-400">{edit.commercial_registration&&edit.tax_number&&edit.national_address?L("Customer type: B2B","نوع العميل: B2B"):L("Customer type: Individual","نوع العميل: فرد")}</span><button disabled={busy||!edit.name?.trim()} onClick={save} className="rounded-xl bg-cyan-400 px-6 py-3 font-bold text-slate-950 disabled:opacity-50">{busy?L("Saving…","جارٍ الحفظ…"):L("Save customer","حفظ العميل")}</button></div></div></div>}
 </main></div></div>}