"use client";

import { useEffect, useState } from "react";
import Sidebar from "@/app/components/Sidebar";
import DashboardHeader from "@/app/components/DashboardHeader";
import { useLanguage } from "@/app/components/LanguageProvider";
import { Bot, Headphones, Send, ShieldCheck, Wrench, MessageSquareText } from "lucide-react";

type Message = { role:"ai"|"user"; text:string };

export default function HelpCenterPage() {
  const { language } = useLanguage(); const ar = language === "ar";
  const [message,setMessage]=useState(""); const [messages,setMessages]=useState<Message[]>([]); const [sending,setSending]=useState(false);

  useEffect(()=>{(async()=>{const res=await fetch("/api/help-center",{cache:"no-store"});if(res.ok){const rows=await res.json();if(Array.isArray(rows)&&rows.length)setMessages(rows.map((r:{role:string;message:string})=>({role:r.role==="user"?"user":"ai",text:r.message})));else setMessages([{role:"ai",text:ar?"أهلاً بك. أنا مساعد AVERO الذكي. اشرح لي ما الذي تريد تعديله أو تحتاج مساعدة فيه.":"Welcome. I’m the AVERO AI Assistant. Tell me what you need help with or what you want to change."}]);}})();},[ar]);

  const send=async()=>{const text=message.trim();if(!text||sending)return;setMessage("");setSending(true);setMessages(v=>[...v,{role:"user",text}]);const res=await fetch("/api/help-center",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text})});const data=await res.json().catch(()=>({}));const responseText=res.ok?(data.action_request?(ar?"تم حفظ طلب التعديل في AVERO وهو الآن بانتظار التأكيد قبل التنفيذ.":"Your change request was saved in AVERO and is awaiting confirmation before execution."):(ar?"تم حفظ رسالتك في مركز المساعدة.":"Your message was saved in the Help Center.")):(ar?"تعذر حفظ الرسالة حالياً.":"The message could not be saved right now.");setMessages(v=>[...v,{role:"ai",text:responseText}]);setSending(false);};

  return <div className="min-h-screen bg-slate-950"><Sidebar/><div className="ml-64 flex min-h-screen flex-col"><DashboardHeader/><main className="flex-1 px-6 py-7 text-white"><div className="mx-auto max-w-6xl">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-violet-400"><Headphones size={15}/>{ar?"مركز مساعدة AVERO":"AVERO HELP CENTER"}</div><h1 className="text-3xl font-bold">{ar?"مساعدة ذكية على مدار الساعة":"24/7 AI Help & Control Center"}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{ar?"المركز الأساسي لمساعدة العميل وإدارة AVERO. المحادثات وطلبات التعديل أصبحت محفوظة على حساب العميل.":"The primary customer assistance and AVERO control center. Conversations and change requests are now stored on the client account."}</p></div><div className="flex items-center gap-2 rounded-full border border-emerald-500/20 bg-emerald-500/10 px-4 py-2 text-xs text-emerald-300"><span className="h-2 w-2 rounded-full bg-emerald-400"/>{ar?"متاح 24/7":"Available 24/7"}</div></div>
    <div className="mt-7 grid gap-5 md:grid-cols-3">{[[MessageSquareText,ar?"دعم فوري":"Instant Help",ar?"اسأل عن أي جزء في النظام.":"Ask about any part of AVERO."],[Wrench,ar?"طلبات التعديل":"Change Requests",ar?"طلبات التعديل تحفظ بسجل آمن قبل التنفيذ.":"Change requests are stored in a safe action queue before execution."],[ShieldCheck,ar?"تنفيذ آمن":"Safe Actions",ar?"الأوامر الحساسة تحتاج تأكيداً وصلاحية.":"Sensitive actions require permission and confirmation."]].map(([Icon,title,desc],i)=>{const I=Icon as typeof Bot;return <div key={i} className="rounded-2xl border border-slate-800 bg-slate-900/55 p-5"><I className="text-blue-400" size={22}/><h2 className="mt-3 font-semibold">{title as string}</h2><p className="mt-1 text-sm text-slate-500">{desc as string}</p></div>})}</div>
    <section className="mt-6 overflow-hidden rounded-3xl border border-slate-800 bg-slate-900/55"><div className="flex items-center gap-3 border-b border-slate-800 p-5"><div className="rounded-xl bg-violet-500/10 p-2.5 text-violet-300"><Bot size={22}/></div><div><p className="font-semibold">{ar?"مساعد AVERO الذكي":"AVERO AI Assistant"}</p><p className="text-xs text-slate-500">{ar?"دعم وإدارة النظام":"Support & system control"}</p></div></div><div className="h-[360px] space-y-3 overflow-y-auto p-5">{messages.map((m,i)=><div key={i} className={`flex ${m.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[75%] rounded-2xl px-4 py-3 text-sm leading-6 ${m.role==="user"?"bg-blue-600 text-white":"border border-slate-800 bg-slate-950 text-slate-300"}`}>{m.text}</div></div>)}</div><div className="flex gap-3 border-t border-slate-800 p-4"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder={ar?"اكتب ما تريد من AVERO...":"Tell AVERO what you need..."} className="flex-1 rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm outline-none focus:border-blue-500"/><button disabled={sending} onClick={send} className="flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold hover:bg-blue-500 disabled:opacity-50"><Send size={16}/>{sending?(ar?"جارٍ الحفظ...":"Saving..."):(ar?"إرسال":"Send")}</button></div></section>
    <p className="mt-4 text-center text-xs text-slate-600">{ar?"تم ربط سجل المحادثات وطلبات الأوامر بـ Supabase. التنفيذ الآلي نفسه سيبقى محمياً بطبقة الصلاحيات والتأكيد قبل تشغيل أي تغيير فعلي.":"Conversation history and action requests are connected to Supabase. Live automation remains protected by permissions and confirmation before any real change is executed."}</p>
  </div></main></div></div>;
}
