"use client";

import { useState } from "react";
import Sidebar from "@/app/components/Sidebar";
import DashboardHeader from "@/app/components/DashboardHeader";
import { useLanguage } from "@/app/components/LanguageProvider";
import { Bot, Headphones, Send, ShieldCheck, Wrench, MessageSquareText } from "lucide-react";

export default function HelpCenterPage() {
  const { language } = useLanguage();
  const ar = language === "ar";
  const [message,setMessage]=useState("");
  const [messages,setMessages]=useState<{role:"ai"|"user";text:string}[]>([{role:"ai",text:ar?"أهلاً بك. أنا مساعد AVERO الذكي. اشرح لي ما الذي تريد تعديله أو تحتاج مساعدة فيه.":"Welcome. I’m the AVERO AI Assistant. Tell me what you need help with or what you want to change."}]);
  const send=()=>{if(!message.trim())return;setMessages(v=>[...v,{role:"user",text:message.trim()},{role:"ai",text:ar?"تم استلام طلبك. قريباً سيتم ربط هذا المركز بمحرك الأوامر لتنفيذ التعديلات المصرح بها بعد تأكيدك.":"Request received. This center is being connected to the command engine so authorized changes can be executed after your confirmation."}]);setMessage("");};

  return <div className="min-h-screen bg-slate-950"><Sidebar/><div className="ml-64 flex min-h-screen flex-col"><DashboardHeader/><main className="flex-1 px-6 py-7 text-white"><div className="mx-auto max-w-6xl">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-violet-400"><Headphones size={15}/>{ar?"مركز مساعدة AVERO":"AVERO HELP CENTER"}</div><h1 className="text-3xl font-bold">{ar?"مساعدة ذكية على مدار الساعة":"24/7 AI Help & Control Center"}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{ar?"المركز الأساسي لمساعدة العميل وإدارة AVERO. اسأل، اطلب شرحاً، أو اطلب تعديل إعداداتك ووكلائك وصلاحياتك من مكان واحد.":"The primary customer assistance and AVERO control center. Ask questions, get guidance, or request changes to your settings, agents and permitted features from one place."}</p></div><div className="flex items-center gap-2 rounded-full border border-emerald-500/20 bg-emerald-500/10 px-4 py-2 text-xs text-emerald-300"><span className="h-2 w-2 rounded-full bg-emerald-400"/>{ar?"متاح 24/7":"Available 24/7"}</div></div>
    <div className="mt-7 grid gap-5 md:grid-cols-3">{[[MessageSquareText,ar?"دعم فوري":"Instant Help",ar?"اسأل عن أي جزء في النظام.":"Ask about any part of AVERO."],[Wrench,ar?"طلبات التعديل":"Change Requests",ar?"اطلب تعديل الإعدادات والوكلاء.":"Request settings and agent changes."],[ShieldCheck,ar?"تنفيذ آمن":"Safe Actions",ar?"الأوامر الحساسة تحتاج تأكيداً وصلاحية.":"Sensitive actions require permission and confirmation."]].map(([Icon,title,desc],i)=>{const I=Icon as typeof Bot;return <div key={i} className="rounded-2xl border border-slate-800 bg-slate-900/55 p-5"><I className="text-blue-400" size={22}/><h2 className="mt-3 font-semibold">{title as string}</h2><p className="mt-1 text-sm text-slate-500">{desc as string}</p></div>})}</div>
    <section className="mt-6 overflow-hidden rounded-3xl border border-slate-800 bg-slate-900/55"><div className="flex items-center gap-3 border-b border-slate-800 p-5"><div className="rounded-xl bg-violet-500/10 p-2.5 text-violet-300"><Bot size={22}/></div><div><p className="font-semibold">{ar?"مساعد AVERO الذكي":"AVERO AI Assistant"}</p><p className="text-xs text-slate-500">{ar?"دعم وإدارة النظام":"Support & system control"}</p></div></div><div className="h-[360px] space-y-3 overflow-y-auto p-5">{messages.map((m,i)=><div key={i} className={`flex ${m.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[75%] rounded-2xl px-4 py-3 text-sm leading-6 ${m.role==="user"?"bg-blue-600 text-white":"border border-slate-800 bg-slate-950 text-slate-300"}`}>{m.text}</div></div>)}</div><div className="flex gap-3 border-t border-slate-800 p-4"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder={ar?"اكتب ما تريد من AVERO...":"Tell AVERO what you need..."} className="flex-1 rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm outline-none focus:border-blue-500"/><button onClick={send} className="flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold hover:bg-blue-500"><Send size={16}/>{ar?"إرسال":"Send"}</button></div></section>
    <p className="mt-4 text-center text-xs text-slate-600">{ar?"حالياً واجهة المركز جاهزة. ربط تنفيذ أوامر الذكاء الاصطناعي الفعلية سيتم مع طبقة Supabase والصلاحيات حتى لا ينفذ أي تعديل غير مصرح به.":"The help-center interface is ready. Live AI action execution will be connected with the Supabase permission layer so no unauthorized change can be executed."}</p>
  </div></main></div></div>;
}
