"use client";

import { useEffect, useState } from "react";
import Sidebar from "@/app/components/Sidebar";
import DashboardHeader from "@/app/components/DashboardHeader";
import { Save } from "lucide-react";
import { useLanguage } from "@/app/components/LanguageProvider";

type ProfileForm={full_name:string;username:string;nickname:string;age:string;bio:string;email:string;avatar_url:string};
const empty:ProfileForm={full_name:"",username:"",nickname:"",age:"",bio:"",email:"",avatar_url:""};
const toForm=(d:any):ProfileForm=>({full_name:d.full_name||"",username:d.username||"",nickname:d.nickname||"",age:d.age==null?"":String(d.age),bio:d.bio||"",email:d.email||"",avatar_url:d.avatar_url||""});

export default function ProfilePage(){
 const {language}=useLanguage();const ar=language==="ar";
 const [form,setForm]=useState<ProfileForm>(empty);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{(async()=>{try{const r=await fetch("/api/profile",{cache:"no-store"});const d=await r.json();if(r.ok)setForm(toForm(d));else setMessage(d.error||"Failed to load profile");}finally{setLoading(false)}})()},[]);
 const change=(k:keyof ProfileForm,v:string)=>setForm(p=>({...p,[k]:v}));
 const save=async()=>{setSaving(true);setMessage("");try{const r=await fetch("/api/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Failed to save profile");const next=toForm({...d.profile,email:d.email,avatar_url:d.profile?.avatar_url||form.avatar_url});setForm(next);window.dispatchEvent(new CustomEvent("avero-profile-updated",{detail:{...d.profile,email:d.email}}));setMessage(ar?"تم حفظ كل بيانات الملف الشخصي":"All profile details saved");}catch(e){const t=e instanceof Error?e.message:"Failed to save profile";setMessage(ar?(t==="Username already in use"?"اسم المستخدم مستخدم من قبل":t==="Invalid email"?"البريد الإلكتروني غير صحيح":"تعذر حفظ الملف الشخصي"):t)}finally{setSaving(false)}};
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-slate-950 text-slate-400">{ar?"جارٍ تحميل الملف الشخصي...":"Loading profile..."}</div>;
 const display=form.nickname||form.full_name||form.username||form.email||"U";const initials=display.slice(0,2).toUpperCase();
 return <div className="min-h-screen bg-slate-950"><Sidebar userEmail={form.email} userName={display}/><div className="ml-64 flex min-h-screen flex-col"><DashboardHeader userEmail={form.email} userName={display}/><main className="flex-1 px-6 py-7 text-white"><div className="mx-auto max-w-5xl"><div className="mb-6"><h1 className="text-3xl font-bold">{ar?"الملف الشخصي":"Profile"}</h1><p className="mt-1 text-slate-400">{ar?"عدّل بيانات حسابك واحفظها مباشرة في AVERO":"Edit your account details and save them directly in AVERO"}</p></div><div className="grid gap-6 lg:grid-cols-[280px_1fr]"><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 text-center"><div className="mx-auto flex h-28 w-28 items-center justify-center overflow-hidden rounded-3xl border border-blue-400/20 bg-gradient-to-br from-blue-600 to-cyan-500 text-3xl font-bold">{form.avatar_url?<img src={form.avatar_url} alt="" className="h-full w-full object-cover"/>:initials}</div><p className="mt-4 text-sm font-semibold">{display}</p>{form.username&&<p className="mt-1 text-xs text-blue-300">@{form.username}</p>}<p className="text-xs text-slate-500">{form.email}</p></section><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><div className="grid gap-4 md:grid-cols-2"><Field label={ar?"الاسم":"Name"} value={form.full_name} onChange={v=>change("full_name",v)}/><Field label={ar?"اسم المستخدم":"Username"} value={form.username} onChange={v=>change("username",v)}/><Field label={ar?"الاسم المختصر":"Nickname"} value={form.nickname} onChange={v=>change("nickname",v)}/><Field label={ar?"العمر":"Age"} value={form.age} type="number" onChange={v=>change("age",v)}/><Field label={ar?"البريد الإلكتروني":"Email"} value={form.email} type="email" onChange={v=>change("email",v)}/></div><label className="mt-4 block text-sm text-slate-300">{ar?"نبذة شخصية":"Bio"}<textarea value={form.bio} onChange={e=>change("bio",e.target.value)} rows={5} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-white outline-none focus:border-blue-500"/></label><div className="mt-5 flex items-center justify-between gap-4"><span className="text-sm text-emerald-400">{message}</span><button onClick={save} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-2.5 font-medium hover:bg-blue-500 disabled:opacity-50"><Save size={16}/>{saving?(ar?"جارٍ الحفظ...":"Saving..."):(ar?"حفظ الملف الشخصي":"Save profile")}</button></div></section></div></div></main></div></div>
}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="block text-sm text-slate-300">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-white outline-none focus:border-blue-500"/></label>}
