// @ts-nocheck
import {NextResponse} from 'next/server';
import {createClient} from '@supabase/supabase-js';
import {getAuthorizationContext,isKingAdmin,isTenantAdmin,hasPermission} from '@/lib/auth/authorization';
const db=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SECRET_KEY!,{auth:{persistSession:false}});
const can=(a:any,p:string)=>isKingAdmin(a)||isTenantAdmin(a)||hasPermission(a,p);
async function C(){const a=await getAuthorizationContext();return a?.profile?.company_id?{a,c:a.profile.company_id,s:db()}:null}
export async function GET(){const x=await C();if(!x)return NextResponse.json({error:'Unauthorized'},{status:401});const [customers,b2b,invoices,payments,tables,invoiceTemplate,products,categories,profiles]=await Promise.all([
 x.s.from('sales_customers').select('*').eq('company_id',x.c).order('created_at',{ascending:false}),
 x.s.from('b2b_accounts').select('*').eq('company_id',x.c).order('created_at',{ascending:false}),
 x.s.from('b2b_invoices').select('*,b2b_invoice_lines(*),b2b_accounts(legal_name)').eq('company_id',x.c).order('created_at',{ascending:false}),
 x.s.from('sales_payment_methods').select('*').eq('company_id',x.c).eq('active',true).order('sort_order'),
 x.s.from('sales_dining_tables').select('*').eq('company_id',x.c).order('sort_order'),
 x.s.from('sales_invoice_templates').select('*').eq('company_id',x.c).maybeSingle(),
 x.s.from('sales_products').select('*,sales_categories(name)').eq('company_id',x.c).order('created_at',{ascending:false}),
 x.s.from('sales_categories').select('*').eq('company_id',x.c).order('sort_order'),
 x.s.from('user_profiles').select('user_id,full_name,username,nickname').eq('company_id',x.c)
]);return NextResponse.json({customers:customers.data||[],b2b:b2b.data||[],invoices:invoices.data||[],payment_methods:payments.data||[],tables:tables.data||[],invoice_template:invoiceTemplate.data||null,products:products.data||[],categories:categories.data||[],profiles:profiles.data||[]})}
export async function POST(req:Request){const x=await C();if(!x)return NextResponse.json({error:'Unauthorized'},{status:401});const b=await req.json(),d=b.data||{};let r:any;
 if(b.kind==='customer'){if(!can(x.a,'customers.manage'))return NextResponse.json({error:'Forbidden'},{status:403});if(!String(d.name||'').trim())return NextResponse.json({error:'Name required'},{status:400});const p={company_id:x.c,name:String(d.name).trim(),phone:d.phone||null,email:d.email||null,tax_number:d.tax_number||null,address:d.address||null,city:d.city||null,notes:d.notes||null,active:d.active!==false};r=d.id?await x.s.from('sales_customers').update(p).eq('id',d.id).eq('company_id',x.c).select().single():await x.s.from('sales_customers').insert({...p,customer_code:d.customer_code||`CUS-${Date.now().toString().slice(-7)}`}).select().single();}
 else if(b.kind==='b2b_account'){if(!can(x.a,'b2b.manage'))return NextResponse.json({error:'Forbidden'},{status:403});if(!String(d.legal_name||'').trim())return NextResponse.json({error:'Legal name required'},{status:400});const p={company_id:x.c,legal_name:String(d.legal_name).trim(),trade_name:d.trade_name||null,tax_number:d.tax_number||null,contact_name:d.contact_name||null,phone:d.phone||null,email:d.email||null,address:d.address||null,city:d.city||null,credit_limit:Number(d.credit_limit||0),payment_terms_days:Number(d.payment_terms_days||0),notes:d.notes||null,active:d.active!==false};r=d.id?await x.s.from('b2b_accounts').update(p).eq('id',d.id).eq('company_id',x.c).select().single():await x.s.from('b2b_accounts').insert({...p,account_code:d.account_code||`B2B-${Date.now().toString().slice(-7)}`}).select().single();}
 else if(b.kind==='b2b_invoice'){if(!can(x.a,'b2b.manage'))return NextResponse.json({error:'Forbidden'},{status:403});const a=await x.s.from('b2b_accounts').select('id,payment_terms_days').eq('id',d.account_id).eq('company_id',x.c).maybeSingle();if(!a.data)return NextResponse.json({error:'Invalid B2B account'},{status:400});const lines=Array.isArray(d.lines)?d.lines.filter((z:any)=>String(z.description||'').trim()&&Number(z.quantity)>0):[];if(!lines.length)return NextResponse.json({error:'Add invoice lines'},{status:400});let subtotal=0,tax=0;for(const z of lines){const base=Number(z.quantity)*Number(z.unit_price||0);subtotal+=base;tax+=base*Number(z.tax_rate||0)/100;}const inv=await x.s.from('b2b_invoices').insert({company_id:x.c,account_id:d.account_id,invoice_no:d.invoice_no||`B2B-${Date.now()}`,invoice_date:d.invoice_date||new Date().toISOString().slice(0,10),due_date:d.due_date||null,status:d.status||'issued',subtotal,tax,total:subtotal+tax,notes:d.notes||null,created_by:x.a.user.id}).select().single();if(inv.error)return NextResponse.json({error:inv.error.message},{status:400});const lr=await x.s.from('b2b_invoice_lines').insert(lines.map((z:any)=>{const base=Number(z.quantity)*Number(z.unit_price||0);return{company_id:x.c,invoice_id:inv.data.id,description:String(z.description).trim(),quantity:Number(z.quantity),unit_price:Number(z.unit_price||0),tax_rate:Number(z.tax_rate||0),line_total:base+base*Number(z.tax_rate||0)/100}}));if(lr.error){await x.s.from('b2b_invoices').delete().eq('id',inv.data.id);return NextResponse.json({error:lr.error.message},{status:400});}return NextResponse.json({record:inv.data});}
 else if(b.kind==='payment_method'){if(!can(x.a,'sales.manage'))return NextResponse.json({error:'Forbidden'},{status:403});const p={company_id:x.c,code:String(d.code||d.name||'pay').toLowerCase().replace(/\s+/g,'_'),name:String(d.name||'Payment'),adjustment_percent:Number(d.adjustment_percent||0),adjustment_type:d.adjustment_type==='discount'?'discount':'markup',active:d.active!==false,sort_order:Number(d.sort_order||0),updated_at:new Date().toISOString()};r=d.id?await x.s.from('sales_payment_methods').update(p).eq('id',d.id).eq('company_id',x.c).select().single():await x.s.from('sales_payment_methods').insert(p).select().single();}
 else if(b.kind==='dining_table'){if(!can(x.a,'sales.manage'))return NextResponse.json({error:'Forbidden'},{status:403});const p={company_id:x.c,name:String(d.name||'Table').trim(),area:d.area||null,seats:Number(d.seats||2),status:d.status||'open',sort_order:Number(d.sort_order||0),updated_at:new Date().toISOString()};r=d.id?await x.s.from('sales_dining_tables').update(p).eq('id',d.id).eq('company_id',x.c).select().single():await x.s.from('sales_dining_tables').insert(p).select().single();}
 else if(b.kind==='invoice_template'){if(!can(x.a,'sales.invoice.customize'))return NextResponse.json({error:'Forbidden'},{status:403});r=await x.s.from('sales_invoice_templates').upsert({company_id:x.c,business_name:d.business_name||null,logo_url:d.logo_url||null,header_text:d.header_text||null,footer_text:d.footer_text||null,paper_size:['roll58','roll80','a4'].includes(d.paper_size)?d.paper_size:'roll80',show_tax_number:d.show_tax_number!==false,show_cashier:d.show_cashier!==false,show_customer:d.show_customer!==false,show_item_notes:d.show_item_notes!==false,accent:d.accent||'#06b6d4',updated_at:new Date().toISOString()},{onConflict:'company_id'}).select().single();}
 else if(b.kind==='product_update'){if(!can(x.a,'sales.manage'))return NextResponse.json({error:'Forbidden'},{status:403});const p:any={name:String(d.name||'').trim(),price:Number(d.price||0),category_id:d.category_id||null,barcode:d.barcode||null,sku:d.sku||null,active:d.active!==false,show_on_cashier:d.show_on_cashier!==false,updated_at:new Date().toISOString()};r=await x.s.from('sales_products').update(p).eq('id',d.id).eq('company_id',x.c).select().single();}
 else return NextResponse.json({error:'Invalid action'},{status:400});return r?.error?NextResponse.json({error:r.error.message},{status:400}):NextResponse.json({record:r.data});}
