import { createClient as createAdminClient } from "@supabase/supabase-js";
import { createClient as createServerClient } from "@/lib/supabase/server";

const notificationKeys = ["new_lead","qualified_lead","quotation_request","negotiation_started","high_interest","new_customer_message","won_deal","lost_deal","event_soon","ai_handoff","automation_error","subscription_expiry","security_alert"] as const;
const defaults: Record<string, boolean> = {new_lead:true,qualified_lead:true,quotation_request:true,negotiation_started:true,high_interest:true,new_customer_message:true,won_deal:true,lost_deal:false,event_soon:true,ai_handoff:true,automation_error:true,subscription_expiry:true,security_alert:true};

async function context(){const auth=await createServerClient();const {data:{user}}=await auth.auth.getUser();if(!user)return null;const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY;if(!url||!key)throw new Error("Missing Supabase configuration");const admin=createAdminClient(url,key);const {data:profile}=await admin.from("user_profiles").select("company_id").eq("user_id",user.id).maybeSingle();if(!profile?.company_id)return null;return {user,companyId:profile.company_id as string,admin};}
function response(row:any){const notification_prefs:Object=Object.fromEntries(notificationKeys.map(k=>[k,row?.[k] ?? defaults[k]]));return {language:row?.language||"en",theme:row?.theme||"system",notification_master:row?.notifications_enabled??true,notification_sound:row?.notification_sound??true,notification_prefs};}

export async function GET(){try{const ctx=await context();if(!ctx)return Response.json({error:"Unauthorized"},{status:401});let {data,error}=await ctx.admin.from("user_preferences").select("*").eq("user_id",ctx.user.id).maybeSingle();if(error)return Response.json({error:"Failed to load settings"},{status:500});if(!data){const row:any={user_id:ctx.user.id,company_id:ctx.companyId,language:"en",theme:"system",notifications_enabled:true,notification_sound:true,...defaults};const created=await ctx.admin.from("user_preferences").insert(row).select("*").single();if(created.error)return Response.json({error:"Failed to initialize settings"},{status:500});data=created.data;}return Response.json(response(data));}catch(error){console.error("Settings GET error:",error);return Response.json({error:"Internal server error"},{status:500});}}

export async function PATCH(request:Request){try{const ctx=await context();if(!ctx)return Response.json({error:"Unauthorized"},{status:401});const body=await request.json();const row:any={user_id:ctx.user.id,company_id:ctx.companyId,updated_at:new Date().toISOString()};if(body.language==="en"||body.language==="ar")row.language=body.language;if(["dark","light","system"].includes(body.theme))row.theme=body.theme;if(typeof body.notification_master==="boolean")row.notifications_enabled=body.notification_master;if(typeof body.notification_sound==="boolean")row.notification_sound=body.notification_sound;if(body.notification_prefs&&typeof body.notification_prefs==="object"&&!Array.isArray(body.notification_prefs)){for(const k of notificationKeys)if(typeof body.notification_prefs[k]==="boolean")row[k]=body.notification_prefs[k];}
const {data:existing}=await ctx.admin.from("user_preferences").select("user_id").eq("user_id",ctx.user.id).maybeSingle();let result;if(existing)result=await ctx.admin.from("user_preferences").update(row).eq("user_id",ctx.user.id).select("*").single();else result=await ctx.admin.from("user_preferences").insert({language:"en",theme:"system",notifications_enabled:true,notification_sound:true,...defaults,...row}).select("*").single();if(result.error){console.error("Settings PATCH database error:",result.error);return Response.json({error:"Failed to save settings"},{status:500});}return Response.json(response(result.data));}catch(error){console.error("Settings PATCH error:",error);return Response.json({error:"Internal server error"},{status:500});}}
