"use client";
import {useMemo,useState,type ReactNode} from "react";
import Sidebar from "@/app/components/Sidebar";
import DashboardHeader from "@/app/components/DashboardHeader";
import {AppWindow,Check,ChevronRight,Globe2,Palette,Smartphone,Boxes,Store} from "lucide-react";

const MODULES=["Dashboard","Sales","Inventory","Purchasing","HR","Accounting","CRM","AI Agents","Reports","Orders"];
const STEPS=["Company","Brand","Modules","Platforms","Review"];

export default function ClientAppsPage(){
 const[step,setStep]=useState(0),[name,setName]=useState(""),[slug,setSlug]=useState(""),[primary,setPrimary]=useState("#19D3FF"),[modules,setModules]=useState<string[]>(["Dashboard","Sales","CRM"]),[platforms,setPlatforms]=useState<string[]>(["Web","PWA"]);
 const valid=useMemo(()=>name.trim().length>1&&slug.trim().length>1,[name,slug]);
 const toggle=(v:string,list:string[],set:(x:string[])=>void)=>set(list.includes(v)?list.filter(x=>x!==v):[...list,v]);
 return <div className="min-h-screen bg-slate-950 text-white"><Sidebar/><div className="min-h-screen md:ml-64"><DashboardHeader/><main className="p-4 md:p-7"><div className="mx-auto max-w-6xl space-y-6">
  <section className="rounded-3xl border border-slate-800 bg-slate-900/50 p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-cyan-300">AVERO · Client Apps</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.04em]">White-label App Builder</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Create a branded company app powered by AVERO. Keep the client identity on the front and AVERO operations underneath.</p></div><div className="rounded-2xl border border-cyan-400/15 bg-cyan-400/[.05] px-4 py-3 text-xs text-cyan-100">Foundation v1 · Web / PWA / iOS / Android</div></div></section>
  <div className="grid gap-5 lg:grid-cols-[260px_1fr]"><aside className="rounded-3xl border border-slate-800 bg-slate-900/45 p-4">{STEPS.map((s,i)=><button key={s} onClick={()=>i<=step&&setStep(i)} className={"mb-2 flex w-full items-center gap-3 rounded-2xl px-3 py-3 text-left text-sm "+(i===step?"bg-cyan-400/[.08] text-cyan-100":"text-slate-500")}><span className={"grid h-7 w-7 place-items-center rounded-full border text-xs "+(i<step?"border-emerald-400/30 bg-emerald-400/10 text-emerald-300":i===step?"border-cyan-400/30 text-cyan-200":"border-slate-800")}>{i<step?<Check size={13}/>:i+1}</span>{s}</button>)}</aside>
  <section className="rounded-3xl border border-slate-800 bg-slate-900/50 p-6">
   {step===0&&<div><Head icon={<Store/>} title="Choose the company" sub="The generated app stays isolated to this company tenant."/><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="App / Company name" value={name} set={setName} placeholder="Example: Rimal Sweets"/><Field label="App slug" value={slug} set={setSlug} placeholder="rimal-sweets"/></div></div>}
   {step===1&&<div><Head icon={<Palette/>} title="Brand identity" sub="The customer sees their own brand, not an AVERO template."/><div className="mt-6 grid gap-4 md:grid-cols-2"><label className="rounded-2xl border border-slate-800 bg-slate-950/60 p-4"><span className="text-xs text-slate-500">Primary color</span><div className="mt-3 flex items-center gap-3"><input type="color" value={primary} onChange={e=>setPrimary(e.target.value)} className="h-10 w-14 bg-transparent"/><code className="text-sm">{primary}</code></div></label><div className="rounded-2xl border border-slate-800 bg-slate-950/60 p-4"><span className="text-xs text-slate-500">Logo & app icon</span><p className="mt-3 text-sm text-slate-300">Upload support comes in the storage integration phase.</p></div></div></div>}
   {step===2&&<div><Head icon={<Boxes/>} title="Select modules" sub="Only enabled modules will appear inside this client's app."/><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{MODULES.map(m=><button key={m} onClick={()=>toggle(m,modules,setModules)} className={"rounded-2xl border p-4 text-left text-sm "+(modules.includes(m)?"border-cyan-400/25 bg-cyan-400/[.07] text-cyan-100":"border-slate-800 bg-slate-950/50 text-slate-500")}>{modules.includes(m)&&<Check size={14} className="mb-2"/>}{m}</button>)}</div></div>}
   {step===3&&<div><Head icon={<Smartphone/>} title="Choose platforms" sub="One client identity, multiple delivery targets."/><div className="mt-6 grid gap-3 sm:grid-cols-2">{["Web","PWA","iOS","Android"].map(p=><button key={p} onClick={()=>toggle(p,platforms,setPlatforms)} className={"flex items-center justify-between rounded-2xl border p-5 "+(platforms.includes(p)?"border-cyan-400/25 bg-cyan-400/[.07]":"border-slate-800 bg-slate-950/50")}><span className="font-medium">{p}</span>{platforms.includes(p)&&<Check size={16} className="text-cyan-300"/>}</button>)}</div></div>}
   {step===4&&<div><Head icon={<AppWindow/>} title="Review app blueprint" sub="This becomes the reusable configuration used by the future build pipeline."/><div className="mt-6 space-y-3 rounded-2xl border border-slate-800 bg-slate-950/55 p-5 text-sm"><Row k="App" v={name||"—"}/><Row k="Slug" v={slug||"—"}/><Row k="Modules" v={modules.join(", ")||"None"}/><Row k="Platforms" v={platforms.join(", ")||"None"}/><Row k="Brand color" v={primary}/></div><div className="mt-4 rounded-2xl border border-amber-400/15 bg-amber-400/[.05] p-4 text-xs leading-5 text-amber-100/70">Database foundation is prepared. Build automation, store signing and publishing credentials are intentionally separate from this first foundation.</div></div>}
   <div className="mt-8 flex justify-between border-t border-slate-800 pt-5"><button disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))} className="rounded-xl border border-slate-800 px-4 py-2 text-sm text-slate-400 disabled:opacity-30">Back</button>{step<4?<button disabled={step===0&&!valid} onClick={()=>setStep(Math.min(4,step+1))} className="flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-2.5 text-sm font-semibold text-slate-950 disabled:opacity-40">Continue <ChevronRight size={15}/></button>:<button className="flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-2.5 text-sm font-semibold text-slate-950"><Globe2 size={15}/> Save App Blueprint</button>}</div>
  </section></div></div>
 </div></main></div></div>
}
function Head({icon,title,sub}:{icon:ReactNode;title:string;sub:string}){return <div className="flex gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl border border-cyan-400/10 bg-cyan-400/[.05] text-cyan-300">{icon}</div><div><h2 className="text-xl font-semibold">{title}</h2><p className="mt-1 text-sm text-slate-500">{sub}</p></div></div>}
function Field({label,value,set,placeholder}:{label:string;value:string;set:(v:string)=>void;placeholder:string}){return <label><span className="text-xs text-slate-500">{label}</span><input value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-2xl border border-slate-800 bg-slate-950 px-4 py-3 text-sm outline-none focus:border-cyan-400/50"/></label>}
function Row({k,v}:{k:string;v:string}){return <div className="flex justify-between gap-4 border-b border-slate-900 py-2 last:border-0"><span className="text-slate-500">{k}</span><span className="text-right text-slate-200">{v}</span></div>}
