import {createClient} from "@supabase/supabase-js";
import {canAccess,getAuthorizationContext,isKingAdmin,type FeatureKey} from "@/lib/auth/authorization";
const agents={
  sales:{feature:"ai_sales",view:"sales.view",manage:"sales.manage",key:"ai_sales"},
  marketing:{feature:"ai_marketing",view:"marketing.view",manage:"marketing.manage",key:"ai_marketing"},
  hr:{feature:"ai_hr",view:"hr.view",manage:"hr.manage",key:"ai_hr"},
  support:{feature:"ai_support",view:"support.view",manage:"support.manage",key:"ai_support"},
  inventory:{feature:"ai_inventory",view:"inventory.view",manage:"inventory.manage",key:"ai_inventory"},
  "customer-care":{feature:"ai_customer_care",view:"customer_care.view",manage:"customer_care.manage",key:"ai_customer_care"},
  analytics:{feature:"ai_analytics",view:"ai_analytics.view",manage:"ai_analytics.manage",key:"ai_analytics"},
  warehouse:{feature:"ai_warehouse",view:"warehouse.view",manage:"warehouse.manage",key:"ai_warehouse"}
} as const satisfies Record<string,{feature:FeatureKey;view:string;manage:string;key:string}>;
type Agent=keyof typeof agents;
function db(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SECRET_KEY;if(!u||!k)throw new Error("Missing Supabase configuration");return createClient(u,k)}
export async function GET(_:Request,{params}:{params:Promise<{agent:string}>}){try{const {agent}=await params;if(!(agent in agents))return Response.json({error:"Unknown agent"},{status:404});const a=agents[agent as Agent],ctx=await getAuthorizationContext();if(!ctx)return Response.json({error:"Unauthorized"},{status:401});if(!canAccess(ctx,a.feature,a.view))return Response.json({error:"Forbidden"},{status:403});const companyId=ctx.profile.company_id;if(!companyId)return Response.json({error:"Company not configured"},{status:409});const s=db();const [{data:profile,error:pErr},{data:config,error:cErr}]=await Promise.all([s.from("company_ai_profiles").select("*").eq("company_id",companyId).maybeSingle(),s.from("ai_agent_configs").select("id,company_id,agent_key,enabled,instructions,knowledge_scope,autonomy_mode,created_at,updated_at").eq("company_id",companyId).eq("agent_key",a.key).maybeSingle()]);if(pErr||cErr)return Response.json({error:"Failed to load AI configuration"},{status:500});return Response.json({agent:a.key,company_profile:profile,config});}catch(e){console.error(e);return Response.json({error:"Internal server error"},{status:500})}}
export async function PUT(request:Request,{params}:{params:Promise<{agent:string}>}){try{const {agent}=await params;if(!(agent in agents))return Response.json({error:"Unknown agent"},{status:404});const a=agents[agent as Agent],ctx=await getAuthorizationContext();if(!ctx)return Response.json({error:"Unauthorized"},{status:401});if(!(isKingAdmin(ctx)||canAccess(ctx,a.feature,a.manage)))return Response.json({error:"Forbidden"},{status:403});const companyId=ctx.profile.company_id;if(!companyId)return Response.json({error:"Company not configured"},{status:409});const body=await request.json(),s=db(),now=new Date().toISOString();const profile={company_id:companyId,industry:String(body.industry||"").slice(0,160)||null,business_description:String(body.business_description||"").slice(0,5000)||null,products_services:String(body.products_services||"").slice(0,8000)||null,target_audience:String(body.target_audience||"").slice(0,4000)||null,brand_voice:String(body.brand_voice||"").slice(0,2000)||null,locations:String(body.locations||"").slice(0,2000)||null,website_url:String(body.website_url||"").slice(0,1000)||null,social_notes:String(body.social_notes||"").slice(0,4000)||null,updated_at:now};const config={company_id:companyId,agent_key:a.key,enabled:true,instructions:String(body.instructions||"").slice(0,12000)||null,knowledge_scope:"Use only this tenant's company profile, approved knowledge and tenant-scoped records. Never infer or borrow data from another company.",autonomy_mode:["draft","approval","automatic"].includes(body.autonomy_mode)?body.autonomy_mode:"approval",updated_at:now};const [{error:pErr},{error:cErr}]=await Promise.all([s.from("company_ai_profiles").upsert(profile),s.from("ai_agent_configs").upsert(config,{onConflict:"company_id,agent_key"})]);if(pErr||cErr)return Response.json({error:"Failed to save AI configuration"},{status:500});return Response.json({ok:true});}catch(e){console.error(e);return Response.json({error:"Internal server error"},{status:500})}}
