// @ts-nocheck
import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { getAuthorizationContext } from "@/lib/auth/authorization";
const db=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SECRET_KEY!,{auth:{persistSession:false}});
async function context(){const a=await getAuthorizationContext();return a?.profile?.company_id?{a,companyId:a.profile.company_id,s:db()}:null}
export async function GET(){const c=await context();if(!c)return NextResponse.json({error:"Unauthorized"},{status:401});const [{data:items},{data:warehouses},{data:units},{data:balances},{data:batches},{data:movements},{data:suppliers}]=await Promise.all([
 c.s.from("inventory_items").select("*").eq("company_id",c.companyId).order("created_at",{ascending:false}),
 c.s.from("inventory_warehouses").select("*").eq("company_id",c.companyId).order("name"),
 c.s.from("inventory_units").select("*").eq("company_id",c.companyId).eq("active",true).order("name"),
 c.s.from("inventory_stock_balances").select("*").eq("company_id",c.companyId),
 c.s.from("inventory_batches").select("*").eq("company_id",c.companyId).order("expiry_date",{ascending:true}),
 c.s.from("inventory_stock_movements").select("*").eq("company_id",c.companyId).order("movement_date",{ascending:false}).limit(100),
 c.s.from("suppliers").select("id,name,supplier_code").eq("company_id",c.companyId).eq("status","active").order("name")
]);
 const today=new Date();const soon=new Date(Date.now()+30*86400000);const expiring=(batches||[]).filter((b:any)=>b.expiry_date&&new Date(b.expiry_date)>=today&&new Date(b.expiry_date)<=soon&&Number(b.qty_on_hand||0)>0).length;const totalValue=(balances||[]).reduce((a:number,b:any)=>a+Number(b.qty_on_hand||0)*Number(b.average_cost||0),0);const low=(items||[]).filter((i:any)=>{const q=(balances||[]).filter((b:any)=>b.item_id===i.id).reduce((a:number,b:any)=>a+Number(b.qty_on_hand||0),0);return q<=Number(i.reorder_point||i.min_stock||0)}).length;const out=(items||[]).filter((i:any)=>{const q=(balances||[]).filter((b:any)=>b.item_id===i.id).reduce((a:number,b:any)=>a+Number(b.qty_on_hand||0),0);return q<=0}).length;
 return NextResponse.json({items:items||[],warehouses:warehouses||[],units:units||[],suppliers:suppliers||[],balances:balances||[],batches:batches||[],movements:movements||[],summary:{items:(items||[]).length,warehouses:(warehouses||[]).length,total_value:totalValue,low_stock:low,out_of_stock:out,expiring_30d:expiring}})}
export async function POST(req:Request){const c=await context();if(!c)return NextResponse.json({error:"Unauthorized"},{status:401});const b=await req.json();const kind=b.kind;const data=b.data||{};
 if(kind==="unit"){if(!data.code||!data.name)return NextResponse.json({error:"Unit code and name required"},{status:400});const {data:r,error}=await c.s.from("inventory_units").insert({company_id:c.companyId,code:String(data.code).trim().toUpperCase(),name:String(data.name).trim(),symbol:data.symbol||null,category:data.category||"count",precision:Number(data.precision??2),active:true}).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({record:r})}
 if(kind==="warehouse"){if(!data.name)return NextResponse.json({error:"Warehouse name required"},{status:400});const code=String(data.code||"").trim().toUpperCase()||`WH-${Date.now().toString().slice(-5)}`;const {data:r,error}=await c.s.from("inventory_warehouses").insert({company_id:c.companyId,code,name:String(data.name).trim(),warehouse_type:data.warehouse_type||"warehouse",address:data.address||null,city:data.city||null,country:data.country||null,is_default:!!data.is_default,allow_sales:!!data.allow_sales,active:true}).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({record:r})}
 if(kind==="item"){if(!data.name)return NextResponse.json({error:"Item name required"},{status:400});const sku=String(data.sku||"").trim().toUpperCase()||`ITM-${Date.now().toString().slice(-7)}`;const payload={company_id:c.companyId,sku,barcode:String(data.barcode||"").trim()||null,name:String(data.name).trim(),item_type:data.item_type||"raw_material",category:data.category||null,brand:data.brand||null,description:data.description||null,image_url:data.image_url||null,base_unit_id:data.base_unit_id||null,purchase_unit_id:data.purchase_unit_id||data.base_unit_id||null,purchase_to_base_factor:Number(data.purchase_to_base_factor||1),tax_enabled:!!data.tax_enabled,tax_rate:data.tax_enabled?Number(data.tax_rate||0):0,costing_method:data.costing_method||"weighted_average",standard_cost:Number(data.standard_cost||0),average_cost:0,last_purchase_cost:Number(data.last_purchase_cost||0),min_stock:Number(data.min_stock||0),max_stock:Number(data.max_stock||0),reorder_point:Number(data.reorder_point||0),safety_stock:Number(data.safety_stock||0),track_batches:!!data.track_batches,track_expiry:!!data.track_expiry,track_serials:!!data.track_serials,allow_negative_stock:!!data.allow_negative_stock,active:true,notes:data.notes||null,created_by:c.a.user?.id,updated_by:c.a.user?.id};const {data:r,error}=await c.s.from("inventory_items").insert(payload).select("*").single();if(error)return NextResponse.json({error:error.message},{status:500});if(data.supplier_id){await c.s.from("inventory_item_suppliers").insert({company_id:c.companyId,item_id:r.id,supplier_id:data.supplier_id,supplier_item_code:data.supplier_item_code||null,supplier_item_name:data.supplier_item_name||null,purchase_unit_id:payload.purchase_unit_id,conversion_factor:payload.purchase_to_base_factor,last_price:Number(data.last_purchase_cost||0),minimum_order_qty:Number(data.minimum_order_qty||0),lead_time_days:Number(data.lead_time_days||0),preferred:true,active:true})}if(data.opening_warehouse_id&&Number(data.opening_qty||0)>0){const {error:moveError}=await c.s.rpc("inventory_post_movement",{p_company_id:c.companyId,p_item_id:r.id,p_warehouse_id:data.opening_warehouse_id,p_location_id:null,p_movement_type:"opening",p_quantity:Number(data.opening_qty),p_unit_cost:Number(data.opening_unit_cost||data.last_purchase_cost||data.standard_cost||0),p_reference_type:"opening_stock",p_reference_id:null,p_reference_no:null,p_reason:"Opening stock",p_created_by:c.a.user?.id});if(moveError)return NextResponse.json({error:`Item created but opening stock failed: ${moveError.message}`,record:r},{status:500})}return NextResponse.json({record:r})}
 if(kind==="stock_movement"){const qty=Number(data.quantity||0);if(!data.item_id||!data.warehouse_id||!qty)return NextResponse.json({error:"Item, warehouse and quantity are required"},{status:400});const type=data.movement_type||(qty>0?"adjustment_in":"adjustment_out");const {data:r,error}=await c.s.rpc("inventory_post_movement",{p_company_id:c.companyId,p_item_id:data.item_id,p_warehouse_id:data.warehouse_id,p_location_id:data.location_id||null,p_movement_type:type,p_quantity:qty,p_unit_cost:data.unit_cost===undefined||data.unit_cost===""?null:Number(data.unit_cost),p_reference_type:data.reference_type||"manual_adjustment",p_reference_id:null,p_reference_no:data.reference_no||null,p_reason:data.reason||null,p_created_by:c.a.user?.id});if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({record:r})}
 return NextResponse.json({error:"Invalid inventory action"},{status:400})}
