import {NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
import {getAuthorizationContext,isKingAdmin} from "@/lib/auth/authorization";
function admin(){return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SECRET_KEY!)}
export async function PUT(req:Request,{params}:{params:Promise<{id:string;userId:string}>}){
 const access=await getAuthorizationContext();if(!access)return NextResponse.json({error:'Unauthorized'},{status:401});if(!isKingAdmin(access))return NextResponse.json({error:'Forbidden'},{status:403});
 const {id,userId}=await params,body=await req.json(),db=admin();const {data:target}=await db.from('user_profiles').select('user_id,company_id,role').eq('user_id',userId).eq('company_id',id).maybeSingle();if(!target)return NextResponse.json({error:'User not found'},{status:404});if(target.role==='king_admin')return NextResponse.json({error:'King Admin cannot be modified here'},{status:403});
 if(body.type==='role'){if(!['super_admin','admin','user'].includes(body.role))return NextResponse.json({error:'Invalid role'},{status:400});const {data:role}=await db.from('roles').select('id').eq('key',body.role).maybeSingle();if(!role)return NextResponse.json({error:'Role not configured'},{status:400});const {error}=await db.from('user_profiles').update({role:body.role,role_id:role.id}).eq('user_id',userId).eq('company_id',id);if(error)return NextResponse.json({error:'Could not update role'},{status:500});return NextResponse.json({ok:true});}
 if(body.type==='permission'){if(typeof body.permission_id!=='string'||!['allow','deny','reset'].includes(body.mode))return NextResponse.json({error:'Invalid permission update'},{status:400});const {data:p}=await db.from('permissions').select('id').eq('id',body.permission_id).maybeSingle();if(!p)return NextResponse.json({error:'Permission not found'},{status:404});if(body.mode==='reset'){const {error}=await db.from('user_permission_overrides').delete().eq('user_id',userId).eq('permission_id',body.permission_id);if(error)return NextResponse.json({error:'Could not reset permission'},{status:500});}else{const {error}=await db.from('user_permission_overrides').upsert({user_id:userId,permission_id:body.permission_id,allowed:body.mode==='allow',granted_by:access.user.id,updated_at:new Date().toISOString()},{onConflict:'user_id,permission_id'});if(error)return NextResponse.json({error:'Could not update permission'},{status:500});}return NextResponse.json({ok:true});}
 return NextResponse.json({error:'Unsupported update'},{status:400});
}