-- total_cost is generated by PostgreSQL; never supply it explicitly.
create or replace function public.inventory_post_movement(p_company_id uuid,p_item_id uuid,p_warehouse_id uuid,p_location_id uuid,p_movement_type text,p_quantity numeric,p_unit_cost numeric default 0,p_reference_type text default null,p_reference_id uuid default null,p_reference_no text default null,p_reason text default null,p_created_by uuid default null,p_batch_id uuid default null)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_id uuid; v_balance record; v_new_qty numeric; v_new_avg numeric; v_allow_negative boolean; v_cost numeric;
begin
 if p_quantity=0 then raise exception 'Quantity cannot be zero'; end if;
 select allow_negative_stock into v_allow_negative from inventory_items where id=p_item_id and company_id=p_company_id and active=true;
 if not found then raise exception 'Item not found or inactive'; end if;
 if not exists(select 1 from inventory_warehouses where id=p_warehouse_id and company_id=p_company_id and active=true) then raise exception 'Warehouse not found or inactive'; end if;
 if p_location_id is not null and not exists(select 1 from inventory_locations where id=p_location_id and company_id=p_company_id and warehouse_id=p_warehouse_id and active=true) then raise exception 'Invalid location'; end if;
 select * into v_balance from inventory_stock_balances where company_id=p_company_id and item_id=p_item_id and warehouse_id=p_warehouse_id and location_id is not distinct from p_location_id for update;
 if not found then begin insert into inventory_stock_balances(company_id,item_id,warehouse_id,location_id,qty_on_hand,qty_reserved,qty_incoming,average_cost) values(p_company_id,p_item_id,p_warehouse_id,p_location_id,0,0,0,0) returning * into v_balance; exception when unique_violation then select * into v_balance from inventory_stock_balances where company_id=p_company_id and item_id=p_item_id and warehouse_id=p_warehouse_id and location_id is not distinct from p_location_id for update; end; end if;
 v_new_qty:=coalesce(v_balance.qty_on_hand,0)+p_quantity;
 if v_new_qty<0 and not coalesce(v_allow_negative,false) then raise exception 'Insufficient stock'; end if;
 v_cost:=case when coalesce(p_unit_cost,0)>0 then p_unit_cost else coalesce(v_balance.average_cost,0) end;
 if p_quantity>0 and v_new_qty>0 then v_new_avg:=((coalesce(v_balance.qty_on_hand,0)*coalesce(v_balance.average_cost,0))+(p_quantity*v_cost))/v_new_qty; else v_new_avg:=coalesce(v_balance.average_cost,0); end if;
 update inventory_stock_balances set qty_on_hand=v_new_qty,average_cost=v_new_avg,updated_at=now() where id=v_balance.id;
 insert into inventory_stock_movements(company_id,item_id,warehouse_id,location_id,batch_id,movement_type,quantity,unit_cost,reference_type,reference_id,reference_no,reason,movement_date,created_by) values(p_company_id,p_item_id,p_warehouse_id,p_location_id,p_batch_id,p_movement_type,p_quantity,v_cost,p_reference_type,p_reference_id,p_reference_no,p_reason,now(),p_created_by) returning id into v_id;
 if p_batch_id is not null then update inventory_batches set qty_on_hand=qty_on_hand+p_quantity where id=p_batch_id and company_id=p_company_id; end if;
 update inventory_items set average_cost=v_new_avg,last_purchase_cost=case when p_movement_type in ('purchase','purchase_receipt','opening') and p_quantity>0 then v_cost else last_purchase_cost end,updated_at=now(),updated_by=coalesce(p_created_by,updated_by) where id=p_item_id and company_id=p_company_id;
 return v_id;
end $$;