// @ts-nocheck
import {NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
import {getAuthorizationContext,isKingAdmin,isTenantAdmin,hasPermission} from "@/lib/auth/authorization";
const admin=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SECRET_KEY!,{auth:{persistSession:false}});async function ctx(){const a=await getAuthorizationContext();return a?.profile?.company_id?{a,c:a.profile.company_id,s:admin()}:null}const can=(a:any,p:string)=>isKingAdmin(a)||isTenantAdmin(a)||hasPermission(a,p)||hasPermission(a,"inventory.manage");
export async function GET(){const x=await ctx();if(!x)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(x.a,"purchasing.view"))return NextResponse.json({error:"Forbidden"},{status:403});const q=(t:string,s="*")=>x.s.from(t).select(s).eq("company_id",x.c).order("created_at",{ascending:false}).limit(100);const [suppliers,items,warehouses,pos,receipts,invoices,prs,rfqs,quotes,payments,credits]=await Promise.all([x.s.from("suppliers").select("id,name,supplier_code,currency,payment_terms_days").eq("company_id",x.c).eq("status","active").order("name"),x.s.from("inventory_items").select("id,sku,name,purchase_unit_id,last_purchase_cost,tax_rate").eq("company_id",x.c).eq("active",true).order("name"),x.s.from("inventory_warehouses").select("id,code,name").eq("company_id",x.c).eq("active",true).order("name"),q("purchase_orders","*,suppliers(name),inventory_warehouses(name),purchase_order_lines(*)"),q("purchase_receipts","*,purchase_receipt_lines(*)"),q("supplier_invoices"),q("purchase_requests","*,purchase_request_lines(*)"),q("purchase_rfqs"),q("purchase_quotes"),q("supplier_payments"),q("supplier_credit_notes")]);return NextResponse.json({suppliers:suppliers.data||[],items:items.data||[],warehouses:warehouses.data||[],purchase_orders:pos.data||[],receipts:receipts.data||[],invoices:invoices.data||[],requests:prs.data||[],rfqs:rfqs.data||[],quotes:quotes.data||[],payments:payments.data||[],credits:credits.data||[]})}
export async function POST(req:Request){const x=await ctx();if(!x)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(x.a,"purchasing.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const b=await req.json(),d=b.data||{};let r:any;
if(b.kind==="purchase_request")r=await x.s.rpc("purchasing_create_request",{p_company_id:x.c,p_warehouse_id:d.warehouse_id,p_needed_by:d.needed_by||null,p_priority:d.priority||"normal",p_department:d.department||null,p_reason:d.reason||null,p_notes:d.notes||null,p_lines:d.lines||[],p_created_by:x.a.user.id});
else if(b.kind==="approve_request")r=await x.s.rpc("purchasing_approve_request",{p_company_id:x.c,p_request_id:d.request_id,p_actor:x.a.user.id,p_approve:!!d.approve,p_comment:d.comment||null});
else if(b.kind==="purchase_order")r=await x.s.rpc("purchasing_create_po",{p_company_id:x.c,p_supplier_id:d.supplier_id,p_warehouse_id:d.warehouse_id,p_expected_date:d.expected_date||null,p_currency:d.currency||"SAR",p_payment_terms_days:Number(d.payment_terms_days||0),p_notes:d.notes||null,p_lines:d.lines||[],p_created_by:x.a.user.id});
else if(b.kind==="receive_po")r=await x.s.rpc("purchasing_receive_po",{p_company_id:x.c,p_po_id:d.po_id,p_lines:d.lines||[],p_received_by:x.a.user.id,p_delivery_note:d.delivery_note||null});
else if(b.kind==="pay_invoice")r=await x.s.rpc("purchasing_pay_invoice",{p_company_id:x.c,p_invoice_id:d.invoice_id,p_amount:Number(d.amount||0),p_method:d.payment_method||"bank_transfer",p_reference:d.reference_no||null,p_notes:d.notes||null,p_actor:x.a.user.id});
else if(b.kind==="supplier_invoice"){if(!d.supplier_id||!d.invoice_no||Number(d.total||0)<0)return NextResponse.json({error:"Supplier, invoice number and valid total required"},{status:400});const po=d.po_id?await x.s.from("purchase_orders").select("total,supplier_id").eq("id",d.po_id).eq("company_id",x.c).maybeSingle():null;const match=po?.data&&po.data.supplier_id===d.supplier_id&&Math.abs(Number(po.data.total)-Number(d.total))<0.01?"matched":"warning";const ins=await x.s.from("supplier_invoices").insert({company_id:x.c,supplier_id:d.supplier_id,po_id:d.po_id||null,invoice_no:d.invoice_no,invoice_date:d.invoice_date||new Date().toISOString().slice(0,10),due_date:d.due_date||null,currency:d.currency||"SAR",subtotal:Number(d.subtotal||d.total||0),tax:Number(d.tax||0),freight:Number(d.freight||0),total:Number(d.total||0),status:"unpaid",match_status:match,notes:d.notes||null,created_by:x.a.user.id}).select("*").single();if(ins.error)return NextResponse.json({error:ins.error.message},{status:400});await x.s.from("supplier_transactions").insert({company_id:x.c,supplier_id:d.supplier_id,transaction_type:"invoice",reference_no:d.invoice_no,transaction_date:d.invoice_date||new Date().toISOString().slice(0,10),due_date:d.due_date||null,amount:Number(d.total||0),paid_amount:0,currency:d.currency||"SAR",notes:`Purchasing invoice ${d.invoice_no}`});return NextResponse.json({record:ins.data})}else return NextResponse.json({error:"Invalid purchasing action"},{status:400});if(r.error)return NextResponse.json({error:r.error.message},{status:400});return NextResponse.json({result:r.data})}
