// @ts-nocheck
import {NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";
import {getAuthorizationContext,isKingAdmin,isTenantAdmin,hasPermission} from "@/lib/auth/authorization";
const admin=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SECRET_KEY!,{auth:{persistSession:false}});
async function ctx(){const a=await getAuthorizationContext();return a?.profile?.company_id?{a,c:a.profile.company_id,s:admin()}:null}
const can=(a:any,p:string)=>isKingAdmin(a)||isTenantAdmin(a)||hasPermission(a,p)||hasPermission(a,"inventory.manage");
export async function GET(){const x=await ctx();if(!x)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(x.a,"purchasing.view"))return NextResponse.json({error:"Forbidden"},{status:403});const [suppliers,items,warehouses,pos,receipts,invoices,prs]=await Promise.all([x.s.from("suppliers").select("id,name,supplier_code,currency,payment_terms_days").eq("company_id",x.c).eq("status","active").order("name"),x.s.from("inventory_items").select("id,sku,name,purchase_unit_id,last_purchase_cost,tax_rate").eq("company_id",x.c).eq("active",true).order("name"),x.s.from("inventory_warehouses").select("id,code,name").eq("company_id",x.c).eq("active",true).order("name"),x.s.from("purchase_orders").select("*,suppliers(name),inventory_warehouses(name),purchase_order_lines(*)").eq("company_id",x.c).order("created_at",{ascending:false}).limit(100),x.s.from("purchase_receipts").select("*,purchase_receipt_lines(*)").eq("company_id",x.c).order("created_at",{ascending:false}).limit(100),x.s.from("supplier_invoices").select("*").eq("company_id",x.c).order("created_at",{ascending:false}).limit(100),x.s.from("purchase_requests").select("*,purchase_request_lines(*)").eq("company_id",x.c).order("created_at",{ascending:false}).limit(100)]);return NextResponse.json({suppliers:suppliers.data||[],items:items.data||[],warehouses:warehouses.data||[],purchase_orders:pos.data||[],receipts:receipts.data||[],invoices:invoices.data||[],requests:prs.data||[]})}
export async function POST(req:Request){const x=await ctx();if(!x)return NextResponse.json({error:"Unauthorized"},{status:401});if(!can(x.a,"purchasing.manage"))return NextResponse.json({error:"Forbidden"},{status:403});const b=await req.json(),d=b.data||{};
if(b.kind==="purchase_order"){const {data,error}=await x.s.rpc("purchasing_create_po",{p_company_id:x.c,p_supplier_id:d.supplier_id,p_warehouse_id:d.warehouse_id,p_expected_date:d.expected_date||null,p_currency:d.currency||"SAR",p_payment_terms_days:Number(d.payment_terms_days||0),p_notes:d.notes||null,p_lines:d.lines||[],p_created_by:x.a.user.id});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({id:data})}
if(b.kind==="receive_po"){const {data,error}=await x.s.rpc("purchasing_receive_po",{p_company_id:x.c,p_po_id:d.po_id,p_lines:d.lines||[],p_received_by:x.a.user.id,p_delivery_note:d.delivery_note||null});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({id:data})}
if(b.kind==="supplier_invoice"){if(!d.supplier_id||!d.invoice_no||Number(d.total||0)<0)return NextResponse.json({error:"Supplier, invoice number and valid total required"},{status:400});const {data:r,error}=await x.s.from("supplier_invoices").insert({company_id:x.c,supplier_id:d.supplier_id,po_id:d.po_id||null,invoice_no:d.invoice_no,invoice_date:d.invoice_date||new Date().toISOString().slice(0,10),due_date:d.due_date||null,currency:d.currency||"SAR",subtotal:Number(d.subtotal||d.total||0),tax:Number(d.tax||0),freight:Number(d.freight||0),total:Number(d.total||0),status:"unpaid",match_status:d.po_id?"pending":"warning",notes:d.notes||null,created_by:x.a.user.id}).select("*").single();if(error)return NextResponse.json({error:error.message},{status:400});await x.s.from("supplier_transactions").insert({company_id:x.c,supplier_id:d.supplier_id,transaction_type:"invoice",reference_no:d.invoice_no,transaction_date:d.invoice_date||new Date().toISOString().slice(0,10),due_date:d.due_date||null,amount:Number(d.total||0),paid_amount:0,currency:d.currency||"SAR",notes:`Purchasing invoice ${d.invoice_no}`});return NextResponse.json({record:r})}
return NextResponse.json({error:"Invalid purchasing action"},{status:400})}
