"use client";

import { useEffect, useMemo, useState } from "react";
import Sidebar from "@/app/components/Sidebar";
import DashboardHeader from "@/app/components/DashboardHeader";
import { useLanguage } from "@/app/components/LanguageProvider";
import { Headphones, MessageSquareText, RefreshCw, Building2, UserRound } from "lucide-react";

type SessionRow = { id:string; user_id:string; company_id:string; status:string; created_at:string; updated_at:string; company?:{id:string;name:string}|null; profile?:{first_name?:string|null;last_name?:string|null;full_name?:string|null;nickname?:string|null;username?:string|null;avatar_url?:string|null}|null; last_message?:{role:string;message:string;created_at:string}|null };
type Detail = { session: SessionRow; messages: {id:string;role:string;message:string;created_at:string}[] };

function personName(row:SessionRow){const p=row.profile;return [p?.first_name,p?.last_name].filter(Boolean).join(" ")||p?.full_name||p?.nickname||p?.username||"User";}
function fmt(value:string,ar:boolean){try{return new Intl.DateTimeFormat(ar?"ar-SA":"en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));}catch{return value;}}

export default function AdminHelpCenterPage(){
 const {language}=useLanguage();const ar=language==="ar";
 const [sessions,setSessions]=useState<SessionRow[]>([]);const [selected,setSelected]=useState<string>("");const [detail,setDetail]=useState<Detail|null>(null);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState("");
 const loadInbox=async(silent=false)=>{if(!silent)setLoading(true);else setRefreshing(true);setError("");try{const r=await fetch("/api/admin/help-center",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Failed to load inbox");setSessions(Array.isArray(d)?d:[]);if(!selected&&d?.[0]?.id)setSelected(d[0].id);}catch(e){setError(e instanceof Error?e.message:"Failed to load inbox");}finally{setLoading(false);setRefreshing(false)}};
 const loadDetail=async(id:string)=>{if(!id){setDetail(null);return;}try{const r=await fetch(`/api/admin/help-center?session_id=${encodeURIComponent(id)}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Failed to load conversation");setDetail(d);}catch(e){setError(e instanceof Error?e.message:"Failed to load conversation");}};
 useEffect(()=>{loadInbox();const t=setInterval(()=>loadInbox(true),15000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(selected)loadDetail(selected)},[selected]);
 useEffect(()=>{const t=setInterval(()=>{if(selected)loadDetail(selected)},10000);return()=>clearInterval(t)},[selected]);
 const selectedRow=useMemo(()=>sessions.find(s=>s.id===selected)||detail?.session||null,[sessions,selected,detail]);
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-slate-950 text-slate-400">{ar?"جارٍ تحميل صندوق الدعم...":"Loading support inbox..."}</div>;
 return <div className="min-h-screen bg-slate-950"><Sidebar/><div className="ml-64 flex min-h-screen flex-col"><DashboardHeader/><main className="flex-1 px-6 py-7 text-white"><div className="mx-auto max-w-7xl">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.2em] text-violet-400"><Headphones size={15}/>{ar?"صندوق دعم AVERO":"AVERO SUPPORT INBOX"}</div><h1 className="text-3xl font-bold">{ar?"محادثات العملاء مع مركز المساعدة":"Client Help Center Conversations"}</h1><p className="mt-2 text-sm text-slate-400">{ar?"شاهد كل رسالة يرسلها العميل للـ AI ومحادثة الدعم كاملة من مكان واحد.":"See every client message sent to the AI and the full support conversation in one place."}</p></div><button onClick={()=>loadInbox(true)} disabled={refreshing} className="inline-flex items-center gap-2 rounded-xl border border-slate-700 bg-slate-900 px-4 py-2.5 text-sm text-slate-300 hover:border-slate-600 hover:text-white disabled:opacity-50"><RefreshCw size={16} className={refreshing?"animate-spin":""}/>{ar?"تحديث":"Refresh"}</button></div>
  {error&&<div className="mt-5 rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-300">{error}</div>}
  <div className="mt-6 grid min-h-[620px] overflow-hidden rounded-3xl border border-slate-800 bg-slate-900/55 lg:grid-cols-[360px_1fr]">
   <aside className="border-b border-slate-800 lg:border-b-0 lg:border-r"><div className="border-b border-slate-800 px-4 py-3 text-xs font-semibold uppercase tracking-[.15em] text-slate-500">{ar?`${sessions.length} محادثة`:`${sessions.length} conversations`}</div><div className="max-h-[620px] overflow-y-auto">{sessions.length===0?<div className="p-6 text-sm text-slate-500">{ar?"لا توجد محادثات بعد.":"No conversations yet."}</div>:sessions.map(row=>{const active=row.id===selected;const name=personName(row);const preview=row.last_message?.message||"";return <button key={row.id} onClick={()=>setSelected(row.id)} className={`w-full border-b border-slate-800/80 p-4 text-start transition ${active?"bg-blue-500/10":"hover:bg-slate-900"}`}><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-slate-800 text-xs font-semibold text-slate-300">{row.profile?.avatar_url?<img src={row.profile.avatar_url} alt="" className="h-full w-full object-cover"/>:name.slice(0,2).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="truncate text-sm font-semibold text-white">{name}</p><span className="shrink-0 text-[10px] text-slate-600">{fmt(row.updated_at||row.created_at,ar)}</span></div><p className="mt-0.5 truncate text-xs text-blue-300">{row.company?.name||"—"}</p><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{preview|| (ar?"لا توجد رسائل":"No messages")}</p></div></div></button>})}</div></aside>
   <section className="flex min-w-0 flex-col">{!selectedRow?<div className="flex flex-1 items-center justify-center p-8 text-slate-500">{ar?"اختر محادثة من القائمة":"Select a conversation"}</div>:<><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 p-5"><div><div className="flex items-center gap-2"><UserRound size={17} className="text-blue-300"/><p className="font-semibold">{personName(selectedRow)}</p></div><div className="mt-1 flex items-center gap-2 text-xs text-slate-500"><Building2 size={13}/><span>{selectedRow.company?.name||detail?.session.company?.name||"—"}</span><span>•</span><span>{selectedRow.status}</span></div></div><div className="rounded-full border border-emerald-500/20 bg-emerald-500/10 px-3 py-1 text-xs text-emerald-300">{ar?"مراقبة مباشرة":"Live monitoring"}</div></div><div className="flex-1 space-y-3 overflow-y-auto p-5">{detail?.messages?.length?detail.messages.map(m=><div key={m.id} className={`flex ${m.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[78%] rounded-2xl px-4 py-3 text-sm leading-6 ${m.role==="user"?"bg-blue-600 text-white":"border border-slate-800 bg-slate-950 text-slate-300"}`}><div>{m.message}</div><div className={`mt-1 text-[10px] ${m.role==="user"?"text-blue-100/70":"text-slate-600"}`}>{m.role==="user"?(ar?"العميل":"Client"):(m.role==="assistant"?(ar?"AVERO AI":"AVERO AI"):m.role)} · {fmt(m.created_at,ar)}</div></div></div>):<div className="flex h-full items-center justify-center text-sm text-slate-500">{ar?"لا توجد رسائل في هذه المحادثة":"No messages in this conversation"}</div>}</div></>}</section>
  </div>
  <p className="mt-4 text-center text-xs text-slate-600">{ar?"الصندوق متاح لمسؤول AVERO الأعلى فقط، ويتم تحديثه تلقائياً أثناء محادثة العميل مع الذكاء الاصطناعي.":"This inbox is restricted to AVERO super admins and refreshes automatically while the client is chatting with the AI."}</p>
 </div></main></div></div>;
}
