import { createClient } from "@supabase/supabase-js";
import { createClient as createServerClient } from "@/lib/supabase/server";
export type FeatureKey="ai_sales"|"crm"|"analytics"|"ai_marketing"|"ai_hr"|"ai_support";
export interface AuthorizationContext{user:{id:string;email?:string};profile:{company_id:string|null;role:string|null;role_id:string|null};permissions:string[];features:string[]}
const LEGACY_PERMISSION_ALIASES:Record<string,string>={view_crm:"crm.view",manage_crm:"crm.manage",view_analytics:"analytics.view",view_ai_sales:"sales.view",manage_ai_sales:"sales.manage",view_ai_marketing:"marketing.view",manage_ai_marketing:"marketing.manage",view_ai_hr:"hr.view",manage_ai_hr:"hr.manage",view_ai_support:"support.view",manage_ai_support:"support.manage"};
function normalizePermissionKey(k:string){return LEGACY_PERMISSION_ALIASES[k]||k}function getAdminClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY;if(!url||!key)throw new Error("Missing Supabase configuration");return createClient(url,key)}
export async function getAuthorizationContext():Promise<AuthorizationContext|null>{const authClient=await createServerClient();const{data:{user}}=await authClient.auth.getUser();if(!user)return null;const supabase=getAdminClient();const{data:profile,error:profileError}=await supabase.from("user_profiles").select("company_id, role, role_id").eq("user_id",user.id).maybeSingle();if(profileError)throw profileError;const permissions:string[]=[];if(profile?.role_id){const{data,error}=await supabase.from("role_permissions").select("permissions(key)").eq("role_id",profile.role_id);if(error)throw error;for(const row of data||[]){const p=Array.isArray(row.permissions)?row.permissions[0]:row.permissions;if(p?.key)permissions.push(p.key)}}const features:string[]=[];if(profile?.company_id){const{data,error}=await supabase.from("company_features").select("enabled, expires_at, features(key)").eq("company_id",profile.company_id).eq("enabled",true);if(error)throw error;const now=Date.now();for(const row of data||[]){const f=Array.isArray(row.features)?row.features[0]:row.features;if(f?.key&&(!row.expires_at||new Date(row.expires_at).getTime()>now))features.push(f.key)}}return{user:{id:user.id,email:user.email},profile:{company_id:profile?.company_id??null,role:profile?.role??null,role_id:profile?.role_id??null},permissions,features}}
export function isKingAdmin(c:AuthorizationContext|null){return c?.profile.role==="king_admin"}
export function isSuperAdmin(c:AuthorizationContext|null){return c?.profile.role==="super_admin"}
export function isTenantAdmin(c:AuthorizationContext|null){return isSuperAdmin(c)||c?.profile.role==="admin"}
export function hasPermission(c:AuthorizationContext|null,key:string){return Boolean(isKingAdmin(c)||c?.permissions.includes(normalizePermissionKey(key)))}
export function hasFeature(c:AuthorizationContext|null,key:FeatureKey){return Boolean(isKingAdmin(c)||c?.features.includes(key))}
export function canAccess(c:AuthorizationContext|null,feature:FeatureKey,permission:string){return Boolean(isKingAdmin(c)||(hasFeature(c,feature)&&hasPermission(c,permission)))}
export function canManageCompanyUsers(c:AuthorizationContext|null){return Boolean(isKingAdmin(c)||isSuperAdmin(c)||hasPermission(c,"users.permissions.manage"))}
